// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// SysJob is the predicate function for sysjob builders.
type SysJob func(*sql.Selector)

// SysJobLog is the predicate function for sysjoblog builders.
type SysJobLog func(*sql.Selector)
