// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// SysJobsColumns holds the columns for the "sys_jobs" table.
	SysJobsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, Comment: "Primary Key | 主键ID，可自定义雪花ID"},
		{Name: "created_at", Type: field.TypeTime, Comment: "Create Time | 创建时间"},
		{Name: "created_id", Type: field.TypeInt64, Comment: "Creator ID | 创建人ID"},
		{Name: "created_by", Type: field.TypeString, Size: 64, Comment: "Creator Name | 创建人名称"},
		{Name: "updated_at", Type: field.TypeTime, Comment: "updated Time | 更新时间"},
		{Name: "updated_id", Type: field.TypeInt64, Comment: "updated ID | 更新人ID"},
		{Name: "updated_by", Type: field.TypeString, Size: 64, Comment: "updated Name | 更新人名称"},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true, Comment: "deleted Time | 删除时间"},
		{Name: "deleted_id", Type: field.TypeInt64, Nullable: true, Comment: "deleted ID | 删除人ID，逻辑删除用"},
		{Name: "deleted_by", Type: field.TypeString, Nullable: true, Size: 64, Comment: "deleted Name | 删除人名称"},
		{Name: "status", Type: field.TypeEnum, Comment: "状态：active-有效，inactive-无效，suspended-暂停", Enums: []string{"active", "inactive", "suspended"}, Default: "active"},
		{Name: "remark", Type: field.TypeString, Nullable: true, Size: 255},
		{Name: "name", Type: field.TypeString, Size: 128, Comment: "任务名称 | Job Name"},
		{Name: "group", Type: field.TypeString, Size: 64, Comment: "任务分组(字典 job_group) | Job Group", Default: "default"},
		{Name: "handler", Type: field.TypeString, Size: 128, Comment: "处理器注册码(代码注册表, 如 report.daily) | Handler Code"},
		{Name: "params", Type: field.TypeString, Size: 2147483647, Comment: "处理器参数(JSON) | Handler Params(JSON)", Default: "{}"},
		{Name: "cron_expression", Type: field.TypeString, Size: 255, Comment: "cron表达式(兼容5/6位, 秒可选) | Cron Expression(5/6 fields, seconds optional)"},
		{Name: "time_zone", Type: field.TypeString, Size: 64, Comment: "表达式时区 | Time Zone", Default: "Asia/Shanghai"},
		{Name: "misfire_policy", Type: field.TypeEnum, Comment: "错过执行策略: skip-放弃, fire_once-补跑一次, fire_all-全部补跑 | Misfire Policy", Enums: []string{"skip", "fire_once", "fire_all"}, Default: "fire_once"},
		{Name: "concurrent", Type: field.TypeBool, Comment: "是否允许并发执行(否-同一时刻只跑一次) | Allow Concurrent", Default: false},
		{Name: "timeout", Type: field.TypeInt32, Comment: "单次执行超时(秒) | Timeout(seconds)", Default: 30},
		{Name: "max_retry", Type: field.TypeInt32, Comment: "失败重试次数 | Max Retry", Default: 0},
		{Name: "retry_interval", Type: field.TypeInt32, Comment: "重试间隔(秒) | Retry Interval(seconds)", Default: 10},
		{Name: "next_run_at", Type: field.TypeTime, Nullable: true, Comment: "下次触发时间(调度器回写) | Next Run At"},
		{Name: "last_run_at", Type: field.TypeTime, Nullable: true, Comment: "上次触发时间 | Last Run At"},
		{Name: "last_status", Type: field.TypeString, Nullable: true, Size: 16, Comment: "上次执行结果: success/fail/timeout/skipped/none | Last Status"},
		{Name: "last_duration", Type: field.TypeInt64, Nullable: true, Comment: "上次耗时(毫秒) | Last Duration(ms)"},
		{Name: "last_error", Type: field.TypeString, Nullable: true, Size: 500, Comment: "上次错误摘要 | Last Error"},
	}
	// SysJobsTable holds the schema information for the "sys_jobs" table.
	SysJobsTable = &schema.Table{
		Name:       "sys_jobs",
		Comment:    "job Table | 定时任务表",
		Columns:    SysJobsColumns,
		PrimaryKey: []*schema.Column{SysJobsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idx_jobs_status_next_run",
				Unique:  false,
				Columns: []*schema.Column{SysJobsColumns[10], SysJobsColumns[23]},
			},
			{
				Name:    "sysjob_group",
				Unique:  false,
				Columns: []*schema.Column{SysJobsColumns[13]},
			},
		},
	}
	// SysJobLogsColumns holds the columns for the "sys_job_logs" table.
	SysJobLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, Comment: "Primary Key | 主键ID，可自定义雪花ID"},
		{Name: "created_at", Type: field.TypeTime, Comment: "Create Time | 创建时间"},
		{Name: "created_id", Type: field.TypeInt64, Comment: "Creator ID | 创建人ID"},
		{Name: "created_by", Type: field.TypeString, Size: 64, Comment: "Creator Name | 创建人名称"},
		{Name: "job_id", Type: field.TypeInt64, Comment: "任务ID | Job ID"},
		{Name: "job_name", Type: field.TypeString, Size: 128, Comment: "任务名称(快照) | Job Name(snapshot)", Default: ""},
		{Name: "job_group", Type: field.TypeString, Size: 64, Comment: "任务分组(快照) | Job Group(snapshot)", Default: ""},
		{Name: "handler", Type: field.TypeString, Size: 128, Comment: "处理器注册码(快照) | Handler Code(snapshot)", Default: ""},
		{Name: "trigger_type", Type: field.TypeEnum, Comment: "触发方式: cron-调度, manual-手动, retry-重试 | Trigger Type", Enums: []string{"cron", "manual", "retry"}, Default: "cron"},
		{Name: "exec_node", Type: field.TypeString, Size: 64, Comment: "执行实例标识 | Executor Node", Default: ""},
		{Name: "status", Type: field.TypeEnum, Comment: "执行状态 | Execution Status", Enums: []string{"running", "success", "fail", "timeout", "skipped"}, Default: "running"},
		{Name: "attempt", Type: field.TypeInt32, Comment: "尝试次数(1=首次) | Attempt", Default: 1},
		{Name: "message", Type: field.TypeString, Size: 500, Comment: "结果摘要 | Result Message", Default: ""},
		{Name: "exception_info", Type: field.TypeString, Size: 1000, Comment: "异常信息(截断) | Exception Info(truncated)", Default: ""},
		{Name: "duration", Type: field.TypeInt64, Comment: "执行时长(毫秒) | Duration(ms)", Default: 0},
	}
	// SysJobLogsTable holds the schema information for the "sys_job_logs" table.
	SysJobLogsTable = &schema.Table{
		Name:       "sys_job_logs",
		Comment:    "job_log Table | 定时任务执行日志表",
		Columns:    SysJobLogsColumns,
		PrimaryKey: []*schema.Column{SysJobLogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "sysjoblog_job_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{SysJobLogsColumns[4], SysJobLogsColumns[1]},
			},
			{
				Name:    "sysjoblog_created_at",
				Unique:  false,
				Columns: []*schema.Column{SysJobLogsColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		SysJobsTable,
		SysJobLogsTable,
	}
)

func init() {
	SysJobsTable.Annotation = &entsql.Annotation{
		Table: "sys_jobs",
	}
	SysJobLogsTable.Annotation = &entsql.Annotation{
		Table: "sys_job_logs",
	}
}
