// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/saas-zero/saas-zero-job/ent/predicate"
	"github.com/saas-zero/saas-zero-job/ent/sysjob"
	"github.com/saas-zero/saas-zero-job/ent/sysjoblog"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeSysJob    = "SysJob"
	TypeSysJobLog = "SysJobLog"
)

// SysJobMutation represents an operation that mutates the SysJob nodes in the graph.
type SysJobMutation struct {
	config
	op                Op
	typ               string
	id                *int64
	created_at        *time.Time
	created_id        *int64
	addcreated_id     *int64
	created_by        *string
	updated_at        *time.Time
	updated_id        *int64
	addupdated_id     *int64
	updated_by        *string
	deleted_at        *time.Time
	deleted_id        *int64
	adddeleted_id     *int64
	deleted_by        *string
	status            *sysjob.Status
	remark            *string
	name              *string
	group             *string
	handler           *string
	params            *string
	cron_expression   *string
	time_zone         *string
	misfire_policy    *sysjob.MisfirePolicy
	concurrent        *bool
	timeout           *int32
	addtimeout        *int32
	max_retry         *int32
	addmax_retry      *int32
	retry_interval    *int32
	addretry_interval *int32
	next_run_at       *time.Time
	last_run_at       *time.Time
	last_status       *string
	last_duration     *int64
	addlast_duration  *int64
	last_error        *string
	clearedFields     map[string]struct{}
	done              bool
	oldValue          func(context.Context) (*SysJob, error)
	predicates        []predicate.SysJob
}

var _ ent.Mutation = (*SysJobMutation)(nil)

// sysjobOption allows management of the mutation configuration using functional options.
type sysjobOption func(*SysJobMutation)

// newSysJobMutation creates new mutation for the SysJob entity.
func newSysJobMutation(c config, op Op, opts ...sysjobOption) *SysJobMutation {
	m := &SysJobMutation{
		config:        c,
		op:            op,
		typ:           TypeSysJob,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withSysJobID sets the ID field of the mutation.
func withSysJobID(id int64) sysjobOption {
	return func(m *SysJobMutation) {
		var (
			err   error
			once  sync.Once
			value *SysJob
		)
		m.oldValue = func(ctx context.Context) (*SysJob, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().SysJob.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withSysJob sets the old SysJob of the mutation.
func withSysJob(node *SysJob) sysjobOption {
	return func(m *SysJobMutation) {
		m.oldValue = func(context.Context) (*SysJob, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m SysJobMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m SysJobMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of SysJob entities.
func (m *SysJobMutation) SetID(id int64) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *SysJobMutation) ID() (id int64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *SysJobMutation) IDs(ctx context.Context) ([]int64, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int64{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().SysJob.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreatedAt sets the "created_at" field.
func (m *SysJobMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *SysJobMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the SysJob entity.
// If the SysJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SysJobMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *SysJobMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetCreatedID sets the "created_id" field.
func (m *SysJobMutation) SetCreatedID(i int64) {
	m.created_id = &i
	m.addcreated_id = nil
}

// CreatedID returns the value of the "created_id" field in the mutation.
func (m *SysJobMutation) CreatedID() (r int64, exists bool) {
	v := m.created_id
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedID returns the old "created_id" field's value of the SysJob entity.
// If the SysJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SysJobMutation) OldCreatedID(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedID: %w", err)
	}
	return oldValue.CreatedID, nil
}

// AddCreatedID adds i to the "created_id" field.
func (m *SysJobMutation) AddCreatedID(i int64) {
	if m.addcreated_id != nil {
		*m.addcreated_id += i
	} else {
		m.addcreated_id = &i
	}
}

// AddedCreatedID returns the value that was added to the "created_id" field in this mutation.
func (m *SysJobMutation) AddedCreatedID() (r int64, exists bool) {
	v := m.addcreated_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetCreatedID resets all changes to the "created_id" field.
func (m *SysJobMutation) ResetCreatedID() {
	m.created_id = nil
	m.addcreated_id = nil
}

// SetCreatedBy sets the "created_by" field.
func (m *SysJobMutation) SetCreatedBy(s string) {
	m.created_by = &s
}

// CreatedBy returns the value of the "created_by" field in the mutation.
func (m *SysJobMutation) CreatedBy() (r string, exists bool) {
	v := m.created_by
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedBy returns the old "created_by" field's value of the SysJob entity.
// If the SysJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SysJobMutation) OldCreatedBy(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedBy is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedBy requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedBy: %w", err)
	}
	return oldValue.CreatedBy, nil
}

// ResetCreatedBy resets all changes to the "created_by" field.
func (m *SysJobMutation) ResetCreatedBy() {
	m.created_by = nil
}

// SetUpdatedAt sets the "updated_at" field.
func (m *SysJobMutation) SetUpdatedAt(t time.Time) {
	m.updated_at = &t
}

// UpdatedAt returns the value of the "updated_at" field in the mutation.
func (m *SysJobMutation) UpdatedAt() (r time.Time, exists bool) {
	v := m.updated_at
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedAt returns the old "updated_at" field's value of the SysJob entity.
// If the SysJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SysJobMutation) OldUpdatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedAt: %w", err)
	}
	return oldValue.UpdatedAt, nil
}

// ResetUpdatedAt resets all changes to the "updated_at" field.
func (m *SysJobMutation) ResetUpdatedAt() {
	m.updated_at = nil
}

// SetUpdatedID sets the "updated_id" field.
func (m *SysJobMutation) SetUpdatedID(i int64) {
	m.updated_id = &i
	m.addupdated_id = nil
}

// UpdatedID returns the value of the "updated_id" field in the mutation.
func (m *SysJobMutation) UpdatedID() (r int64, exists bool) {
	v := m.updated_id
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedID returns the old "updated_id" field's value of the SysJob entity.
// If the SysJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SysJobMutation) OldUpdatedID(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedID: %w", err)
	}
	return oldValue.UpdatedID, nil
}

// AddUpdatedID adds i to the "updated_id" field.
func (m *SysJobMutation) AddUpdatedID(i int64) {
	if m.addupdated_id != nil {
		*m.addupdated_id += i
	} else {
		m.addupdated_id = &i
	}
}

// AddedUpdatedID returns the value that was added to the "updated_id" field in this mutation.
func (m *SysJobMutation) AddedUpdatedID() (r int64, exists bool) {
	v := m.addupdated_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetUpdatedID resets all changes to the "updated_id" field.
func (m *SysJobMutation) ResetUpdatedID() {
	m.updated_id = nil
	m.addupdated_id = nil
}

// SetUpdatedBy sets the "updated_by" field.
func (m *SysJobMutation) SetUpdatedBy(s string) {
	m.updated_by = &s
}

// UpdatedBy returns the value of the "updated_by" field in the mutation.
func (m *SysJobMutation) UpdatedBy() (r string, exists bool) {
	v := m.updated_by
	if v == nil {
		return
	}
	return *v, true
}

// OldUpdatedBy returns the old "updated_by" field's value of the SysJob entity.
// If the SysJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SysJobMutation) OldUpdatedBy(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUpdatedBy is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUpdatedBy requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUpdatedBy: %w", err)
	}
	return oldValue.UpdatedBy, nil
}

// ResetUpdatedBy resets all changes to the "updated_by" field.
func (m *SysJobMutation) ResetUpdatedBy() {
	m.updated_by = nil
}

// SetDeletedAt sets the "deleted_at" field.
func (m *SysJobMutation) SetDeletedAt(t time.Time) {
	m.deleted_at = &t
}

// DeletedAt returns the value of the "deleted_at" field in the mutation.
func (m *SysJobMutation) DeletedAt() (r time.Time, exists bool) {
	v := m.deleted_at
	if v == nil {
		return
	}
	return *v, true
}

// OldDeletedAt returns the old "deleted_at" field's value of the SysJob entity.
// If the SysJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SysJobMutation) OldDeletedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDeletedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDeletedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDeletedAt: %w", err)
	}
	return oldValue.DeletedAt, nil
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (m *SysJobMutation) ClearDeletedAt() {
	m.deleted_at = nil
	m.clearedFields[sysjob.FieldDeletedAt] = struct{}{}
}

// DeletedAtCleared returns if the "deleted_at" field was cleared in this mutation.
func (m *SysJobMutation) DeletedAtCleared() bool {
	_, ok := m.clearedFields[sysjob.FieldDeletedAt]
	return ok
}

// ResetDeletedAt resets all changes to the "deleted_at" field.
func (m *SysJobMutation) ResetDeletedAt() {
	m.deleted_at = nil
	delete(m.clearedFields, sysjob.FieldDeletedAt)
}

// SetDeletedID sets the "deleted_id" field.
func (m *SysJobMutation) SetDeletedID(i int64) {
	m.deleted_id = &i
	m.adddeleted_id = nil
}

// DeletedID returns the value of the "deleted_id" field in the mutation.
func (m *SysJobMutation) DeletedID() (r int64, exists bool) {
	v := m.deleted_id
	if v == nil {
		return
	}
	return *v, true
}

// OldDeletedID returns the old "deleted_id" field's value of the SysJob entity.
// If the SysJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SysJobMutation) OldDeletedID(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDeletedID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDeletedID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDeletedID: %w", err)
	}
	return oldValue.DeletedID, nil
}

// AddDeletedID adds i to the "deleted_id" field.
func (m *SysJobMutation) AddDeletedID(i int64) {
	if m.adddeleted_id != nil {
		*m.adddeleted_id += i
	} else {
		m.adddeleted_id = &i
	}
}

// AddedDeletedID returns the value that was added to the "deleted_id" field in this mutation.
func (m *SysJobMutation) AddedDeletedID() (r int64, exists bool) {
	v := m.adddeleted_id
	if v == nil {
		return
	}
	return *v, true
}

// ClearDeletedID clears the value of the "deleted_id" field.
func (m *SysJobMutation) ClearDeletedID() {
	m.deleted_id = nil
	m.adddeleted_id = nil
	m.clearedFields[sysjob.FieldDeletedID] = struct{}{}
}

// DeletedIDCleared returns if the "deleted_id" field was cleared in this mutation.
func (m *SysJobMutation) DeletedIDCleared() bool {
	_, ok := m.clearedFields[sysjob.FieldDeletedID]
	return ok
}

// ResetDeletedID resets all changes to the "deleted_id" field.
func (m *SysJobMutation) ResetDeletedID() {
	m.deleted_id = nil
	m.adddeleted_id = nil
	delete(m.clearedFields, sysjob.FieldDeletedID)
}

// SetDeletedBy sets the "deleted_by" field.
func (m *SysJobMutation) SetDeletedBy(s string) {
	m.deleted_by = &s
}

// DeletedBy returns the value of the "deleted_by" field in the mutation.
func (m *SysJobMutation) DeletedBy() (r string, exists bool) {
	v := m.deleted_by
	if v == nil {
		return
	}
	return *v, true
}

// OldDeletedBy returns the old "deleted_by" field's value of the SysJob entity.
// If the SysJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SysJobMutation) OldDeletedBy(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDeletedBy is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDeletedBy requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDeletedBy: %w", err)
	}
	return oldValue.DeletedBy, nil
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (m *SysJobMutation) ClearDeletedBy() {
	m.deleted_by = nil
	m.clearedFields[sysjob.FieldDeletedBy] = struct{}{}
}

// DeletedByCleared returns if the "deleted_by" field was cleared in this mutation.
func (m *SysJobMutation) DeletedByCleared() bool {
	_, ok := m.clearedFields[sysjob.FieldDeletedBy]
	return ok
}

// ResetDeletedBy resets all changes to the "deleted_by" field.
func (m *SysJobMutation) ResetDeletedBy() {
	m.deleted_by = nil
	delete(m.clearedFields, sysjob.FieldDeletedBy)
}

// SetStatus sets the "status" field.
func (m *SysJobMutation) SetStatus(s sysjob.Status) {
	m.status = &s
}

// Status returns the value of the "status" field in the mutation.
func (m *SysJobMutation) Status() (r sysjob.Status, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the SysJob entity.
// If the SysJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SysJobMutation) OldStatus(ctx context.Context) (v sysjob.Status, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *SysJobMutation) ResetStatus() {
	m.status = nil
}

// SetRemark sets the "remark" field.
func (m *SysJobMutation) SetRemark(s string) {
	m.remark = &s
}

// Remark returns the value of the "remark" field in the mutation.
func (m *SysJobMutation) Remark() (r string, exists bool) {
	v := m.remark
	if v == nil {
		return
	}
	return *v, true
}

// OldRemark returns the old "remark" field's value of the SysJob entity.
// If the SysJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SysJobMutation) OldRemark(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRemark is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRemark requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRemark: %w", err)
	}
	return oldValue.Remark, nil
}

// ClearRemark clears the value of the "remark" field.
func (m *SysJobMutation) ClearRemark() {
	m.remark = nil
	m.clearedFields[sysjob.FieldRemark] = struct{}{}
}

// RemarkCleared returns if the "remark" field was cleared in this mutation.
func (m *SysJobMutation) RemarkCleared() bool {
	_, ok := m.clearedFields[sysjob.FieldRemark]
	return ok
}

// ResetRemark resets all changes to the "remark" field.
func (m *SysJobMutation) ResetRemark() {
	m.remark = nil
	delete(m.clearedFields, sysjob.FieldRemark)
}

// SetName sets the "name" field.
func (m *SysJobMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *SysJobMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the SysJob entity.
// If the SysJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SysJobMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *SysJobMutation) ResetName() {
	m.name = nil
}

// SetGroup sets the "group" field.
func (m *SysJobMutation) SetGroup(s string) {
	m.group = &s
}

// Group returns the value of the "group" field in the mutation.
func (m *SysJobMutation) Group() (r string, exists bool) {
	v := m.group
	if v == nil {
		return
	}
	return *v, true
}

// OldGroup returns the old "group" field's value of the SysJob entity.
// If the SysJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SysJobMutation) OldGroup(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldGroup is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldGroup requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldGroup: %w", err)
	}
	return oldValue.Group, nil
}

// ResetGroup resets all changes to the "group" field.
func (m *SysJobMutation) ResetGroup() {
	m.group = nil
}

// SetHandler sets the "handler" field.
func (m *SysJobMutation) SetHandler(s string) {
	m.handler = &s
}

// Handler returns the value of the "handler" field in the mutation.
func (m *SysJobMutation) Handler() (r string, exists bool) {
	v := m.handler
	if v == nil {
		return
	}
	return *v, true
}

// OldHandler returns the old "handler" field's value of the SysJob entity.
// If the SysJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SysJobMutation) OldHandler(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldHandler is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldHandler requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldHandler: %w", err)
	}
	return oldValue.Handler, nil
}

// ResetHandler resets all changes to the "handler" field.
func (m *SysJobMutation) ResetHandler() {
	m.handler = nil
}

// SetParams sets the "params" field.
func (m *SysJobMutation) SetParams(s string) {
	m.params = &s
}

// Params returns the value of the "params" field in the mutation.
func (m *SysJobMutation) Params() (r string, exists bool) {
	v := m.params
	if v == nil {
		return
	}
	return *v, true
}

// OldParams returns the old "params" field's value of the SysJob entity.
// If the SysJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SysJobMutation) OldParams(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldParams is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldParams requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldParams: %w", err)
	}
	return oldValue.Params, nil
}

// ResetParams resets all changes to the "params" field.
func (m *SysJobMutation) ResetParams() {
	m.params = nil
}

// SetCronExpression sets the "cron_expression" field.
func (m *SysJobMutation) SetCronExpression(s string) {
	m.cron_expression = &s
}

// CronExpression returns the value of the "cron_expression" field in the mutation.
func (m *SysJobMutation) CronExpression() (r string, exists bool) {
	v := m.cron_expression
	if v == nil {
		return
	}
	return *v, true
}

// OldCronExpression returns the old "cron_expression" field's value of the SysJob entity.
// If the SysJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SysJobMutation) OldCronExpression(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCronExpression is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCronExpression requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCronExpression: %w", err)
	}
	return oldValue.CronExpression, nil
}

// ResetCronExpression resets all changes to the "cron_expression" field.
func (m *SysJobMutation) ResetCronExpression() {
	m.cron_expression = nil
}

// SetTimeZone sets the "time_zone" field.
func (m *SysJobMutation) SetTimeZone(s string) {
	m.time_zone = &s
}

// TimeZone returns the value of the "time_zone" field in the mutation.
func (m *SysJobMutation) TimeZone() (r string, exists bool) {
	v := m.time_zone
	if v == nil {
		return
	}
	return *v, true
}

// OldTimeZone returns the old "time_zone" field's value of the SysJob entity.
// If the SysJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SysJobMutation) OldTimeZone(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTimeZone is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTimeZone requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTimeZone: %w", err)
	}
	return oldValue.TimeZone, nil
}

// ResetTimeZone resets all changes to the "time_zone" field.
func (m *SysJobMutation) ResetTimeZone() {
	m.time_zone = nil
}

// SetMisfirePolicy sets the "misfire_policy" field.
func (m *SysJobMutation) SetMisfirePolicy(sp sysjob.MisfirePolicy) {
	m.misfire_policy = &sp
}

// MisfirePolicy returns the value of the "misfire_policy" field in the mutation.
func (m *SysJobMutation) MisfirePolicy() (r sysjob.MisfirePolicy, exists bool) {
	v := m.misfire_policy
	if v == nil {
		return
	}
	return *v, true
}

// OldMisfirePolicy returns the old "misfire_policy" field's value of the SysJob entity.
// If the SysJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SysJobMutation) OldMisfirePolicy(ctx context.Context) (v sysjob.MisfirePolicy, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMisfirePolicy is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMisfirePolicy requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMisfirePolicy: %w", err)
	}
	return oldValue.MisfirePolicy, nil
}

// ResetMisfirePolicy resets all changes to the "misfire_policy" field.
func (m *SysJobMutation) ResetMisfirePolicy() {
	m.misfire_policy = nil
}

// SetConcurrent sets the "concurrent" field.
func (m *SysJobMutation) SetConcurrent(b bool) {
	m.concurrent = &b
}

// Concurrent returns the value of the "concurrent" field in the mutation.
func (m *SysJobMutation) Concurrent() (r bool, exists bool) {
	v := m.concurrent
	if v == nil {
		return
	}
	return *v, true
}

// OldConcurrent returns the old "concurrent" field's value of the SysJob entity.
// If the SysJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SysJobMutation) OldConcurrent(ctx context.Context) (v bool, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldConcurrent is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldConcurrent requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldConcurrent: %w", err)
	}
	return oldValue.Concurrent, nil
}

// ResetConcurrent resets all changes to the "concurrent" field.
func (m *SysJobMutation) ResetConcurrent() {
	m.concurrent = nil
}

// SetTimeout sets the "timeout" field.
func (m *SysJobMutation) SetTimeout(i int32) {
	m.timeout = &i
	m.addtimeout = nil
}

// Timeout returns the value of the "timeout" field in the mutation.
func (m *SysJobMutation) Timeout() (r int32, exists bool) {
	v := m.timeout
	if v == nil {
		return
	}
	return *v, true
}

// OldTimeout returns the old "timeout" field's value of the SysJob entity.
// If the SysJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SysJobMutation) OldTimeout(ctx context.Context) (v int32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTimeout is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTimeout requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTimeout: %w", err)
	}
	return oldValue.Timeout, nil
}

// AddTimeout adds i to the "timeout" field.
func (m *SysJobMutation) AddTimeout(i int32) {
	if m.addtimeout != nil {
		*m.addtimeout += i
	} else {
		m.addtimeout = &i
	}
}

// AddedTimeout returns the value that was added to the "timeout" field in this mutation.
func (m *SysJobMutation) AddedTimeout() (r int32, exists bool) {
	v := m.addtimeout
	if v == nil {
		return
	}
	return *v, true
}

// ResetTimeout resets all changes to the "timeout" field.
func (m *SysJobMutation) ResetTimeout() {
	m.timeout = nil
	m.addtimeout = nil
}

// SetMaxRetry sets the "max_retry" field.
func (m *SysJobMutation) SetMaxRetry(i int32) {
	m.max_retry = &i
	m.addmax_retry = nil
}

// MaxRetry returns the value of the "max_retry" field in the mutation.
func (m *SysJobMutation) MaxRetry() (r int32, exists bool) {
	v := m.max_retry
	if v == nil {
		return
	}
	return *v, true
}

// OldMaxRetry returns the old "max_retry" field's value of the SysJob entity.
// If the SysJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SysJobMutation) OldMaxRetry(ctx context.Context) (v int32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMaxRetry is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMaxRetry requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMaxRetry: %w", err)
	}
	return oldValue.MaxRetry, nil
}

// AddMaxRetry adds i to the "max_retry" field.
func (m *SysJobMutation) AddMaxRetry(i int32) {
	if m.addmax_retry != nil {
		*m.addmax_retry += i
	} else {
		m.addmax_retry = &i
	}
}

// AddedMaxRetry returns the value that was added to the "max_retry" field in this mutation.
func (m *SysJobMutation) AddedMaxRetry() (r int32, exists bool) {
	v := m.addmax_retry
	if v == nil {
		return
	}
	return *v, true
}

// ResetMaxRetry resets all changes to the "max_retry" field.
func (m *SysJobMutation) ResetMaxRetry() {
	m.max_retry = nil
	m.addmax_retry = nil
}

// SetRetryInterval sets the "retry_interval" field.
func (m *SysJobMutation) SetRetryInterval(i int32) {
	m.retry_interval = &i
	m.addretry_interval = nil
}

// RetryInterval returns the value of the "retry_interval" field in the mutation.
func (m *SysJobMutation) RetryInterval() (r int32, exists bool) {
	v := m.retry_interval
	if v == nil {
		return
	}
	return *v, true
}

// OldRetryInterval returns the old "retry_interval" field's value of the SysJob entity.
// If the SysJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SysJobMutation) OldRetryInterval(ctx context.Context) (v int32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldRetryInterval is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldRetryInterval requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldRetryInterval: %w", err)
	}
	return oldValue.RetryInterval, nil
}

// AddRetryInterval adds i to the "retry_interval" field.
func (m *SysJobMutation) AddRetryInterval(i int32) {
	if m.addretry_interval != nil {
		*m.addretry_interval += i
	} else {
		m.addretry_interval = &i
	}
}

// AddedRetryInterval returns the value that was added to the "retry_interval" field in this mutation.
func (m *SysJobMutation) AddedRetryInterval() (r int32, exists bool) {
	v := m.addretry_interval
	if v == nil {
		return
	}
	return *v, true
}

// ResetRetryInterval resets all changes to the "retry_interval" field.
func (m *SysJobMutation) ResetRetryInterval() {
	m.retry_interval = nil
	m.addretry_interval = nil
}

// SetNextRunAt sets the "next_run_at" field.
func (m *SysJobMutation) SetNextRunAt(t time.Time) {
	m.next_run_at = &t
}

// NextRunAt returns the value of the "next_run_at" field in the mutation.
func (m *SysJobMutation) NextRunAt() (r time.Time, exists bool) {
	v := m.next_run_at
	if v == nil {
		return
	}
	return *v, true
}

// OldNextRunAt returns the old "next_run_at" field's value of the SysJob entity.
// If the SysJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SysJobMutation) OldNextRunAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldNextRunAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldNextRunAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldNextRunAt: %w", err)
	}
	return oldValue.NextRunAt, nil
}

// ClearNextRunAt clears the value of the "next_run_at" field.
func (m *SysJobMutation) ClearNextRunAt() {
	m.next_run_at = nil
	m.clearedFields[sysjob.FieldNextRunAt] = struct{}{}
}

// NextRunAtCleared returns if the "next_run_at" field was cleared in this mutation.
func (m *SysJobMutation) NextRunAtCleared() bool {
	_, ok := m.clearedFields[sysjob.FieldNextRunAt]
	return ok
}

// ResetNextRunAt resets all changes to the "next_run_at" field.
func (m *SysJobMutation) ResetNextRunAt() {
	m.next_run_at = nil
	delete(m.clearedFields, sysjob.FieldNextRunAt)
}

// SetLastRunAt sets the "last_run_at" field.
func (m *SysJobMutation) SetLastRunAt(t time.Time) {
	m.last_run_at = &t
}

// LastRunAt returns the value of the "last_run_at" field in the mutation.
func (m *SysJobMutation) LastRunAt() (r time.Time, exists bool) {
	v := m.last_run_at
	if v == nil {
		return
	}
	return *v, true
}

// OldLastRunAt returns the old "last_run_at" field's value of the SysJob entity.
// If the SysJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SysJobMutation) OldLastRunAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLastRunAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLastRunAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLastRunAt: %w", err)
	}
	return oldValue.LastRunAt, nil
}

// ClearLastRunAt clears the value of the "last_run_at" field.
func (m *SysJobMutation) ClearLastRunAt() {
	m.last_run_at = nil
	m.clearedFields[sysjob.FieldLastRunAt] = struct{}{}
}

// LastRunAtCleared returns if the "last_run_at" field was cleared in this mutation.
func (m *SysJobMutation) LastRunAtCleared() bool {
	_, ok := m.clearedFields[sysjob.FieldLastRunAt]
	return ok
}

// ResetLastRunAt resets all changes to the "last_run_at" field.
func (m *SysJobMutation) ResetLastRunAt() {
	m.last_run_at = nil
	delete(m.clearedFields, sysjob.FieldLastRunAt)
}

// SetLastStatus sets the "last_status" field.
func (m *SysJobMutation) SetLastStatus(s string) {
	m.last_status = &s
}

// LastStatus returns the value of the "last_status" field in the mutation.
func (m *SysJobMutation) LastStatus() (r string, exists bool) {
	v := m.last_status
	if v == nil {
		return
	}
	return *v, true
}

// OldLastStatus returns the old "last_status" field's value of the SysJob entity.
// If the SysJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SysJobMutation) OldLastStatus(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLastStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLastStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLastStatus: %w", err)
	}
	return oldValue.LastStatus, nil
}

// ClearLastStatus clears the value of the "last_status" field.
func (m *SysJobMutation) ClearLastStatus() {
	m.last_status = nil
	m.clearedFields[sysjob.FieldLastStatus] = struct{}{}
}

// LastStatusCleared returns if the "last_status" field was cleared in this mutation.
func (m *SysJobMutation) LastStatusCleared() bool {
	_, ok := m.clearedFields[sysjob.FieldLastStatus]
	return ok
}

// ResetLastStatus resets all changes to the "last_status" field.
func (m *SysJobMutation) ResetLastStatus() {
	m.last_status = nil
	delete(m.clearedFields, sysjob.FieldLastStatus)
}

// SetLastDuration sets the "last_duration" field.
func (m *SysJobMutation) SetLastDuration(i int64) {
	m.last_duration = &i
	m.addlast_duration = nil
}

// LastDuration returns the value of the "last_duration" field in the mutation.
func (m *SysJobMutation) LastDuration() (r int64, exists bool) {
	v := m.last_duration
	if v == nil {
		return
	}
	return *v, true
}

// OldLastDuration returns the old "last_duration" field's value of the SysJob entity.
// If the SysJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SysJobMutation) OldLastDuration(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLastDuration is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLastDuration requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLastDuration: %w", err)
	}
	return oldValue.LastDuration, nil
}

// AddLastDuration adds i to the "last_duration" field.
func (m *SysJobMutation) AddLastDuration(i int64) {
	if m.addlast_duration != nil {
		*m.addlast_duration += i
	} else {
		m.addlast_duration = &i
	}
}

// AddedLastDuration returns the value that was added to the "last_duration" field in this mutation.
func (m *SysJobMutation) AddedLastDuration() (r int64, exists bool) {
	v := m.addlast_duration
	if v == nil {
		return
	}
	return *v, true
}

// ClearLastDuration clears the value of the "last_duration" field.
func (m *SysJobMutation) ClearLastDuration() {
	m.last_duration = nil
	m.addlast_duration = nil
	m.clearedFields[sysjob.FieldLastDuration] = struct{}{}
}

// LastDurationCleared returns if the "last_duration" field was cleared in this mutation.
func (m *SysJobMutation) LastDurationCleared() bool {
	_, ok := m.clearedFields[sysjob.FieldLastDuration]
	return ok
}

// ResetLastDuration resets all changes to the "last_duration" field.
func (m *SysJobMutation) ResetLastDuration() {
	m.last_duration = nil
	m.addlast_duration = nil
	delete(m.clearedFields, sysjob.FieldLastDuration)
}

// SetLastError sets the "last_error" field.
func (m *SysJobMutation) SetLastError(s string) {
	m.last_error = &s
}

// LastError returns the value of the "last_error" field in the mutation.
func (m *SysJobMutation) LastError() (r string, exists bool) {
	v := m.last_error
	if v == nil {
		return
	}
	return *v, true
}

// OldLastError returns the old "last_error" field's value of the SysJob entity.
// If the SysJob object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SysJobMutation) OldLastError(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldLastError is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldLastError requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldLastError: %w", err)
	}
	return oldValue.LastError, nil
}

// ClearLastError clears the value of the "last_error" field.
func (m *SysJobMutation) ClearLastError() {
	m.last_error = nil
	m.clearedFields[sysjob.FieldLastError] = struct{}{}
}

// LastErrorCleared returns if the "last_error" field was cleared in this mutation.
func (m *SysJobMutation) LastErrorCleared() bool {
	_, ok := m.clearedFields[sysjob.FieldLastError]
	return ok
}

// ResetLastError resets all changes to the "last_error" field.
func (m *SysJobMutation) ResetLastError() {
	m.last_error = nil
	delete(m.clearedFields, sysjob.FieldLastError)
}

// Where appends a list predicates to the SysJobMutation builder.
func (m *SysJobMutation) Where(ps ...predicate.SysJob) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the SysJobMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *SysJobMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.SysJob, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *SysJobMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *SysJobMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (SysJob).
func (m *SysJobMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *SysJobMutation) Fields() []string {
	fields := make([]string, 0, 27)
	if m.created_at != nil {
		fields = append(fields, sysjob.FieldCreatedAt)
	}
	if m.created_id != nil {
		fields = append(fields, sysjob.FieldCreatedID)
	}
	if m.created_by != nil {
		fields = append(fields, sysjob.FieldCreatedBy)
	}
	if m.updated_at != nil {
		fields = append(fields, sysjob.FieldUpdatedAt)
	}
	if m.updated_id != nil {
		fields = append(fields, sysjob.FieldUpdatedID)
	}
	if m.updated_by != nil {
		fields = append(fields, sysjob.FieldUpdatedBy)
	}
	if m.deleted_at != nil {
		fields = append(fields, sysjob.FieldDeletedAt)
	}
	if m.deleted_id != nil {
		fields = append(fields, sysjob.FieldDeletedID)
	}
	if m.deleted_by != nil {
		fields = append(fields, sysjob.FieldDeletedBy)
	}
	if m.status != nil {
		fields = append(fields, sysjob.FieldStatus)
	}
	if m.remark != nil {
		fields = append(fields, sysjob.FieldRemark)
	}
	if m.name != nil {
		fields = append(fields, sysjob.FieldName)
	}
	if m.group != nil {
		fields = append(fields, sysjob.FieldGroup)
	}
	if m.handler != nil {
		fields = append(fields, sysjob.FieldHandler)
	}
	if m.params != nil {
		fields = append(fields, sysjob.FieldParams)
	}
	if m.cron_expression != nil {
		fields = append(fields, sysjob.FieldCronExpression)
	}
	if m.time_zone != nil {
		fields = append(fields, sysjob.FieldTimeZone)
	}
	if m.misfire_policy != nil {
		fields = append(fields, sysjob.FieldMisfirePolicy)
	}
	if m.concurrent != nil {
		fields = append(fields, sysjob.FieldConcurrent)
	}
	if m.timeout != nil {
		fields = append(fields, sysjob.FieldTimeout)
	}
	if m.max_retry != nil {
		fields = append(fields, sysjob.FieldMaxRetry)
	}
	if m.retry_interval != nil {
		fields = append(fields, sysjob.FieldRetryInterval)
	}
	if m.next_run_at != nil {
		fields = append(fields, sysjob.FieldNextRunAt)
	}
	if m.last_run_at != nil {
		fields = append(fields, sysjob.FieldLastRunAt)
	}
	if m.last_status != nil {
		fields = append(fields, sysjob.FieldLastStatus)
	}
	if m.last_duration != nil {
		fields = append(fields, sysjob.FieldLastDuration)
	}
	if m.last_error != nil {
		fields = append(fields, sysjob.FieldLastError)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *SysJobMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case sysjob.FieldCreatedAt:
		return m.CreatedAt()
	case sysjob.FieldCreatedID:
		return m.CreatedID()
	case sysjob.FieldCreatedBy:
		return m.CreatedBy()
	case sysjob.FieldUpdatedAt:
		return m.UpdatedAt()
	case sysjob.FieldUpdatedID:
		return m.UpdatedID()
	case sysjob.FieldUpdatedBy:
		return m.UpdatedBy()
	case sysjob.FieldDeletedAt:
		return m.DeletedAt()
	case sysjob.FieldDeletedID:
		return m.DeletedID()
	case sysjob.FieldDeletedBy:
		return m.DeletedBy()
	case sysjob.FieldStatus:
		return m.Status()
	case sysjob.FieldRemark:
		return m.Remark()
	case sysjob.FieldName:
		return m.Name()
	case sysjob.FieldGroup:
		return m.Group()
	case sysjob.FieldHandler:
		return m.Handler()
	case sysjob.FieldParams:
		return m.Params()
	case sysjob.FieldCronExpression:
		return m.CronExpression()
	case sysjob.FieldTimeZone:
		return m.TimeZone()
	case sysjob.FieldMisfirePolicy:
		return m.MisfirePolicy()
	case sysjob.FieldConcurrent:
		return m.Concurrent()
	case sysjob.FieldTimeout:
		return m.Timeout()
	case sysjob.FieldMaxRetry:
		return m.MaxRetry()
	case sysjob.FieldRetryInterval:
		return m.RetryInterval()
	case sysjob.FieldNextRunAt:
		return m.NextRunAt()
	case sysjob.FieldLastRunAt:
		return m.LastRunAt()
	case sysjob.FieldLastStatus:
		return m.LastStatus()
	case sysjob.FieldLastDuration:
		return m.LastDuration()
	case sysjob.FieldLastError:
		return m.LastError()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *SysJobMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case sysjob.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case sysjob.FieldCreatedID:
		return m.OldCreatedID(ctx)
	case sysjob.FieldCreatedBy:
		return m.OldCreatedBy(ctx)
	case sysjob.FieldUpdatedAt:
		return m.OldUpdatedAt(ctx)
	case sysjob.FieldUpdatedID:
		return m.OldUpdatedID(ctx)
	case sysjob.FieldUpdatedBy:
		return m.OldUpdatedBy(ctx)
	case sysjob.FieldDeletedAt:
		return m.OldDeletedAt(ctx)
	case sysjob.FieldDeletedID:
		return m.OldDeletedID(ctx)
	case sysjob.FieldDeletedBy:
		return m.OldDeletedBy(ctx)
	case sysjob.FieldStatus:
		return m.OldStatus(ctx)
	case sysjob.FieldRemark:
		return m.OldRemark(ctx)
	case sysjob.FieldName:
		return m.OldName(ctx)
	case sysjob.FieldGroup:
		return m.OldGroup(ctx)
	case sysjob.FieldHandler:
		return m.OldHandler(ctx)
	case sysjob.FieldParams:
		return m.OldParams(ctx)
	case sysjob.FieldCronExpression:
		return m.OldCronExpression(ctx)
	case sysjob.FieldTimeZone:
		return m.OldTimeZone(ctx)
	case sysjob.FieldMisfirePolicy:
		return m.OldMisfirePolicy(ctx)
	case sysjob.FieldConcurrent:
		return m.OldConcurrent(ctx)
	case sysjob.FieldTimeout:
		return m.OldTimeout(ctx)
	case sysjob.FieldMaxRetry:
		return m.OldMaxRetry(ctx)
	case sysjob.FieldRetryInterval:
		return m.OldRetryInterval(ctx)
	case sysjob.FieldNextRunAt:
		return m.OldNextRunAt(ctx)
	case sysjob.FieldLastRunAt:
		return m.OldLastRunAt(ctx)
	case sysjob.FieldLastStatus:
		return m.OldLastStatus(ctx)
	case sysjob.FieldLastDuration:
		return m.OldLastDuration(ctx)
	case sysjob.FieldLastError:
		return m.OldLastError(ctx)
	}
	return nil, fmt.Errorf("unknown SysJob field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SysJobMutation) SetField(name string, value ent.Value) error {
	switch name {
	case sysjob.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case sysjob.FieldCreatedID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedID(v)
		return nil
	case sysjob.FieldCreatedBy:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedBy(v)
		return nil
	case sysjob.FieldUpdatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedAt(v)
		return nil
	case sysjob.FieldUpdatedID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedID(v)
		return nil
	case sysjob.FieldUpdatedBy:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUpdatedBy(v)
		return nil
	case sysjob.FieldDeletedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDeletedAt(v)
		return nil
	case sysjob.FieldDeletedID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDeletedID(v)
		return nil
	case sysjob.FieldDeletedBy:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDeletedBy(v)
		return nil
	case sysjob.FieldStatus:
		v, ok := value.(sysjob.Status)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case sysjob.FieldRemark:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRemark(v)
		return nil
	case sysjob.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	case sysjob.FieldGroup:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetGroup(v)
		return nil
	case sysjob.FieldHandler:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetHandler(v)
		return nil
	case sysjob.FieldParams:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetParams(v)
		return nil
	case sysjob.FieldCronExpression:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCronExpression(v)
		return nil
	case sysjob.FieldTimeZone:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTimeZone(v)
		return nil
	case sysjob.FieldMisfirePolicy:
		v, ok := value.(sysjob.MisfirePolicy)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMisfirePolicy(v)
		return nil
	case sysjob.FieldConcurrent:
		v, ok := value.(bool)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetConcurrent(v)
		return nil
	case sysjob.FieldTimeout:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTimeout(v)
		return nil
	case sysjob.FieldMaxRetry:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMaxRetry(v)
		return nil
	case sysjob.FieldRetryInterval:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetRetryInterval(v)
		return nil
	case sysjob.FieldNextRunAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetNextRunAt(v)
		return nil
	case sysjob.FieldLastRunAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLastRunAt(v)
		return nil
	case sysjob.FieldLastStatus:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLastStatus(v)
		return nil
	case sysjob.FieldLastDuration:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLastDuration(v)
		return nil
	case sysjob.FieldLastError:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetLastError(v)
		return nil
	}
	return fmt.Errorf("unknown SysJob field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *SysJobMutation) AddedFields() []string {
	var fields []string
	if m.addcreated_id != nil {
		fields = append(fields, sysjob.FieldCreatedID)
	}
	if m.addupdated_id != nil {
		fields = append(fields, sysjob.FieldUpdatedID)
	}
	if m.adddeleted_id != nil {
		fields = append(fields, sysjob.FieldDeletedID)
	}
	if m.addtimeout != nil {
		fields = append(fields, sysjob.FieldTimeout)
	}
	if m.addmax_retry != nil {
		fields = append(fields, sysjob.FieldMaxRetry)
	}
	if m.addretry_interval != nil {
		fields = append(fields, sysjob.FieldRetryInterval)
	}
	if m.addlast_duration != nil {
		fields = append(fields, sysjob.FieldLastDuration)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *SysJobMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case sysjob.FieldCreatedID:
		return m.AddedCreatedID()
	case sysjob.FieldUpdatedID:
		return m.AddedUpdatedID()
	case sysjob.FieldDeletedID:
		return m.AddedDeletedID()
	case sysjob.FieldTimeout:
		return m.AddedTimeout()
	case sysjob.FieldMaxRetry:
		return m.AddedMaxRetry()
	case sysjob.FieldRetryInterval:
		return m.AddedRetryInterval()
	case sysjob.FieldLastDuration:
		return m.AddedLastDuration()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SysJobMutation) AddField(name string, value ent.Value) error {
	switch name {
	case sysjob.FieldCreatedID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddCreatedID(v)
		return nil
	case sysjob.FieldUpdatedID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddUpdatedID(v)
		return nil
	case sysjob.FieldDeletedID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddDeletedID(v)
		return nil
	case sysjob.FieldTimeout:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddTimeout(v)
		return nil
	case sysjob.FieldMaxRetry:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddMaxRetry(v)
		return nil
	case sysjob.FieldRetryInterval:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddRetryInterval(v)
		return nil
	case sysjob.FieldLastDuration:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddLastDuration(v)
		return nil
	}
	return fmt.Errorf("unknown SysJob numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *SysJobMutation) ClearedFields() []string {
	var fields []string
	if m.FieldCleared(sysjob.FieldDeletedAt) {
		fields = append(fields, sysjob.FieldDeletedAt)
	}
	if m.FieldCleared(sysjob.FieldDeletedID) {
		fields = append(fields, sysjob.FieldDeletedID)
	}
	if m.FieldCleared(sysjob.FieldDeletedBy) {
		fields = append(fields, sysjob.FieldDeletedBy)
	}
	if m.FieldCleared(sysjob.FieldRemark) {
		fields = append(fields, sysjob.FieldRemark)
	}
	if m.FieldCleared(sysjob.FieldNextRunAt) {
		fields = append(fields, sysjob.FieldNextRunAt)
	}
	if m.FieldCleared(sysjob.FieldLastRunAt) {
		fields = append(fields, sysjob.FieldLastRunAt)
	}
	if m.FieldCleared(sysjob.FieldLastStatus) {
		fields = append(fields, sysjob.FieldLastStatus)
	}
	if m.FieldCleared(sysjob.FieldLastDuration) {
		fields = append(fields, sysjob.FieldLastDuration)
	}
	if m.FieldCleared(sysjob.FieldLastError) {
		fields = append(fields, sysjob.FieldLastError)
	}
	return fields
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *SysJobMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *SysJobMutation) ClearField(name string) error {
	switch name {
	case sysjob.FieldDeletedAt:
		m.ClearDeletedAt()
		return nil
	case sysjob.FieldDeletedID:
		m.ClearDeletedID()
		return nil
	case sysjob.FieldDeletedBy:
		m.ClearDeletedBy()
		return nil
	case sysjob.FieldRemark:
		m.ClearRemark()
		return nil
	case sysjob.FieldNextRunAt:
		m.ClearNextRunAt()
		return nil
	case sysjob.FieldLastRunAt:
		m.ClearLastRunAt()
		return nil
	case sysjob.FieldLastStatus:
		m.ClearLastStatus()
		return nil
	case sysjob.FieldLastDuration:
		m.ClearLastDuration()
		return nil
	case sysjob.FieldLastError:
		m.ClearLastError()
		return nil
	}
	return fmt.Errorf("unknown SysJob nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *SysJobMutation) ResetField(name string) error {
	switch name {
	case sysjob.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case sysjob.FieldCreatedID:
		m.ResetCreatedID()
		return nil
	case sysjob.FieldCreatedBy:
		m.ResetCreatedBy()
		return nil
	case sysjob.FieldUpdatedAt:
		m.ResetUpdatedAt()
		return nil
	case sysjob.FieldUpdatedID:
		m.ResetUpdatedID()
		return nil
	case sysjob.FieldUpdatedBy:
		m.ResetUpdatedBy()
		return nil
	case sysjob.FieldDeletedAt:
		m.ResetDeletedAt()
		return nil
	case sysjob.FieldDeletedID:
		m.ResetDeletedID()
		return nil
	case sysjob.FieldDeletedBy:
		m.ResetDeletedBy()
		return nil
	case sysjob.FieldStatus:
		m.ResetStatus()
		return nil
	case sysjob.FieldRemark:
		m.ResetRemark()
		return nil
	case sysjob.FieldName:
		m.ResetName()
		return nil
	case sysjob.FieldGroup:
		m.ResetGroup()
		return nil
	case sysjob.FieldHandler:
		m.ResetHandler()
		return nil
	case sysjob.FieldParams:
		m.ResetParams()
		return nil
	case sysjob.FieldCronExpression:
		m.ResetCronExpression()
		return nil
	case sysjob.FieldTimeZone:
		m.ResetTimeZone()
		return nil
	case sysjob.FieldMisfirePolicy:
		m.ResetMisfirePolicy()
		return nil
	case sysjob.FieldConcurrent:
		m.ResetConcurrent()
		return nil
	case sysjob.FieldTimeout:
		m.ResetTimeout()
		return nil
	case sysjob.FieldMaxRetry:
		m.ResetMaxRetry()
		return nil
	case sysjob.FieldRetryInterval:
		m.ResetRetryInterval()
		return nil
	case sysjob.FieldNextRunAt:
		m.ResetNextRunAt()
		return nil
	case sysjob.FieldLastRunAt:
		m.ResetLastRunAt()
		return nil
	case sysjob.FieldLastStatus:
		m.ResetLastStatus()
		return nil
	case sysjob.FieldLastDuration:
		m.ResetLastDuration()
		return nil
	case sysjob.FieldLastError:
		m.ResetLastError()
		return nil
	}
	return fmt.Errorf("unknown SysJob field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *SysJobMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *SysJobMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *SysJobMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *SysJobMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *SysJobMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *SysJobMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *SysJobMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown SysJob unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *SysJobMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown SysJob edge %s", name)
}

// SysJobLogMutation represents an operation that mutates the SysJobLog nodes in the graph.
type SysJobLogMutation struct {
	config
	op             Op
	typ            string
	id             *int64
	created_at     *time.Time
	created_id     *int64
	addcreated_id  *int64
	created_by     *string
	job_id         *int64
	addjob_id      *int64
	job_name       *string
	job_group      *string
	handler        *string
	trigger_type   *sysjoblog.TriggerType
	exec_node      *string
	status         *sysjoblog.Status
	attempt        *int32
	addattempt     *int32
	message        *string
	exception_info *string
	duration       *int64
	addduration    *int64
	clearedFields  map[string]struct{}
	done           bool
	oldValue       func(context.Context) (*SysJobLog, error)
	predicates     []predicate.SysJobLog
}

var _ ent.Mutation = (*SysJobLogMutation)(nil)

// sysjoblogOption allows management of the mutation configuration using functional options.
type sysjoblogOption func(*SysJobLogMutation)

// newSysJobLogMutation creates new mutation for the SysJobLog entity.
func newSysJobLogMutation(c config, op Op, opts ...sysjoblogOption) *SysJobLogMutation {
	m := &SysJobLogMutation{
		config:        c,
		op:            op,
		typ:           TypeSysJobLog,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withSysJobLogID sets the ID field of the mutation.
func withSysJobLogID(id int64) sysjoblogOption {
	return func(m *SysJobLogMutation) {
		var (
			err   error
			once  sync.Once
			value *SysJobLog
		)
		m.oldValue = func(ctx context.Context) (*SysJobLog, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().SysJobLog.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withSysJobLog sets the old SysJobLog of the mutation.
func withSysJobLog(node *SysJobLog) sysjoblogOption {
	return func(m *SysJobLogMutation) {
		m.oldValue = func(context.Context) (*SysJobLog, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m SysJobLogMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m SysJobLogMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// SetID sets the value of the id field. Note that this
// operation is only accepted on creation of SysJobLog entities.
func (m *SysJobLogMutation) SetID(id int64) {
	m.id = &id
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *SysJobLogMutation) ID() (id int64, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *SysJobLogMutation) IDs(ctx context.Context) ([]int64, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int64{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().SysJobLog.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetCreatedAt sets the "created_at" field.
func (m *SysJobLogMutation) SetCreatedAt(t time.Time) {
	m.created_at = &t
}

// CreatedAt returns the value of the "created_at" field in the mutation.
func (m *SysJobLogMutation) CreatedAt() (r time.Time, exists bool) {
	v := m.created_at
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedAt returns the old "created_at" field's value of the SysJobLog entity.
// If the SysJobLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SysJobLogMutation) OldCreatedAt(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedAt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedAt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedAt: %w", err)
	}
	return oldValue.CreatedAt, nil
}

// ResetCreatedAt resets all changes to the "created_at" field.
func (m *SysJobLogMutation) ResetCreatedAt() {
	m.created_at = nil
}

// SetCreatedID sets the "created_id" field.
func (m *SysJobLogMutation) SetCreatedID(i int64) {
	m.created_id = &i
	m.addcreated_id = nil
}

// CreatedID returns the value of the "created_id" field in the mutation.
func (m *SysJobLogMutation) CreatedID() (r int64, exists bool) {
	v := m.created_id
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedID returns the old "created_id" field's value of the SysJobLog entity.
// If the SysJobLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SysJobLogMutation) OldCreatedID(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedID: %w", err)
	}
	return oldValue.CreatedID, nil
}

// AddCreatedID adds i to the "created_id" field.
func (m *SysJobLogMutation) AddCreatedID(i int64) {
	if m.addcreated_id != nil {
		*m.addcreated_id += i
	} else {
		m.addcreated_id = &i
	}
}

// AddedCreatedID returns the value that was added to the "created_id" field in this mutation.
func (m *SysJobLogMutation) AddedCreatedID() (r int64, exists bool) {
	v := m.addcreated_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetCreatedID resets all changes to the "created_id" field.
func (m *SysJobLogMutation) ResetCreatedID() {
	m.created_id = nil
	m.addcreated_id = nil
}

// SetCreatedBy sets the "created_by" field.
func (m *SysJobLogMutation) SetCreatedBy(s string) {
	m.created_by = &s
}

// CreatedBy returns the value of the "created_by" field in the mutation.
func (m *SysJobLogMutation) CreatedBy() (r string, exists bool) {
	v := m.created_by
	if v == nil {
		return
	}
	return *v, true
}

// OldCreatedBy returns the old "created_by" field's value of the SysJobLog entity.
// If the SysJobLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SysJobLogMutation) OldCreatedBy(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldCreatedBy is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldCreatedBy requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldCreatedBy: %w", err)
	}
	return oldValue.CreatedBy, nil
}

// ResetCreatedBy resets all changes to the "created_by" field.
func (m *SysJobLogMutation) ResetCreatedBy() {
	m.created_by = nil
}

// SetJobID sets the "job_id" field.
func (m *SysJobLogMutation) SetJobID(i int64) {
	m.job_id = &i
	m.addjob_id = nil
}

// JobID returns the value of the "job_id" field in the mutation.
func (m *SysJobLogMutation) JobID() (r int64, exists bool) {
	v := m.job_id
	if v == nil {
		return
	}
	return *v, true
}

// OldJobID returns the old "job_id" field's value of the SysJobLog entity.
// If the SysJobLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SysJobLogMutation) OldJobID(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldJobID is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldJobID requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldJobID: %w", err)
	}
	return oldValue.JobID, nil
}

// AddJobID adds i to the "job_id" field.
func (m *SysJobLogMutation) AddJobID(i int64) {
	if m.addjob_id != nil {
		*m.addjob_id += i
	} else {
		m.addjob_id = &i
	}
}

// AddedJobID returns the value that was added to the "job_id" field in this mutation.
func (m *SysJobLogMutation) AddedJobID() (r int64, exists bool) {
	v := m.addjob_id
	if v == nil {
		return
	}
	return *v, true
}

// ResetJobID resets all changes to the "job_id" field.
func (m *SysJobLogMutation) ResetJobID() {
	m.job_id = nil
	m.addjob_id = nil
}

// SetJobName sets the "job_name" field.
func (m *SysJobLogMutation) SetJobName(s string) {
	m.job_name = &s
}

// JobName returns the value of the "job_name" field in the mutation.
func (m *SysJobLogMutation) JobName() (r string, exists bool) {
	v := m.job_name
	if v == nil {
		return
	}
	return *v, true
}

// OldJobName returns the old "job_name" field's value of the SysJobLog entity.
// If the SysJobLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SysJobLogMutation) OldJobName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldJobName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldJobName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldJobName: %w", err)
	}
	return oldValue.JobName, nil
}

// ResetJobName resets all changes to the "job_name" field.
func (m *SysJobLogMutation) ResetJobName() {
	m.job_name = nil
}

// SetJobGroup sets the "job_group" field.
func (m *SysJobLogMutation) SetJobGroup(s string) {
	m.job_group = &s
}

// JobGroup returns the value of the "job_group" field in the mutation.
func (m *SysJobLogMutation) JobGroup() (r string, exists bool) {
	v := m.job_group
	if v == nil {
		return
	}
	return *v, true
}

// OldJobGroup returns the old "job_group" field's value of the SysJobLog entity.
// If the SysJobLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SysJobLogMutation) OldJobGroup(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldJobGroup is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldJobGroup requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldJobGroup: %w", err)
	}
	return oldValue.JobGroup, nil
}

// ResetJobGroup resets all changes to the "job_group" field.
func (m *SysJobLogMutation) ResetJobGroup() {
	m.job_group = nil
}

// SetHandler sets the "handler" field.
func (m *SysJobLogMutation) SetHandler(s string) {
	m.handler = &s
}

// Handler returns the value of the "handler" field in the mutation.
func (m *SysJobLogMutation) Handler() (r string, exists bool) {
	v := m.handler
	if v == nil {
		return
	}
	return *v, true
}

// OldHandler returns the old "handler" field's value of the SysJobLog entity.
// If the SysJobLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SysJobLogMutation) OldHandler(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldHandler is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldHandler requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldHandler: %w", err)
	}
	return oldValue.Handler, nil
}

// ResetHandler resets all changes to the "handler" field.
func (m *SysJobLogMutation) ResetHandler() {
	m.handler = nil
}

// SetTriggerType sets the "trigger_type" field.
func (m *SysJobLogMutation) SetTriggerType(st sysjoblog.TriggerType) {
	m.trigger_type = &st
}

// TriggerType returns the value of the "trigger_type" field in the mutation.
func (m *SysJobLogMutation) TriggerType() (r sysjoblog.TriggerType, exists bool) {
	v := m.trigger_type
	if v == nil {
		return
	}
	return *v, true
}

// OldTriggerType returns the old "trigger_type" field's value of the SysJobLog entity.
// If the SysJobLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SysJobLogMutation) OldTriggerType(ctx context.Context) (v sysjoblog.TriggerType, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTriggerType is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTriggerType requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTriggerType: %w", err)
	}
	return oldValue.TriggerType, nil
}

// ResetTriggerType resets all changes to the "trigger_type" field.
func (m *SysJobLogMutation) ResetTriggerType() {
	m.trigger_type = nil
}

// SetExecNode sets the "exec_node" field.
func (m *SysJobLogMutation) SetExecNode(s string) {
	m.exec_node = &s
}

// ExecNode returns the value of the "exec_node" field in the mutation.
func (m *SysJobLogMutation) ExecNode() (r string, exists bool) {
	v := m.exec_node
	if v == nil {
		return
	}
	return *v, true
}

// OldExecNode returns the old "exec_node" field's value of the SysJobLog entity.
// If the SysJobLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SysJobLogMutation) OldExecNode(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldExecNode is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldExecNode requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldExecNode: %w", err)
	}
	return oldValue.ExecNode, nil
}

// ResetExecNode resets all changes to the "exec_node" field.
func (m *SysJobLogMutation) ResetExecNode() {
	m.exec_node = nil
}

// SetStatus sets the "status" field.
func (m *SysJobLogMutation) SetStatus(s sysjoblog.Status) {
	m.status = &s
}

// Status returns the value of the "status" field in the mutation.
func (m *SysJobLogMutation) Status() (r sysjoblog.Status, exists bool) {
	v := m.status
	if v == nil {
		return
	}
	return *v, true
}

// OldStatus returns the old "status" field's value of the SysJobLog entity.
// If the SysJobLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SysJobLogMutation) OldStatus(ctx context.Context) (v sysjoblog.Status, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldStatus is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldStatus requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldStatus: %w", err)
	}
	return oldValue.Status, nil
}

// ResetStatus resets all changes to the "status" field.
func (m *SysJobLogMutation) ResetStatus() {
	m.status = nil
}

// SetAttempt sets the "attempt" field.
func (m *SysJobLogMutation) SetAttempt(i int32) {
	m.attempt = &i
	m.addattempt = nil
}

// Attempt returns the value of the "attempt" field in the mutation.
func (m *SysJobLogMutation) Attempt() (r int32, exists bool) {
	v := m.attempt
	if v == nil {
		return
	}
	return *v, true
}

// OldAttempt returns the old "attempt" field's value of the SysJobLog entity.
// If the SysJobLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SysJobLogMutation) OldAttempt(ctx context.Context) (v int32, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldAttempt is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldAttempt requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldAttempt: %w", err)
	}
	return oldValue.Attempt, nil
}

// AddAttempt adds i to the "attempt" field.
func (m *SysJobLogMutation) AddAttempt(i int32) {
	if m.addattempt != nil {
		*m.addattempt += i
	} else {
		m.addattempt = &i
	}
}

// AddedAttempt returns the value that was added to the "attempt" field in this mutation.
func (m *SysJobLogMutation) AddedAttempt() (r int32, exists bool) {
	v := m.addattempt
	if v == nil {
		return
	}
	return *v, true
}

// ResetAttempt resets all changes to the "attempt" field.
func (m *SysJobLogMutation) ResetAttempt() {
	m.attempt = nil
	m.addattempt = nil
}

// SetMessage sets the "message" field.
func (m *SysJobLogMutation) SetMessage(s string) {
	m.message = &s
}

// Message returns the value of the "message" field in the mutation.
func (m *SysJobLogMutation) Message() (r string, exists bool) {
	v := m.message
	if v == nil {
		return
	}
	return *v, true
}

// OldMessage returns the old "message" field's value of the SysJobLog entity.
// If the SysJobLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SysJobLogMutation) OldMessage(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldMessage is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldMessage requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldMessage: %w", err)
	}
	return oldValue.Message, nil
}

// ResetMessage resets all changes to the "message" field.
func (m *SysJobLogMutation) ResetMessage() {
	m.message = nil
}

// SetExceptionInfo sets the "exception_info" field.
func (m *SysJobLogMutation) SetExceptionInfo(s string) {
	m.exception_info = &s
}

// ExceptionInfo returns the value of the "exception_info" field in the mutation.
func (m *SysJobLogMutation) ExceptionInfo() (r string, exists bool) {
	v := m.exception_info
	if v == nil {
		return
	}
	return *v, true
}

// OldExceptionInfo returns the old "exception_info" field's value of the SysJobLog entity.
// If the SysJobLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SysJobLogMutation) OldExceptionInfo(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldExceptionInfo is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldExceptionInfo requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldExceptionInfo: %w", err)
	}
	return oldValue.ExceptionInfo, nil
}

// ResetExceptionInfo resets all changes to the "exception_info" field.
func (m *SysJobLogMutation) ResetExceptionInfo() {
	m.exception_info = nil
}

// SetDuration sets the "duration" field.
func (m *SysJobLogMutation) SetDuration(i int64) {
	m.duration = &i
	m.addduration = nil
}

// Duration returns the value of the "duration" field in the mutation.
func (m *SysJobLogMutation) Duration() (r int64, exists bool) {
	v := m.duration
	if v == nil {
		return
	}
	return *v, true
}

// OldDuration returns the old "duration" field's value of the SysJobLog entity.
// If the SysJobLog object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *SysJobLogMutation) OldDuration(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldDuration is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldDuration requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldDuration: %w", err)
	}
	return oldValue.Duration, nil
}

// AddDuration adds i to the "duration" field.
func (m *SysJobLogMutation) AddDuration(i int64) {
	if m.addduration != nil {
		*m.addduration += i
	} else {
		m.addduration = &i
	}
}

// AddedDuration returns the value that was added to the "duration" field in this mutation.
func (m *SysJobLogMutation) AddedDuration() (r int64, exists bool) {
	v := m.addduration
	if v == nil {
		return
	}
	return *v, true
}

// ResetDuration resets all changes to the "duration" field.
func (m *SysJobLogMutation) ResetDuration() {
	m.duration = nil
	m.addduration = nil
}

// Where appends a list predicates to the SysJobLogMutation builder.
func (m *SysJobLogMutation) Where(ps ...predicate.SysJobLog) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the SysJobLogMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *SysJobLogMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.SysJobLog, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *SysJobLogMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *SysJobLogMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (SysJobLog).
func (m *SysJobLogMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *SysJobLogMutation) Fields() []string {
	fields := make([]string, 0, 14)
	if m.created_at != nil {
		fields = append(fields, sysjoblog.FieldCreatedAt)
	}
	if m.created_id != nil {
		fields = append(fields, sysjoblog.FieldCreatedID)
	}
	if m.created_by != nil {
		fields = append(fields, sysjoblog.FieldCreatedBy)
	}
	if m.job_id != nil {
		fields = append(fields, sysjoblog.FieldJobID)
	}
	if m.job_name != nil {
		fields = append(fields, sysjoblog.FieldJobName)
	}
	if m.job_group != nil {
		fields = append(fields, sysjoblog.FieldJobGroup)
	}
	if m.handler != nil {
		fields = append(fields, sysjoblog.FieldHandler)
	}
	if m.trigger_type != nil {
		fields = append(fields, sysjoblog.FieldTriggerType)
	}
	if m.exec_node != nil {
		fields = append(fields, sysjoblog.FieldExecNode)
	}
	if m.status != nil {
		fields = append(fields, sysjoblog.FieldStatus)
	}
	if m.attempt != nil {
		fields = append(fields, sysjoblog.FieldAttempt)
	}
	if m.message != nil {
		fields = append(fields, sysjoblog.FieldMessage)
	}
	if m.exception_info != nil {
		fields = append(fields, sysjoblog.FieldExceptionInfo)
	}
	if m.duration != nil {
		fields = append(fields, sysjoblog.FieldDuration)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *SysJobLogMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case sysjoblog.FieldCreatedAt:
		return m.CreatedAt()
	case sysjoblog.FieldCreatedID:
		return m.CreatedID()
	case sysjoblog.FieldCreatedBy:
		return m.CreatedBy()
	case sysjoblog.FieldJobID:
		return m.JobID()
	case sysjoblog.FieldJobName:
		return m.JobName()
	case sysjoblog.FieldJobGroup:
		return m.JobGroup()
	case sysjoblog.FieldHandler:
		return m.Handler()
	case sysjoblog.FieldTriggerType:
		return m.TriggerType()
	case sysjoblog.FieldExecNode:
		return m.ExecNode()
	case sysjoblog.FieldStatus:
		return m.Status()
	case sysjoblog.FieldAttempt:
		return m.Attempt()
	case sysjoblog.FieldMessage:
		return m.Message()
	case sysjoblog.FieldExceptionInfo:
		return m.ExceptionInfo()
	case sysjoblog.FieldDuration:
		return m.Duration()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *SysJobLogMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case sysjoblog.FieldCreatedAt:
		return m.OldCreatedAt(ctx)
	case sysjoblog.FieldCreatedID:
		return m.OldCreatedID(ctx)
	case sysjoblog.FieldCreatedBy:
		return m.OldCreatedBy(ctx)
	case sysjoblog.FieldJobID:
		return m.OldJobID(ctx)
	case sysjoblog.FieldJobName:
		return m.OldJobName(ctx)
	case sysjoblog.FieldJobGroup:
		return m.OldJobGroup(ctx)
	case sysjoblog.FieldHandler:
		return m.OldHandler(ctx)
	case sysjoblog.FieldTriggerType:
		return m.OldTriggerType(ctx)
	case sysjoblog.FieldExecNode:
		return m.OldExecNode(ctx)
	case sysjoblog.FieldStatus:
		return m.OldStatus(ctx)
	case sysjoblog.FieldAttempt:
		return m.OldAttempt(ctx)
	case sysjoblog.FieldMessage:
		return m.OldMessage(ctx)
	case sysjoblog.FieldExceptionInfo:
		return m.OldExceptionInfo(ctx)
	case sysjoblog.FieldDuration:
		return m.OldDuration(ctx)
	}
	return nil, fmt.Errorf("unknown SysJobLog field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SysJobLogMutation) SetField(name string, value ent.Value) error {
	switch name {
	case sysjoblog.FieldCreatedAt:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedAt(v)
		return nil
	case sysjoblog.FieldCreatedID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedID(v)
		return nil
	case sysjoblog.FieldCreatedBy:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetCreatedBy(v)
		return nil
	case sysjoblog.FieldJobID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetJobID(v)
		return nil
	case sysjoblog.FieldJobName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetJobName(v)
		return nil
	case sysjoblog.FieldJobGroup:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetJobGroup(v)
		return nil
	case sysjoblog.FieldHandler:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetHandler(v)
		return nil
	case sysjoblog.FieldTriggerType:
		v, ok := value.(sysjoblog.TriggerType)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTriggerType(v)
		return nil
	case sysjoblog.FieldExecNode:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetExecNode(v)
		return nil
	case sysjoblog.FieldStatus:
		v, ok := value.(sysjoblog.Status)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetStatus(v)
		return nil
	case sysjoblog.FieldAttempt:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetAttempt(v)
		return nil
	case sysjoblog.FieldMessage:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetMessage(v)
		return nil
	case sysjoblog.FieldExceptionInfo:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetExceptionInfo(v)
		return nil
	case sysjoblog.FieldDuration:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetDuration(v)
		return nil
	}
	return fmt.Errorf("unknown SysJobLog field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *SysJobLogMutation) AddedFields() []string {
	var fields []string
	if m.addcreated_id != nil {
		fields = append(fields, sysjoblog.FieldCreatedID)
	}
	if m.addjob_id != nil {
		fields = append(fields, sysjoblog.FieldJobID)
	}
	if m.addattempt != nil {
		fields = append(fields, sysjoblog.FieldAttempt)
	}
	if m.addduration != nil {
		fields = append(fields, sysjoblog.FieldDuration)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *SysJobLogMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case sysjoblog.FieldCreatedID:
		return m.AddedCreatedID()
	case sysjoblog.FieldJobID:
		return m.AddedJobID()
	case sysjoblog.FieldAttempt:
		return m.AddedAttempt()
	case sysjoblog.FieldDuration:
		return m.AddedDuration()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *SysJobLogMutation) AddField(name string, value ent.Value) error {
	switch name {
	case sysjoblog.FieldCreatedID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddCreatedID(v)
		return nil
	case sysjoblog.FieldJobID:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddJobID(v)
		return nil
	case sysjoblog.FieldAttempt:
		v, ok := value.(int32)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddAttempt(v)
		return nil
	case sysjoblog.FieldDuration:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddDuration(v)
		return nil
	}
	return fmt.Errorf("unknown SysJobLog numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *SysJobLogMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *SysJobLogMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *SysJobLogMutation) ClearField(name string) error {
	return fmt.Errorf("unknown SysJobLog nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *SysJobLogMutation) ResetField(name string) error {
	switch name {
	case sysjoblog.FieldCreatedAt:
		m.ResetCreatedAt()
		return nil
	case sysjoblog.FieldCreatedID:
		m.ResetCreatedID()
		return nil
	case sysjoblog.FieldCreatedBy:
		m.ResetCreatedBy()
		return nil
	case sysjoblog.FieldJobID:
		m.ResetJobID()
		return nil
	case sysjoblog.FieldJobName:
		m.ResetJobName()
		return nil
	case sysjoblog.FieldJobGroup:
		m.ResetJobGroup()
		return nil
	case sysjoblog.FieldHandler:
		m.ResetHandler()
		return nil
	case sysjoblog.FieldTriggerType:
		m.ResetTriggerType()
		return nil
	case sysjoblog.FieldExecNode:
		m.ResetExecNode()
		return nil
	case sysjoblog.FieldStatus:
		m.ResetStatus()
		return nil
	case sysjoblog.FieldAttempt:
		m.ResetAttempt()
		return nil
	case sysjoblog.FieldMessage:
		m.ResetMessage()
		return nil
	case sysjoblog.FieldExceptionInfo:
		m.ResetExceptionInfo()
		return nil
	case sysjoblog.FieldDuration:
		m.ResetDuration()
		return nil
	}
	return fmt.Errorf("unknown SysJobLog field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *SysJobLogMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *SysJobLogMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *SysJobLogMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *SysJobLogMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *SysJobLogMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *SysJobLogMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *SysJobLogMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown SysJobLog unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *SysJobLogMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown SysJobLog edge %s", name)
}
