// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/saas-zero/saas-zero-job/ent/sysjoblog"
)

// job_log Table | 定时任务执行日志表
type SysJobLog struct {
	config `json:"-"`
	// ID of the ent.
	// Primary Key | 主键ID，可自定义雪花ID
	ID int64 `json:"id,omitempty"`
	// Create Time | 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Creator ID | 创建人ID
	CreatedID int64 `json:"created_id,omitempty"`
	// Creator Name | 创建人名称
	CreatedBy string `json:"created_by,omitempty"`
	// 任务ID | Job ID
	JobID int64 `json:"job_id,omitempty"`
	// 任务名称(快照) | Job Name(snapshot)
	JobName string `json:"job_name,omitempty"`
	// 任务分组(快照) | Job Group(snapshot)
	JobGroup string `json:"job_group,omitempty"`
	// 处理器注册码(快照) | Handler Code(snapshot)
	Handler string `json:"handler,omitempty"`
	// 触发方式: cron-调度, manual-手动, retry-重试 | Trigger Type
	TriggerType sysjoblog.TriggerType `json:"trigger_type,omitempty"`
	// 执行实例标识(hostname:pid，容器主机名可能较长) | Executor Node
	ExecNode string `json:"exec_node,omitempty"`
	// 执行状态 | Execution Status
	Status sysjoblog.Status `json:"status,omitempty"`
	// 尝试次数(1=首次) | Attempt
	Attempt int32 `json:"attempt,omitempty"`
	// 结果摘要 | Result Message
	Message string `json:"message,omitempty"`
	// 异常信息(截断) | Exception Info(truncated)
	ExceptionInfo string `json:"exception_info,omitempty"`
	// 执行时长(毫秒) | Duration(ms)
	Duration     int64 `json:"duration,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SysJobLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sysjoblog.FieldID, sysjoblog.FieldCreatedID, sysjoblog.FieldJobID, sysjoblog.FieldAttempt, sysjoblog.FieldDuration:
			values[i] = new(sql.NullInt64)
		case sysjoblog.FieldCreatedBy, sysjoblog.FieldJobName, sysjoblog.FieldJobGroup, sysjoblog.FieldHandler, sysjoblog.FieldTriggerType, sysjoblog.FieldExecNode, sysjoblog.FieldStatus, sysjoblog.FieldMessage, sysjoblog.FieldExceptionInfo:
			values[i] = new(sql.NullString)
		case sysjoblog.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SysJobLog fields.
func (_m *SysJobLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sysjoblog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case sysjoblog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case sysjoblog.FieldCreatedID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_id", values[i])
			} else if value.Valid {
				_m.CreatedID = value.Int64
			}
		case sysjoblog.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.String
			}
		case sysjoblog.FieldJobID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field job_id", values[i])
			} else if value.Valid {
				_m.JobID = value.Int64
			}
		case sysjoblog.FieldJobName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field job_name", values[i])
			} else if value.Valid {
				_m.JobName = value.String
			}
		case sysjoblog.FieldJobGroup:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field job_group", values[i])
			} else if value.Valid {
				_m.JobGroup = value.String
			}
		case sysjoblog.FieldHandler:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field handler", values[i])
			} else if value.Valid {
				_m.Handler = value.String
			}
		case sysjoblog.FieldTriggerType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trigger_type", values[i])
			} else if value.Valid {
				_m.TriggerType = sysjoblog.TriggerType(value.String)
			}
		case sysjoblog.FieldExecNode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field exec_node", values[i])
			} else if value.Valid {
				_m.ExecNode = value.String
			}
		case sysjoblog.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = sysjoblog.Status(value.String)
			}
		case sysjoblog.FieldAttempt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempt", values[i])
			} else if value.Valid {
				_m.Attempt = int32(value.Int64)
			}
		case sysjoblog.FieldMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message", values[i])
			} else if value.Valid {
				_m.Message = value.String
			}
		case sysjoblog.FieldExceptionInfo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field exception_info", values[i])
			} else if value.Valid {
				_m.ExceptionInfo = value.String
			}
		case sysjoblog.FieldDuration:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field duration", values[i])
			} else if value.Valid {
				_m.Duration = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SysJobLog.
// This includes values selected through modifiers, order, etc.
func (_m *SysJobLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SysJobLog.
// Note that you need to call SysJobLog.Unwrap() before calling this method if this SysJobLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SysJobLog) Update() *SysJobLogUpdateOne {
	return NewSysJobLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SysJobLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SysJobLog) Unwrap() *SysJobLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SysJobLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SysJobLog) String() string {
	var builder strings.Builder
	builder.WriteString("SysJobLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedID))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(_m.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("job_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.JobID))
	builder.WriteString(", ")
	builder.WriteString("job_name=")
	builder.WriteString(_m.JobName)
	builder.WriteString(", ")
	builder.WriteString("job_group=")
	builder.WriteString(_m.JobGroup)
	builder.WriteString(", ")
	builder.WriteString("handler=")
	builder.WriteString(_m.Handler)
	builder.WriteString(", ")
	builder.WriteString("trigger_type=")
	builder.WriteString(fmt.Sprintf("%v", _m.TriggerType))
	builder.WriteString(", ")
	builder.WriteString("exec_node=")
	builder.WriteString(_m.ExecNode)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("attempt=")
	builder.WriteString(fmt.Sprintf("%v", _m.Attempt))
	builder.WriteString(", ")
	builder.WriteString("message=")
	builder.WriteString(_m.Message)
	builder.WriteString(", ")
	builder.WriteString("exception_info=")
	builder.WriteString(_m.ExceptionInfo)
	builder.WriteString(", ")
	builder.WriteString("duration=")
	builder.WriteString(fmt.Sprintf("%v", _m.Duration))
	builder.WriteByte(')')
	return builder.String()
}

// SysJobLogs is a parsable slice of SysJobLog.
type SysJobLogs []*SysJobLog
