// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/saas-zero/saas-zero-job/ent/sysjoblog"
)

// SysJobLogCreate is the builder for creating a SysJobLog entity.
type SysJobLogCreate struct {
	config
	mutation *SysJobLogMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *SysJobLogCreate) SetCreatedAt(v time.Time) *SysJobLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SysJobLogCreate) SetNillableCreatedAt(v *time.Time) *SysJobLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetCreatedID sets the "created_id" field.
func (_c *SysJobLogCreate) SetCreatedID(v int64) *SysJobLogCreate {
	_c.mutation.SetCreatedID(v)
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *SysJobLogCreate) SetCreatedBy(v string) *SysJobLogCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetJobID sets the "job_id" field.
func (_c *SysJobLogCreate) SetJobID(v int64) *SysJobLogCreate {
	_c.mutation.SetJobID(v)
	return _c
}

// SetJobName sets the "job_name" field.
func (_c *SysJobLogCreate) SetJobName(v string) *SysJobLogCreate {
	_c.mutation.SetJobName(v)
	return _c
}

// SetNillableJobName sets the "job_name" field if the given value is not nil.
func (_c *SysJobLogCreate) SetNillableJobName(v *string) *SysJobLogCreate {
	if v != nil {
		_c.SetJobName(*v)
	}
	return _c
}

// SetJobGroup sets the "job_group" field.
func (_c *SysJobLogCreate) SetJobGroup(v string) *SysJobLogCreate {
	_c.mutation.SetJobGroup(v)
	return _c
}

// SetNillableJobGroup sets the "job_group" field if the given value is not nil.
func (_c *SysJobLogCreate) SetNillableJobGroup(v *string) *SysJobLogCreate {
	if v != nil {
		_c.SetJobGroup(*v)
	}
	return _c
}

// SetHandler sets the "handler" field.
func (_c *SysJobLogCreate) SetHandler(v string) *SysJobLogCreate {
	_c.mutation.SetHandler(v)
	return _c
}

// SetNillableHandler sets the "handler" field if the given value is not nil.
func (_c *SysJobLogCreate) SetNillableHandler(v *string) *SysJobLogCreate {
	if v != nil {
		_c.SetHandler(*v)
	}
	return _c
}

// SetTriggerType sets the "trigger_type" field.
func (_c *SysJobLogCreate) SetTriggerType(v sysjoblog.TriggerType) *SysJobLogCreate {
	_c.mutation.SetTriggerType(v)
	return _c
}

// SetNillableTriggerType sets the "trigger_type" field if the given value is not nil.
func (_c *SysJobLogCreate) SetNillableTriggerType(v *sysjoblog.TriggerType) *SysJobLogCreate {
	if v != nil {
		_c.SetTriggerType(*v)
	}
	return _c
}

// SetExecNode sets the "exec_node" field.
func (_c *SysJobLogCreate) SetExecNode(v string) *SysJobLogCreate {
	_c.mutation.SetExecNode(v)
	return _c
}

// SetNillableExecNode sets the "exec_node" field if the given value is not nil.
func (_c *SysJobLogCreate) SetNillableExecNode(v *string) *SysJobLogCreate {
	if v != nil {
		_c.SetExecNode(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *SysJobLogCreate) SetStatus(v sysjoblog.Status) *SysJobLogCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SysJobLogCreate) SetNillableStatus(v *sysjoblog.Status) *SysJobLogCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetAttempt sets the "attempt" field.
func (_c *SysJobLogCreate) SetAttempt(v int32) *SysJobLogCreate {
	_c.mutation.SetAttempt(v)
	return _c
}

// SetNillableAttempt sets the "attempt" field if the given value is not nil.
func (_c *SysJobLogCreate) SetNillableAttempt(v *int32) *SysJobLogCreate {
	if v != nil {
		_c.SetAttempt(*v)
	}
	return _c
}

// SetMessage sets the "message" field.
func (_c *SysJobLogCreate) SetMessage(v string) *SysJobLogCreate {
	_c.mutation.SetMessage(v)
	return _c
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_c *SysJobLogCreate) SetNillableMessage(v *string) *SysJobLogCreate {
	if v != nil {
		_c.SetMessage(*v)
	}
	return _c
}

// SetExceptionInfo sets the "exception_info" field.
func (_c *SysJobLogCreate) SetExceptionInfo(v string) *SysJobLogCreate {
	_c.mutation.SetExceptionInfo(v)
	return _c
}

// SetNillableExceptionInfo sets the "exception_info" field if the given value is not nil.
func (_c *SysJobLogCreate) SetNillableExceptionInfo(v *string) *SysJobLogCreate {
	if v != nil {
		_c.SetExceptionInfo(*v)
	}
	return _c
}

// SetDuration sets the "duration" field.
func (_c *SysJobLogCreate) SetDuration(v int64) *SysJobLogCreate {
	_c.mutation.SetDuration(v)
	return _c
}

// SetNillableDuration sets the "duration" field if the given value is not nil.
func (_c *SysJobLogCreate) SetNillableDuration(v *int64) *SysJobLogCreate {
	if v != nil {
		_c.SetDuration(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SysJobLogCreate) SetID(v int64) *SysJobLogCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the SysJobLogMutation object of the builder.
func (_c *SysJobLogCreate) Mutation() *SysJobLogMutation {
	return _c.mutation
}

// Save creates the SysJobLog in the database.
func (_c *SysJobLogCreate) Save(ctx context.Context) (*SysJobLog, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SysJobLogCreate) SaveX(ctx context.Context) *SysJobLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SysJobLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SysJobLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SysJobLogCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if sysjoblog.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized sysjoblog.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := sysjoblog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.JobName(); !ok {
		v := sysjoblog.DefaultJobName
		_c.mutation.SetJobName(v)
	}
	if _, ok := _c.mutation.JobGroup(); !ok {
		v := sysjoblog.DefaultJobGroup
		_c.mutation.SetJobGroup(v)
	}
	if _, ok := _c.mutation.Handler(); !ok {
		v := sysjoblog.DefaultHandler
		_c.mutation.SetHandler(v)
	}
	if _, ok := _c.mutation.TriggerType(); !ok {
		v := sysjoblog.DefaultTriggerType
		_c.mutation.SetTriggerType(v)
	}
	if _, ok := _c.mutation.ExecNode(); !ok {
		v := sysjoblog.DefaultExecNode
		_c.mutation.SetExecNode(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := sysjoblog.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Attempt(); !ok {
		v := sysjoblog.DefaultAttempt
		_c.mutation.SetAttempt(v)
	}
	if _, ok := _c.mutation.Message(); !ok {
		v := sysjoblog.DefaultMessage
		_c.mutation.SetMessage(v)
	}
	if _, ok := _c.mutation.ExceptionInfo(); !ok {
		v := sysjoblog.DefaultExceptionInfo
		_c.mutation.SetExceptionInfo(v)
	}
	if _, ok := _c.mutation.Duration(); !ok {
		v := sysjoblog.DefaultDuration
		_c.mutation.SetDuration(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *SysJobLogCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SysJobLog.created_at"`)}
	}
	if _, ok := _c.mutation.CreatedID(); !ok {
		return &ValidationError{Name: "created_id", err: errors.New(`ent: missing required field "SysJobLog.created_id"`)}
	}
	if v, ok := _c.mutation.CreatedID(); ok {
		if err := sysjoblog.CreatedIDValidator(v); err != nil {
			return &ValidationError{Name: "created_id", err: fmt.Errorf(`ent: validator failed for field "SysJobLog.created_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "SysJobLog.created_by"`)}
	}
	if v, ok := _c.mutation.CreatedBy(); ok {
		if err := sysjoblog.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "SysJobLog.created_by": %w`, err)}
		}
	}
	if _, ok := _c.mutation.JobID(); !ok {
		return &ValidationError{Name: "job_id", err: errors.New(`ent: missing required field "SysJobLog.job_id"`)}
	}
	if v, ok := _c.mutation.JobID(); ok {
		if err := sysjoblog.JobIDValidator(v); err != nil {
			return &ValidationError{Name: "job_id", err: fmt.Errorf(`ent: validator failed for field "SysJobLog.job_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.JobName(); !ok {
		return &ValidationError{Name: "job_name", err: errors.New(`ent: missing required field "SysJobLog.job_name"`)}
	}
	if v, ok := _c.mutation.JobName(); ok {
		if err := sysjoblog.JobNameValidator(v); err != nil {
			return &ValidationError{Name: "job_name", err: fmt.Errorf(`ent: validator failed for field "SysJobLog.job_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.JobGroup(); !ok {
		return &ValidationError{Name: "job_group", err: errors.New(`ent: missing required field "SysJobLog.job_group"`)}
	}
	if v, ok := _c.mutation.JobGroup(); ok {
		if err := sysjoblog.JobGroupValidator(v); err != nil {
			return &ValidationError{Name: "job_group", err: fmt.Errorf(`ent: validator failed for field "SysJobLog.job_group": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Handler(); !ok {
		return &ValidationError{Name: "handler", err: errors.New(`ent: missing required field "SysJobLog.handler"`)}
	}
	if v, ok := _c.mutation.Handler(); ok {
		if err := sysjoblog.HandlerValidator(v); err != nil {
			return &ValidationError{Name: "handler", err: fmt.Errorf(`ent: validator failed for field "SysJobLog.handler": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TriggerType(); !ok {
		return &ValidationError{Name: "trigger_type", err: errors.New(`ent: missing required field "SysJobLog.trigger_type"`)}
	}
	if v, ok := _c.mutation.TriggerType(); ok {
		if err := sysjoblog.TriggerTypeValidator(v); err != nil {
			return &ValidationError{Name: "trigger_type", err: fmt.Errorf(`ent: validator failed for field "SysJobLog.trigger_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExecNode(); !ok {
		return &ValidationError{Name: "exec_node", err: errors.New(`ent: missing required field "SysJobLog.exec_node"`)}
	}
	if v, ok := _c.mutation.ExecNode(); ok {
		if err := sysjoblog.ExecNodeValidator(v); err != nil {
			return &ValidationError{Name: "exec_node", err: fmt.Errorf(`ent: validator failed for field "SysJobLog.exec_node": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SysJobLog.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := sysjoblog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SysJobLog.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Attempt(); !ok {
		return &ValidationError{Name: "attempt", err: errors.New(`ent: missing required field "SysJobLog.attempt"`)}
	}
	if v, ok := _c.mutation.Attempt(); ok {
		if err := sysjoblog.AttemptValidator(v); err != nil {
			return &ValidationError{Name: "attempt", err: fmt.Errorf(`ent: validator failed for field "SysJobLog.attempt": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Message(); !ok {
		return &ValidationError{Name: "message", err: errors.New(`ent: missing required field "SysJobLog.message"`)}
	}
	if v, ok := _c.mutation.Message(); ok {
		if err := sysjoblog.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "SysJobLog.message": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ExceptionInfo(); !ok {
		return &ValidationError{Name: "exception_info", err: errors.New(`ent: missing required field "SysJobLog.exception_info"`)}
	}
	if v, ok := _c.mutation.ExceptionInfo(); ok {
		if err := sysjoblog.ExceptionInfoValidator(v); err != nil {
			return &ValidationError{Name: "exception_info", err: fmt.Errorf(`ent: validator failed for field "SysJobLog.exception_info": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Duration(); !ok {
		return &ValidationError{Name: "duration", err: errors.New(`ent: missing required field "SysJobLog.duration"`)}
	}
	if v, ok := _c.mutation.Duration(); ok {
		if err := sysjoblog.DurationValidator(v); err != nil {
			return &ValidationError{Name: "duration", err: fmt.Errorf(`ent: validator failed for field "SysJobLog.duration": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := sysjoblog.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "SysJobLog.id": %w`, err)}
		}
	}
	return nil
}

func (_c *SysJobLogCreate) sqlSave(ctx context.Context) (*SysJobLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SysJobLogCreate) createSpec() (*SysJobLog, *sqlgraph.CreateSpec) {
	var (
		_node = &SysJobLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sysjoblog.Table, sqlgraph.NewFieldSpec(sysjoblog.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(sysjoblog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.CreatedID(); ok {
		_spec.SetField(sysjoblog.FieldCreatedID, field.TypeInt64, value)
		_node.CreatedID = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(sysjoblog.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.JobID(); ok {
		_spec.SetField(sysjoblog.FieldJobID, field.TypeInt64, value)
		_node.JobID = value
	}
	if value, ok := _c.mutation.JobName(); ok {
		_spec.SetField(sysjoblog.FieldJobName, field.TypeString, value)
		_node.JobName = value
	}
	if value, ok := _c.mutation.JobGroup(); ok {
		_spec.SetField(sysjoblog.FieldJobGroup, field.TypeString, value)
		_node.JobGroup = value
	}
	if value, ok := _c.mutation.Handler(); ok {
		_spec.SetField(sysjoblog.FieldHandler, field.TypeString, value)
		_node.Handler = value
	}
	if value, ok := _c.mutation.TriggerType(); ok {
		_spec.SetField(sysjoblog.FieldTriggerType, field.TypeEnum, value)
		_node.TriggerType = value
	}
	if value, ok := _c.mutation.ExecNode(); ok {
		_spec.SetField(sysjoblog.FieldExecNode, field.TypeString, value)
		_node.ExecNode = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(sysjoblog.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Attempt(); ok {
		_spec.SetField(sysjoblog.FieldAttempt, field.TypeInt32, value)
		_node.Attempt = value
	}
	if value, ok := _c.mutation.Message(); ok {
		_spec.SetField(sysjoblog.FieldMessage, field.TypeString, value)
		_node.Message = value
	}
	if value, ok := _c.mutation.ExceptionInfo(); ok {
		_spec.SetField(sysjoblog.FieldExceptionInfo, field.TypeString, value)
		_node.ExceptionInfo = value
	}
	if value, ok := _c.mutation.Duration(); ok {
		_spec.SetField(sysjoblog.FieldDuration, field.TypeInt64, value)
		_node.Duration = value
	}
	return _node, _spec
}

// SysJobLogCreateBulk is the builder for creating many SysJobLog entities in bulk.
type SysJobLogCreateBulk struct {
	config
	err      error
	builders []*SysJobLogCreate
}

// Save creates the SysJobLog entities in the database.
func (_c *SysJobLogCreateBulk) Save(ctx context.Context) ([]*SysJobLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SysJobLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SysJobLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SysJobLogCreateBulk) SaveX(ctx context.Context) []*SysJobLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SysJobLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SysJobLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
