// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/saas-zero/saas-zero-job/ent/predicate"
	"github.com/saas-zero/saas-zero-job/ent/sysjoblog"
)

// SysJobLogUpdate is the builder for updating SysJobLog entities.
type SysJobLogUpdate struct {
	config
	hooks    []Hook
	mutation *SysJobLogMutation
}

// Where appends a list predicates to the SysJobLogUpdate builder.
func (_u *SysJobLogUpdate) Where(ps ...predicate.SysJobLog) *SysJobLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetJobID sets the "job_id" field.
func (_u *SysJobLogUpdate) SetJobID(v int64) *SysJobLogUpdate {
	_u.mutation.ResetJobID()
	_u.mutation.SetJobID(v)
	return _u
}

// SetNillableJobID sets the "job_id" field if the given value is not nil.
func (_u *SysJobLogUpdate) SetNillableJobID(v *int64) *SysJobLogUpdate {
	if v != nil {
		_u.SetJobID(*v)
	}
	return _u
}

// AddJobID adds value to the "job_id" field.
func (_u *SysJobLogUpdate) AddJobID(v int64) *SysJobLogUpdate {
	_u.mutation.AddJobID(v)
	return _u
}

// SetJobName sets the "job_name" field.
func (_u *SysJobLogUpdate) SetJobName(v string) *SysJobLogUpdate {
	_u.mutation.SetJobName(v)
	return _u
}

// SetNillableJobName sets the "job_name" field if the given value is not nil.
func (_u *SysJobLogUpdate) SetNillableJobName(v *string) *SysJobLogUpdate {
	if v != nil {
		_u.SetJobName(*v)
	}
	return _u
}

// SetJobGroup sets the "job_group" field.
func (_u *SysJobLogUpdate) SetJobGroup(v string) *SysJobLogUpdate {
	_u.mutation.SetJobGroup(v)
	return _u
}

// SetNillableJobGroup sets the "job_group" field if the given value is not nil.
func (_u *SysJobLogUpdate) SetNillableJobGroup(v *string) *SysJobLogUpdate {
	if v != nil {
		_u.SetJobGroup(*v)
	}
	return _u
}

// SetHandler sets the "handler" field.
func (_u *SysJobLogUpdate) SetHandler(v string) *SysJobLogUpdate {
	_u.mutation.SetHandler(v)
	return _u
}

// SetNillableHandler sets the "handler" field if the given value is not nil.
func (_u *SysJobLogUpdate) SetNillableHandler(v *string) *SysJobLogUpdate {
	if v != nil {
		_u.SetHandler(*v)
	}
	return _u
}

// SetTriggerType sets the "trigger_type" field.
func (_u *SysJobLogUpdate) SetTriggerType(v sysjoblog.TriggerType) *SysJobLogUpdate {
	_u.mutation.SetTriggerType(v)
	return _u
}

// SetNillableTriggerType sets the "trigger_type" field if the given value is not nil.
func (_u *SysJobLogUpdate) SetNillableTriggerType(v *sysjoblog.TriggerType) *SysJobLogUpdate {
	if v != nil {
		_u.SetTriggerType(*v)
	}
	return _u
}

// SetExecNode sets the "exec_node" field.
func (_u *SysJobLogUpdate) SetExecNode(v string) *SysJobLogUpdate {
	_u.mutation.SetExecNode(v)
	return _u
}

// SetNillableExecNode sets the "exec_node" field if the given value is not nil.
func (_u *SysJobLogUpdate) SetNillableExecNode(v *string) *SysJobLogUpdate {
	if v != nil {
		_u.SetExecNode(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SysJobLogUpdate) SetStatus(v sysjoblog.Status) *SysJobLogUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SysJobLogUpdate) SetNillableStatus(v *sysjoblog.Status) *SysJobLogUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAttempt sets the "attempt" field.
func (_u *SysJobLogUpdate) SetAttempt(v int32) *SysJobLogUpdate {
	_u.mutation.ResetAttempt()
	_u.mutation.SetAttempt(v)
	return _u
}

// SetNillableAttempt sets the "attempt" field if the given value is not nil.
func (_u *SysJobLogUpdate) SetNillableAttempt(v *int32) *SysJobLogUpdate {
	if v != nil {
		_u.SetAttempt(*v)
	}
	return _u
}

// AddAttempt adds value to the "attempt" field.
func (_u *SysJobLogUpdate) AddAttempt(v int32) *SysJobLogUpdate {
	_u.mutation.AddAttempt(v)
	return _u
}

// SetMessage sets the "message" field.
func (_u *SysJobLogUpdate) SetMessage(v string) *SysJobLogUpdate {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *SysJobLogUpdate) SetNillableMessage(v *string) *SysJobLogUpdate {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// SetExceptionInfo sets the "exception_info" field.
func (_u *SysJobLogUpdate) SetExceptionInfo(v string) *SysJobLogUpdate {
	_u.mutation.SetExceptionInfo(v)
	return _u
}

// SetNillableExceptionInfo sets the "exception_info" field if the given value is not nil.
func (_u *SysJobLogUpdate) SetNillableExceptionInfo(v *string) *SysJobLogUpdate {
	if v != nil {
		_u.SetExceptionInfo(*v)
	}
	return _u
}

// SetDuration sets the "duration" field.
func (_u *SysJobLogUpdate) SetDuration(v int64) *SysJobLogUpdate {
	_u.mutation.ResetDuration()
	_u.mutation.SetDuration(v)
	return _u
}

// SetNillableDuration sets the "duration" field if the given value is not nil.
func (_u *SysJobLogUpdate) SetNillableDuration(v *int64) *SysJobLogUpdate {
	if v != nil {
		_u.SetDuration(*v)
	}
	return _u
}

// AddDuration adds value to the "duration" field.
func (_u *SysJobLogUpdate) AddDuration(v int64) *SysJobLogUpdate {
	_u.mutation.AddDuration(v)
	return _u
}

// Mutation returns the SysJobLogMutation object of the builder.
func (_u *SysJobLogUpdate) Mutation() *SysJobLogMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SysJobLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SysJobLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SysJobLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SysJobLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SysJobLogUpdate) check() error {
	if v, ok := _u.mutation.JobID(); ok {
		if err := sysjoblog.JobIDValidator(v); err != nil {
			return &ValidationError{Name: "job_id", err: fmt.Errorf(`ent: validator failed for field "SysJobLog.job_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.JobName(); ok {
		if err := sysjoblog.JobNameValidator(v); err != nil {
			return &ValidationError{Name: "job_name", err: fmt.Errorf(`ent: validator failed for field "SysJobLog.job_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.JobGroup(); ok {
		if err := sysjoblog.JobGroupValidator(v); err != nil {
			return &ValidationError{Name: "job_group", err: fmt.Errorf(`ent: validator failed for field "SysJobLog.job_group": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Handler(); ok {
		if err := sysjoblog.HandlerValidator(v); err != nil {
			return &ValidationError{Name: "handler", err: fmt.Errorf(`ent: validator failed for field "SysJobLog.handler": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TriggerType(); ok {
		if err := sysjoblog.TriggerTypeValidator(v); err != nil {
			return &ValidationError{Name: "trigger_type", err: fmt.Errorf(`ent: validator failed for field "SysJobLog.trigger_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExecNode(); ok {
		if err := sysjoblog.ExecNodeValidator(v); err != nil {
			return &ValidationError{Name: "exec_node", err: fmt.Errorf(`ent: validator failed for field "SysJobLog.exec_node": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := sysjoblog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SysJobLog.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Attempt(); ok {
		if err := sysjoblog.AttemptValidator(v); err != nil {
			return &ValidationError{Name: "attempt", err: fmt.Errorf(`ent: validator failed for field "SysJobLog.attempt": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Message(); ok {
		if err := sysjoblog.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "SysJobLog.message": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExceptionInfo(); ok {
		if err := sysjoblog.ExceptionInfoValidator(v); err != nil {
			return &ValidationError{Name: "exception_info", err: fmt.Errorf(`ent: validator failed for field "SysJobLog.exception_info": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Duration(); ok {
		if err := sysjoblog.DurationValidator(v); err != nil {
			return &ValidationError{Name: "duration", err: fmt.Errorf(`ent: validator failed for field "SysJobLog.duration": %w`, err)}
		}
	}
	return nil
}

func (_u *SysJobLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sysjoblog.Table, sysjoblog.Columns, sqlgraph.NewFieldSpec(sysjoblog.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.JobID(); ok {
		_spec.SetField(sysjoblog.FieldJobID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedJobID(); ok {
		_spec.AddField(sysjoblog.FieldJobID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.JobName(); ok {
		_spec.SetField(sysjoblog.FieldJobName, field.TypeString, value)
	}
	if value, ok := _u.mutation.JobGroup(); ok {
		_spec.SetField(sysjoblog.FieldJobGroup, field.TypeString, value)
	}
	if value, ok := _u.mutation.Handler(); ok {
		_spec.SetField(sysjoblog.FieldHandler, field.TypeString, value)
	}
	if value, ok := _u.mutation.TriggerType(); ok {
		_spec.SetField(sysjoblog.FieldTriggerType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ExecNode(); ok {
		_spec.SetField(sysjoblog.FieldExecNode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(sysjoblog.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Attempt(); ok {
		_spec.SetField(sysjoblog.FieldAttempt, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedAttempt(); ok {
		_spec.AddField(sysjoblog.FieldAttempt, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(sysjoblog.FieldMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExceptionInfo(); ok {
		_spec.SetField(sysjoblog.FieldExceptionInfo, field.TypeString, value)
	}
	if value, ok := _u.mutation.Duration(); ok {
		_spec.SetField(sysjoblog.FieldDuration, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDuration(); ok {
		_spec.AddField(sysjoblog.FieldDuration, field.TypeInt64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sysjoblog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SysJobLogUpdateOne is the builder for updating a single SysJobLog entity.
type SysJobLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SysJobLogMutation
}

// SetJobID sets the "job_id" field.
func (_u *SysJobLogUpdateOne) SetJobID(v int64) *SysJobLogUpdateOne {
	_u.mutation.ResetJobID()
	_u.mutation.SetJobID(v)
	return _u
}

// SetNillableJobID sets the "job_id" field if the given value is not nil.
func (_u *SysJobLogUpdateOne) SetNillableJobID(v *int64) *SysJobLogUpdateOne {
	if v != nil {
		_u.SetJobID(*v)
	}
	return _u
}

// AddJobID adds value to the "job_id" field.
func (_u *SysJobLogUpdateOne) AddJobID(v int64) *SysJobLogUpdateOne {
	_u.mutation.AddJobID(v)
	return _u
}

// SetJobName sets the "job_name" field.
func (_u *SysJobLogUpdateOne) SetJobName(v string) *SysJobLogUpdateOne {
	_u.mutation.SetJobName(v)
	return _u
}

// SetNillableJobName sets the "job_name" field if the given value is not nil.
func (_u *SysJobLogUpdateOne) SetNillableJobName(v *string) *SysJobLogUpdateOne {
	if v != nil {
		_u.SetJobName(*v)
	}
	return _u
}

// SetJobGroup sets the "job_group" field.
func (_u *SysJobLogUpdateOne) SetJobGroup(v string) *SysJobLogUpdateOne {
	_u.mutation.SetJobGroup(v)
	return _u
}

// SetNillableJobGroup sets the "job_group" field if the given value is not nil.
func (_u *SysJobLogUpdateOne) SetNillableJobGroup(v *string) *SysJobLogUpdateOne {
	if v != nil {
		_u.SetJobGroup(*v)
	}
	return _u
}

// SetHandler sets the "handler" field.
func (_u *SysJobLogUpdateOne) SetHandler(v string) *SysJobLogUpdateOne {
	_u.mutation.SetHandler(v)
	return _u
}

// SetNillableHandler sets the "handler" field if the given value is not nil.
func (_u *SysJobLogUpdateOne) SetNillableHandler(v *string) *SysJobLogUpdateOne {
	if v != nil {
		_u.SetHandler(*v)
	}
	return _u
}

// SetTriggerType sets the "trigger_type" field.
func (_u *SysJobLogUpdateOne) SetTriggerType(v sysjoblog.TriggerType) *SysJobLogUpdateOne {
	_u.mutation.SetTriggerType(v)
	return _u
}

// SetNillableTriggerType sets the "trigger_type" field if the given value is not nil.
func (_u *SysJobLogUpdateOne) SetNillableTriggerType(v *sysjoblog.TriggerType) *SysJobLogUpdateOne {
	if v != nil {
		_u.SetTriggerType(*v)
	}
	return _u
}

// SetExecNode sets the "exec_node" field.
func (_u *SysJobLogUpdateOne) SetExecNode(v string) *SysJobLogUpdateOne {
	_u.mutation.SetExecNode(v)
	return _u
}

// SetNillableExecNode sets the "exec_node" field if the given value is not nil.
func (_u *SysJobLogUpdateOne) SetNillableExecNode(v *string) *SysJobLogUpdateOne {
	if v != nil {
		_u.SetExecNode(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SysJobLogUpdateOne) SetStatus(v sysjoblog.Status) *SysJobLogUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SysJobLogUpdateOne) SetNillableStatus(v *sysjoblog.Status) *SysJobLogUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAttempt sets the "attempt" field.
func (_u *SysJobLogUpdateOne) SetAttempt(v int32) *SysJobLogUpdateOne {
	_u.mutation.ResetAttempt()
	_u.mutation.SetAttempt(v)
	return _u
}

// SetNillableAttempt sets the "attempt" field if the given value is not nil.
func (_u *SysJobLogUpdateOne) SetNillableAttempt(v *int32) *SysJobLogUpdateOne {
	if v != nil {
		_u.SetAttempt(*v)
	}
	return _u
}

// AddAttempt adds value to the "attempt" field.
func (_u *SysJobLogUpdateOne) AddAttempt(v int32) *SysJobLogUpdateOne {
	_u.mutation.AddAttempt(v)
	return _u
}

// SetMessage sets the "message" field.
func (_u *SysJobLogUpdateOne) SetMessage(v string) *SysJobLogUpdateOne {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *SysJobLogUpdateOne) SetNillableMessage(v *string) *SysJobLogUpdateOne {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// SetExceptionInfo sets the "exception_info" field.
func (_u *SysJobLogUpdateOne) SetExceptionInfo(v string) *SysJobLogUpdateOne {
	_u.mutation.SetExceptionInfo(v)
	return _u
}

// SetNillableExceptionInfo sets the "exception_info" field if the given value is not nil.
func (_u *SysJobLogUpdateOne) SetNillableExceptionInfo(v *string) *SysJobLogUpdateOne {
	if v != nil {
		_u.SetExceptionInfo(*v)
	}
	return _u
}

// SetDuration sets the "duration" field.
func (_u *SysJobLogUpdateOne) SetDuration(v int64) *SysJobLogUpdateOne {
	_u.mutation.ResetDuration()
	_u.mutation.SetDuration(v)
	return _u
}

// SetNillableDuration sets the "duration" field if the given value is not nil.
func (_u *SysJobLogUpdateOne) SetNillableDuration(v *int64) *SysJobLogUpdateOne {
	if v != nil {
		_u.SetDuration(*v)
	}
	return _u
}

// AddDuration adds value to the "duration" field.
func (_u *SysJobLogUpdateOne) AddDuration(v int64) *SysJobLogUpdateOne {
	_u.mutation.AddDuration(v)
	return _u
}

// Mutation returns the SysJobLogMutation object of the builder.
func (_u *SysJobLogUpdateOne) Mutation() *SysJobLogMutation {
	return _u.mutation
}

// Where appends a list predicates to the SysJobLogUpdate builder.
func (_u *SysJobLogUpdateOne) Where(ps ...predicate.SysJobLog) *SysJobLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SysJobLogUpdateOne) Select(field string, fields ...string) *SysJobLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SysJobLog entity.
func (_u *SysJobLogUpdateOne) Save(ctx context.Context) (*SysJobLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SysJobLogUpdateOne) SaveX(ctx context.Context) *SysJobLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SysJobLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SysJobLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SysJobLogUpdateOne) check() error {
	if v, ok := _u.mutation.JobID(); ok {
		if err := sysjoblog.JobIDValidator(v); err != nil {
			return &ValidationError{Name: "job_id", err: fmt.Errorf(`ent: validator failed for field "SysJobLog.job_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.JobName(); ok {
		if err := sysjoblog.JobNameValidator(v); err != nil {
			return &ValidationError{Name: "job_name", err: fmt.Errorf(`ent: validator failed for field "SysJobLog.job_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.JobGroup(); ok {
		if err := sysjoblog.JobGroupValidator(v); err != nil {
			return &ValidationError{Name: "job_group", err: fmt.Errorf(`ent: validator failed for field "SysJobLog.job_group": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Handler(); ok {
		if err := sysjoblog.HandlerValidator(v); err != nil {
			return &ValidationError{Name: "handler", err: fmt.Errorf(`ent: validator failed for field "SysJobLog.handler": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TriggerType(); ok {
		if err := sysjoblog.TriggerTypeValidator(v); err != nil {
			return &ValidationError{Name: "trigger_type", err: fmt.Errorf(`ent: validator failed for field "SysJobLog.trigger_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExecNode(); ok {
		if err := sysjoblog.ExecNodeValidator(v); err != nil {
			return &ValidationError{Name: "exec_node", err: fmt.Errorf(`ent: validator failed for field "SysJobLog.exec_node": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := sysjoblog.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SysJobLog.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Attempt(); ok {
		if err := sysjoblog.AttemptValidator(v); err != nil {
			return &ValidationError{Name: "attempt", err: fmt.Errorf(`ent: validator failed for field "SysJobLog.attempt": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Message(); ok {
		if err := sysjoblog.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "SysJobLog.message": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ExceptionInfo(); ok {
		if err := sysjoblog.ExceptionInfoValidator(v); err != nil {
			return &ValidationError{Name: "exception_info", err: fmt.Errorf(`ent: validator failed for field "SysJobLog.exception_info": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Duration(); ok {
		if err := sysjoblog.DurationValidator(v); err != nil {
			return &ValidationError{Name: "duration", err: fmt.Errorf(`ent: validator failed for field "SysJobLog.duration": %w`, err)}
		}
	}
	return nil
}

func (_u *SysJobLogUpdateOne) sqlSave(ctx context.Context) (_node *SysJobLog, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sysjoblog.Table, sysjoblog.Columns, sqlgraph.NewFieldSpec(sysjoblog.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SysJobLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sysjoblog.FieldID)
		for _, f := range fields {
			if !sysjoblog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sysjoblog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.JobID(); ok {
		_spec.SetField(sysjoblog.FieldJobID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedJobID(); ok {
		_spec.AddField(sysjoblog.FieldJobID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.JobName(); ok {
		_spec.SetField(sysjoblog.FieldJobName, field.TypeString, value)
	}
	if value, ok := _u.mutation.JobGroup(); ok {
		_spec.SetField(sysjoblog.FieldJobGroup, field.TypeString, value)
	}
	if value, ok := _u.mutation.Handler(); ok {
		_spec.SetField(sysjoblog.FieldHandler, field.TypeString, value)
	}
	if value, ok := _u.mutation.TriggerType(); ok {
		_spec.SetField(sysjoblog.FieldTriggerType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ExecNode(); ok {
		_spec.SetField(sysjoblog.FieldExecNode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(sysjoblog.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Attempt(); ok {
		_spec.SetField(sysjoblog.FieldAttempt, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedAttempt(); ok {
		_spec.AddField(sysjoblog.FieldAttempt, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(sysjoblog.FieldMessage, field.TypeString, value)
	}
	if value, ok := _u.mutation.ExceptionInfo(); ok {
		_spec.SetField(sysjoblog.FieldExceptionInfo, field.TypeString, value)
	}
	if value, ok := _u.mutation.Duration(); ok {
		_spec.SetField(sysjoblog.FieldDuration, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDuration(); ok {
		_spec.AddField(sysjoblog.FieldDuration, field.TypeInt64, value)
	}
	_node = &SysJobLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sysjoblog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
