// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/saas-zero/saas-zero-job/ent/sysjob"
)

// SysJobCreate is the builder for creating a SysJob entity.
type SysJobCreate struct {
	config
	mutation *SysJobMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *SysJobCreate) SetCreatedAt(v time.Time) *SysJobCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SysJobCreate) SetNillableCreatedAt(v *time.Time) *SysJobCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetCreatedID sets the "created_id" field.
func (_c *SysJobCreate) SetCreatedID(v int64) *SysJobCreate {
	_c.mutation.SetCreatedID(v)
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *SysJobCreate) SetCreatedBy(v string) *SysJobCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SysJobCreate) SetUpdatedAt(v time.Time) *SysJobCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SysJobCreate) SetNillableUpdatedAt(v *time.Time) *SysJobCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUpdatedID sets the "updated_id" field.
func (_c *SysJobCreate) SetUpdatedID(v int64) *SysJobCreate {
	_c.mutation.SetUpdatedID(v)
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *SysJobCreate) SetUpdatedBy(v string) *SysJobCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *SysJobCreate) SetDeletedAt(v time.Time) *SysJobCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *SysJobCreate) SetNillableDeletedAt(v *time.Time) *SysJobCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetDeletedID sets the "deleted_id" field.
func (_c *SysJobCreate) SetDeletedID(v int64) *SysJobCreate {
	_c.mutation.SetDeletedID(v)
	return _c
}

// SetNillableDeletedID sets the "deleted_id" field if the given value is not nil.
func (_c *SysJobCreate) SetNillableDeletedID(v *int64) *SysJobCreate {
	if v != nil {
		_c.SetDeletedID(*v)
	}
	return _c
}

// SetDeletedBy sets the "deleted_by" field.
func (_c *SysJobCreate) SetDeletedBy(v string) *SysJobCreate {
	_c.mutation.SetDeletedBy(v)
	return _c
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_c *SysJobCreate) SetNillableDeletedBy(v *string) *SysJobCreate {
	if v != nil {
		_c.SetDeletedBy(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *SysJobCreate) SetStatus(v sysjob.Status) *SysJobCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SysJobCreate) SetNillableStatus(v *sysjob.Status) *SysJobCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetRemark sets the "remark" field.
func (_c *SysJobCreate) SetRemark(v string) *SysJobCreate {
	_c.mutation.SetRemark(v)
	return _c
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_c *SysJobCreate) SetNillableRemark(v *string) *SysJobCreate {
	if v != nil {
		_c.SetRemark(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *SysJobCreate) SetName(v string) *SysJobCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetGroup sets the "group" field.
func (_c *SysJobCreate) SetGroup(v string) *SysJobCreate {
	_c.mutation.SetGroup(v)
	return _c
}

// SetNillableGroup sets the "group" field if the given value is not nil.
func (_c *SysJobCreate) SetNillableGroup(v *string) *SysJobCreate {
	if v != nil {
		_c.SetGroup(*v)
	}
	return _c
}

// SetHandler sets the "handler" field.
func (_c *SysJobCreate) SetHandler(v string) *SysJobCreate {
	_c.mutation.SetHandler(v)
	return _c
}

// SetParams sets the "params" field.
func (_c *SysJobCreate) SetParams(v string) *SysJobCreate {
	_c.mutation.SetParams(v)
	return _c
}

// SetNillableParams sets the "params" field if the given value is not nil.
func (_c *SysJobCreate) SetNillableParams(v *string) *SysJobCreate {
	if v != nil {
		_c.SetParams(*v)
	}
	return _c
}

// SetCronExpression sets the "cron_expression" field.
func (_c *SysJobCreate) SetCronExpression(v string) *SysJobCreate {
	_c.mutation.SetCronExpression(v)
	return _c
}

// SetTimeZone sets the "time_zone" field.
func (_c *SysJobCreate) SetTimeZone(v string) *SysJobCreate {
	_c.mutation.SetTimeZone(v)
	return _c
}

// SetNillableTimeZone sets the "time_zone" field if the given value is not nil.
func (_c *SysJobCreate) SetNillableTimeZone(v *string) *SysJobCreate {
	if v != nil {
		_c.SetTimeZone(*v)
	}
	return _c
}

// SetMisfirePolicy sets the "misfire_policy" field.
func (_c *SysJobCreate) SetMisfirePolicy(v sysjob.MisfirePolicy) *SysJobCreate {
	_c.mutation.SetMisfirePolicy(v)
	return _c
}

// SetNillableMisfirePolicy sets the "misfire_policy" field if the given value is not nil.
func (_c *SysJobCreate) SetNillableMisfirePolicy(v *sysjob.MisfirePolicy) *SysJobCreate {
	if v != nil {
		_c.SetMisfirePolicy(*v)
	}
	return _c
}

// SetConcurrent sets the "concurrent" field.
func (_c *SysJobCreate) SetConcurrent(v bool) *SysJobCreate {
	_c.mutation.SetConcurrent(v)
	return _c
}

// SetNillableConcurrent sets the "concurrent" field if the given value is not nil.
func (_c *SysJobCreate) SetNillableConcurrent(v *bool) *SysJobCreate {
	if v != nil {
		_c.SetConcurrent(*v)
	}
	return _c
}

// SetTimeout sets the "timeout" field.
func (_c *SysJobCreate) SetTimeout(v int32) *SysJobCreate {
	_c.mutation.SetTimeout(v)
	return _c
}

// SetNillableTimeout sets the "timeout" field if the given value is not nil.
func (_c *SysJobCreate) SetNillableTimeout(v *int32) *SysJobCreate {
	if v != nil {
		_c.SetTimeout(*v)
	}
	return _c
}

// SetMaxRetry sets the "max_retry" field.
func (_c *SysJobCreate) SetMaxRetry(v int32) *SysJobCreate {
	_c.mutation.SetMaxRetry(v)
	return _c
}

// SetNillableMaxRetry sets the "max_retry" field if the given value is not nil.
func (_c *SysJobCreate) SetNillableMaxRetry(v *int32) *SysJobCreate {
	if v != nil {
		_c.SetMaxRetry(*v)
	}
	return _c
}

// SetRetryInterval sets the "retry_interval" field.
func (_c *SysJobCreate) SetRetryInterval(v int32) *SysJobCreate {
	_c.mutation.SetRetryInterval(v)
	return _c
}

// SetNillableRetryInterval sets the "retry_interval" field if the given value is not nil.
func (_c *SysJobCreate) SetNillableRetryInterval(v *int32) *SysJobCreate {
	if v != nil {
		_c.SetRetryInterval(*v)
	}
	return _c
}

// SetNextRunAt sets the "next_run_at" field.
func (_c *SysJobCreate) SetNextRunAt(v time.Time) *SysJobCreate {
	_c.mutation.SetNextRunAt(v)
	return _c
}

// SetNillableNextRunAt sets the "next_run_at" field if the given value is not nil.
func (_c *SysJobCreate) SetNillableNextRunAt(v *time.Time) *SysJobCreate {
	if v != nil {
		_c.SetNextRunAt(*v)
	}
	return _c
}

// SetLastRunAt sets the "last_run_at" field.
func (_c *SysJobCreate) SetLastRunAt(v time.Time) *SysJobCreate {
	_c.mutation.SetLastRunAt(v)
	return _c
}

// SetNillableLastRunAt sets the "last_run_at" field if the given value is not nil.
func (_c *SysJobCreate) SetNillableLastRunAt(v *time.Time) *SysJobCreate {
	if v != nil {
		_c.SetLastRunAt(*v)
	}
	return _c
}

// SetLastStatus sets the "last_status" field.
func (_c *SysJobCreate) SetLastStatus(v string) *SysJobCreate {
	_c.mutation.SetLastStatus(v)
	return _c
}

// SetNillableLastStatus sets the "last_status" field if the given value is not nil.
func (_c *SysJobCreate) SetNillableLastStatus(v *string) *SysJobCreate {
	if v != nil {
		_c.SetLastStatus(*v)
	}
	return _c
}

// SetLastDuration sets the "last_duration" field.
func (_c *SysJobCreate) SetLastDuration(v int64) *SysJobCreate {
	_c.mutation.SetLastDuration(v)
	return _c
}

// SetNillableLastDuration sets the "last_duration" field if the given value is not nil.
func (_c *SysJobCreate) SetNillableLastDuration(v *int64) *SysJobCreate {
	if v != nil {
		_c.SetLastDuration(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *SysJobCreate) SetLastError(v string) *SysJobCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *SysJobCreate) SetNillableLastError(v *string) *SysJobCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SysJobCreate) SetID(v int64) *SysJobCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the SysJobMutation object of the builder.
func (_c *SysJobCreate) Mutation() *SysJobMutation {
	return _c.mutation
}

// Save creates the SysJob in the database.
func (_c *SysJobCreate) Save(ctx context.Context) (*SysJob, error) {
	if err := _c.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SysJobCreate) SaveX(ctx context.Context) *SysJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SysJobCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SysJobCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SysJobCreate) defaults() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		if sysjob.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized sysjob.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := sysjob.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		if sysjob.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized sysjob.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := sysjob.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := sysjob.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Group(); !ok {
		v := sysjob.DefaultGroup
		_c.mutation.SetGroup(v)
	}
	if _, ok := _c.mutation.Params(); !ok {
		v := sysjob.DefaultParams
		_c.mutation.SetParams(v)
	}
	if _, ok := _c.mutation.TimeZone(); !ok {
		v := sysjob.DefaultTimeZone
		_c.mutation.SetTimeZone(v)
	}
	if _, ok := _c.mutation.MisfirePolicy(); !ok {
		v := sysjob.DefaultMisfirePolicy
		_c.mutation.SetMisfirePolicy(v)
	}
	if _, ok := _c.mutation.Concurrent(); !ok {
		v := sysjob.DefaultConcurrent
		_c.mutation.SetConcurrent(v)
	}
	if _, ok := _c.mutation.Timeout(); !ok {
		v := sysjob.DefaultTimeout
		_c.mutation.SetTimeout(v)
	}
	if _, ok := _c.mutation.MaxRetry(); !ok {
		v := sysjob.DefaultMaxRetry
		_c.mutation.SetMaxRetry(v)
	}
	if _, ok := _c.mutation.RetryInterval(); !ok {
		v := sysjob.DefaultRetryInterval
		_c.mutation.SetRetryInterval(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_c *SysJobCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SysJob.created_at"`)}
	}
	if _, ok := _c.mutation.CreatedID(); !ok {
		return &ValidationError{Name: "created_id", err: errors.New(`ent: missing required field "SysJob.created_id"`)}
	}
	if v, ok := _c.mutation.CreatedID(); ok {
		if err := sysjob.CreatedIDValidator(v); err != nil {
			return &ValidationError{Name: "created_id", err: fmt.Errorf(`ent: validator failed for field "SysJob.created_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "SysJob.created_by"`)}
	}
	if v, ok := _c.mutation.CreatedBy(); ok {
		if err := sysjob.CreatedByValidator(v); err != nil {
			return &ValidationError{Name: "created_by", err: fmt.Errorf(`ent: validator failed for field "SysJob.created_by": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SysJob.updated_at"`)}
	}
	if _, ok := _c.mutation.UpdatedID(); !ok {
		return &ValidationError{Name: "updated_id", err: errors.New(`ent: missing required field "SysJob.updated_id"`)}
	}
	if v, ok := _c.mutation.UpdatedID(); ok {
		if err := sysjob.UpdatedIDValidator(v); err != nil {
			return &ValidationError{Name: "updated_id", err: fmt.Errorf(`ent: validator failed for field "SysJob.updated_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpdatedBy(); !ok {
		return &ValidationError{Name: "updated_by", err: errors.New(`ent: missing required field "SysJob.updated_by"`)}
	}
	if v, ok := _c.mutation.UpdatedBy(); ok {
		if err := sysjob.UpdatedByValidator(v); err != nil {
			return &ValidationError{Name: "updated_by", err: fmt.Errorf(`ent: validator failed for field "SysJob.updated_by": %w`, err)}
		}
	}
	if v, ok := _c.mutation.DeletedBy(); ok {
		if err := sysjob.DeletedByValidator(v); err != nil {
			return &ValidationError{Name: "deleted_by", err: fmt.Errorf(`ent: validator failed for field "SysJob.deleted_by": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SysJob.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := sysjob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SysJob.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.Remark(); ok {
		if err := sysjob.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "SysJob.remark": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "SysJob.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := sysjob.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SysJob.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Group(); !ok {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required field "SysJob.group"`)}
	}
	if v, ok := _c.mutation.Group(); ok {
		if err := sysjob.GroupValidator(v); err != nil {
			return &ValidationError{Name: "group", err: fmt.Errorf(`ent: validator failed for field "SysJob.group": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Handler(); !ok {
		return &ValidationError{Name: "handler", err: errors.New(`ent: missing required field "SysJob.handler"`)}
	}
	if v, ok := _c.mutation.Handler(); ok {
		if err := sysjob.HandlerValidator(v); err != nil {
			return &ValidationError{Name: "handler", err: fmt.Errorf(`ent: validator failed for field "SysJob.handler": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Params(); !ok {
		return &ValidationError{Name: "params", err: errors.New(`ent: missing required field "SysJob.params"`)}
	}
	if _, ok := _c.mutation.CronExpression(); !ok {
		return &ValidationError{Name: "cron_expression", err: errors.New(`ent: missing required field "SysJob.cron_expression"`)}
	}
	if v, ok := _c.mutation.CronExpression(); ok {
		if err := sysjob.CronExpressionValidator(v); err != nil {
			return &ValidationError{Name: "cron_expression", err: fmt.Errorf(`ent: validator failed for field "SysJob.cron_expression": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TimeZone(); !ok {
		return &ValidationError{Name: "time_zone", err: errors.New(`ent: missing required field "SysJob.time_zone"`)}
	}
	if v, ok := _c.mutation.TimeZone(); ok {
		if err := sysjob.TimeZoneValidator(v); err != nil {
			return &ValidationError{Name: "time_zone", err: fmt.Errorf(`ent: validator failed for field "SysJob.time_zone": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MisfirePolicy(); !ok {
		return &ValidationError{Name: "misfire_policy", err: errors.New(`ent: missing required field "SysJob.misfire_policy"`)}
	}
	if v, ok := _c.mutation.MisfirePolicy(); ok {
		if err := sysjob.MisfirePolicyValidator(v); err != nil {
			return &ValidationError{Name: "misfire_policy", err: fmt.Errorf(`ent: validator failed for field "SysJob.misfire_policy": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Concurrent(); !ok {
		return &ValidationError{Name: "concurrent", err: errors.New(`ent: missing required field "SysJob.concurrent"`)}
	}
	if _, ok := _c.mutation.Timeout(); !ok {
		return &ValidationError{Name: "timeout", err: errors.New(`ent: missing required field "SysJob.timeout"`)}
	}
	if v, ok := _c.mutation.Timeout(); ok {
		if err := sysjob.TimeoutValidator(v); err != nil {
			return &ValidationError{Name: "timeout", err: fmt.Errorf(`ent: validator failed for field "SysJob.timeout": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MaxRetry(); !ok {
		return &ValidationError{Name: "max_retry", err: errors.New(`ent: missing required field "SysJob.max_retry"`)}
	}
	if v, ok := _c.mutation.MaxRetry(); ok {
		if err := sysjob.MaxRetryValidator(v); err != nil {
			return &ValidationError{Name: "max_retry", err: fmt.Errorf(`ent: validator failed for field "SysJob.max_retry": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RetryInterval(); !ok {
		return &ValidationError{Name: "retry_interval", err: errors.New(`ent: missing required field "SysJob.retry_interval"`)}
	}
	if v, ok := _c.mutation.RetryInterval(); ok {
		if err := sysjob.RetryIntervalValidator(v); err != nil {
			return &ValidationError{Name: "retry_interval", err: fmt.Errorf(`ent: validator failed for field "SysJob.retry_interval": %w`, err)}
		}
	}
	if v, ok := _c.mutation.LastStatus(); ok {
		if err := sysjob.LastStatusValidator(v); err != nil {
			return &ValidationError{Name: "last_status", err: fmt.Errorf(`ent: validator failed for field "SysJob.last_status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.LastError(); ok {
		if err := sysjob.LastErrorValidator(v); err != nil {
			return &ValidationError{Name: "last_error", err: fmt.Errorf(`ent: validator failed for field "SysJob.last_error": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := sysjob.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "SysJob.id": %w`, err)}
		}
	}
	return nil
}

func (_c *SysJobCreate) sqlSave(ctx context.Context) (*SysJob, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SysJobCreate) createSpec() (*SysJob, *sqlgraph.CreateSpec) {
	var (
		_node = &SysJob{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(sysjob.Table, sqlgraph.NewFieldSpec(sysjob.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(sysjob.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.CreatedID(); ok {
		_spec.SetField(sysjob.FieldCreatedID, field.TypeInt64, value)
		_node.CreatedID = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(sysjob.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(sysjob.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.UpdatedID(); ok {
		_spec.SetField(sysjob.FieldUpdatedID, field.TypeInt64, value)
		_node.UpdatedID = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(sysjob.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(sysjob.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = value
	}
	if value, ok := _c.mutation.DeletedID(); ok {
		_spec.SetField(sysjob.FieldDeletedID, field.TypeInt64, value)
		_node.DeletedID = value
	}
	if value, ok := _c.mutation.DeletedBy(); ok {
		_spec.SetField(sysjob.FieldDeletedBy, field.TypeString, value)
		_node.DeletedBy = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(sysjob.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Remark(); ok {
		_spec.SetField(sysjob.FieldRemark, field.TypeString, value)
		_node.Remark = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(sysjob.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Group(); ok {
		_spec.SetField(sysjob.FieldGroup, field.TypeString, value)
		_node.Group = value
	}
	if value, ok := _c.mutation.Handler(); ok {
		_spec.SetField(sysjob.FieldHandler, field.TypeString, value)
		_node.Handler = value
	}
	if value, ok := _c.mutation.Params(); ok {
		_spec.SetField(sysjob.FieldParams, field.TypeString, value)
		_node.Params = value
	}
	if value, ok := _c.mutation.CronExpression(); ok {
		_spec.SetField(sysjob.FieldCronExpression, field.TypeString, value)
		_node.CronExpression = value
	}
	if value, ok := _c.mutation.TimeZone(); ok {
		_spec.SetField(sysjob.FieldTimeZone, field.TypeString, value)
		_node.TimeZone = value
	}
	if value, ok := _c.mutation.MisfirePolicy(); ok {
		_spec.SetField(sysjob.FieldMisfirePolicy, field.TypeEnum, value)
		_node.MisfirePolicy = value
	}
	if value, ok := _c.mutation.Concurrent(); ok {
		_spec.SetField(sysjob.FieldConcurrent, field.TypeBool, value)
		_node.Concurrent = value
	}
	if value, ok := _c.mutation.Timeout(); ok {
		_spec.SetField(sysjob.FieldTimeout, field.TypeInt32, value)
		_node.Timeout = value
	}
	if value, ok := _c.mutation.MaxRetry(); ok {
		_spec.SetField(sysjob.FieldMaxRetry, field.TypeInt32, value)
		_node.MaxRetry = value
	}
	if value, ok := _c.mutation.RetryInterval(); ok {
		_spec.SetField(sysjob.FieldRetryInterval, field.TypeInt32, value)
		_node.RetryInterval = value
	}
	if value, ok := _c.mutation.NextRunAt(); ok {
		_spec.SetField(sysjob.FieldNextRunAt, field.TypeTime, value)
		_node.NextRunAt = value
	}
	if value, ok := _c.mutation.LastRunAt(); ok {
		_spec.SetField(sysjob.FieldLastRunAt, field.TypeTime, value)
		_node.LastRunAt = value
	}
	if value, ok := _c.mutation.LastStatus(); ok {
		_spec.SetField(sysjob.FieldLastStatus, field.TypeString, value)
		_node.LastStatus = value
	}
	if value, ok := _c.mutation.LastDuration(); ok {
		_spec.SetField(sysjob.FieldLastDuration, field.TypeInt64, value)
		_node.LastDuration = value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(sysjob.FieldLastError, field.TypeString, value)
		_node.LastError = value
	}
	return _node, _spec
}

// SysJobCreateBulk is the builder for creating many SysJob entities in bulk.
type SysJobCreateBulk struct {
	config
	err      error
	builders []*SysJobCreate
}

// Save creates the SysJob entities in the database.
func (_c *SysJobCreateBulk) Save(ctx context.Context) ([]*SysJob, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SysJob, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SysJobMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SysJobCreateBulk) SaveX(ctx context.Context) []*SysJob {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SysJobCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SysJobCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
