// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/saas-zero/saas-zero-job/ent/predicate"
	"github.com/saas-zero/saas-zero-job/ent/sysjob"
)

// SysJobUpdate is the builder for updating SysJob entities.
type SysJobUpdate struct {
	config
	hooks    []Hook
	mutation *SysJobMutation
}

// Where appends a list predicates to the SysJobUpdate builder.
func (_u *SysJobUpdate) Where(ps ...predicate.SysJob) *SysJobUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SysJobUpdate) SetUpdatedAt(v time.Time) *SysJobUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *SysJobUpdate) SetNillableUpdatedAt(v *time.Time) *SysJobUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetUpdatedID sets the "updated_id" field.
func (_u *SysJobUpdate) SetUpdatedID(v int64) *SysJobUpdate {
	_u.mutation.ResetUpdatedID()
	_u.mutation.SetUpdatedID(v)
	return _u
}

// SetNillableUpdatedID sets the "updated_id" field if the given value is not nil.
func (_u *SysJobUpdate) SetNillableUpdatedID(v *int64) *SysJobUpdate {
	if v != nil {
		_u.SetUpdatedID(*v)
	}
	return _u
}

// AddUpdatedID adds value to the "updated_id" field.
func (_u *SysJobUpdate) AddUpdatedID(v int64) *SysJobUpdate {
	_u.mutation.AddUpdatedID(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *SysJobUpdate) SetUpdatedBy(v string) *SysJobUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *SysJobUpdate) SetNillableUpdatedBy(v *string) *SysJobUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SysJobUpdate) SetDeletedAt(v time.Time) *SysJobUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SysJobUpdate) SetNillableDeletedAt(v *time.Time) *SysJobUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SysJobUpdate) ClearDeletedAt() *SysJobUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetDeletedID sets the "deleted_id" field.
func (_u *SysJobUpdate) SetDeletedID(v int64) *SysJobUpdate {
	_u.mutation.ResetDeletedID()
	_u.mutation.SetDeletedID(v)
	return _u
}

// SetNillableDeletedID sets the "deleted_id" field if the given value is not nil.
func (_u *SysJobUpdate) SetNillableDeletedID(v *int64) *SysJobUpdate {
	if v != nil {
		_u.SetDeletedID(*v)
	}
	return _u
}

// AddDeletedID adds value to the "deleted_id" field.
func (_u *SysJobUpdate) AddDeletedID(v int64) *SysJobUpdate {
	_u.mutation.AddDeletedID(v)
	return _u
}

// ClearDeletedID clears the value of the "deleted_id" field.
func (_u *SysJobUpdate) ClearDeletedID() *SysJobUpdate {
	_u.mutation.ClearDeletedID()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *SysJobUpdate) SetDeletedBy(v string) *SysJobUpdate {
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *SysJobUpdate) SetNillableDeletedBy(v *string) *SysJobUpdate {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *SysJobUpdate) ClearDeletedBy() *SysJobUpdate {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetStatus sets the "status" field.
func (_u *SysJobUpdate) SetStatus(v sysjob.Status) *SysJobUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SysJobUpdate) SetNillableStatus(v *sysjob.Status) *SysJobUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRemark sets the "remark" field.
func (_u *SysJobUpdate) SetRemark(v string) *SysJobUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *SysJobUpdate) SetNillableRemark(v *string) *SysJobUpdate {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *SysJobUpdate) ClearRemark() *SysJobUpdate {
	_u.mutation.ClearRemark()
	return _u
}

// SetName sets the "name" field.
func (_u *SysJobUpdate) SetName(v string) *SysJobUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SysJobUpdate) SetNillableName(v *string) *SysJobUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetGroup sets the "group" field.
func (_u *SysJobUpdate) SetGroup(v string) *SysJobUpdate {
	_u.mutation.SetGroup(v)
	return _u
}

// SetNillableGroup sets the "group" field if the given value is not nil.
func (_u *SysJobUpdate) SetNillableGroup(v *string) *SysJobUpdate {
	if v != nil {
		_u.SetGroup(*v)
	}
	return _u
}

// SetHandler sets the "handler" field.
func (_u *SysJobUpdate) SetHandler(v string) *SysJobUpdate {
	_u.mutation.SetHandler(v)
	return _u
}

// SetNillableHandler sets the "handler" field if the given value is not nil.
func (_u *SysJobUpdate) SetNillableHandler(v *string) *SysJobUpdate {
	if v != nil {
		_u.SetHandler(*v)
	}
	return _u
}

// SetParams sets the "params" field.
func (_u *SysJobUpdate) SetParams(v string) *SysJobUpdate {
	_u.mutation.SetParams(v)
	return _u
}

// SetNillableParams sets the "params" field if the given value is not nil.
func (_u *SysJobUpdate) SetNillableParams(v *string) *SysJobUpdate {
	if v != nil {
		_u.SetParams(*v)
	}
	return _u
}

// SetCronExpression sets the "cron_expression" field.
func (_u *SysJobUpdate) SetCronExpression(v string) *SysJobUpdate {
	_u.mutation.SetCronExpression(v)
	return _u
}

// SetNillableCronExpression sets the "cron_expression" field if the given value is not nil.
func (_u *SysJobUpdate) SetNillableCronExpression(v *string) *SysJobUpdate {
	if v != nil {
		_u.SetCronExpression(*v)
	}
	return _u
}

// SetTimeZone sets the "time_zone" field.
func (_u *SysJobUpdate) SetTimeZone(v string) *SysJobUpdate {
	_u.mutation.SetTimeZone(v)
	return _u
}

// SetNillableTimeZone sets the "time_zone" field if the given value is not nil.
func (_u *SysJobUpdate) SetNillableTimeZone(v *string) *SysJobUpdate {
	if v != nil {
		_u.SetTimeZone(*v)
	}
	return _u
}

// SetMisfirePolicy sets the "misfire_policy" field.
func (_u *SysJobUpdate) SetMisfirePolicy(v sysjob.MisfirePolicy) *SysJobUpdate {
	_u.mutation.SetMisfirePolicy(v)
	return _u
}

// SetNillableMisfirePolicy sets the "misfire_policy" field if the given value is not nil.
func (_u *SysJobUpdate) SetNillableMisfirePolicy(v *sysjob.MisfirePolicy) *SysJobUpdate {
	if v != nil {
		_u.SetMisfirePolicy(*v)
	}
	return _u
}

// SetConcurrent sets the "concurrent" field.
func (_u *SysJobUpdate) SetConcurrent(v bool) *SysJobUpdate {
	_u.mutation.SetConcurrent(v)
	return _u
}

// SetNillableConcurrent sets the "concurrent" field if the given value is not nil.
func (_u *SysJobUpdate) SetNillableConcurrent(v *bool) *SysJobUpdate {
	if v != nil {
		_u.SetConcurrent(*v)
	}
	return _u
}

// SetTimeout sets the "timeout" field.
func (_u *SysJobUpdate) SetTimeout(v int32) *SysJobUpdate {
	_u.mutation.ResetTimeout()
	_u.mutation.SetTimeout(v)
	return _u
}

// SetNillableTimeout sets the "timeout" field if the given value is not nil.
func (_u *SysJobUpdate) SetNillableTimeout(v *int32) *SysJobUpdate {
	if v != nil {
		_u.SetTimeout(*v)
	}
	return _u
}

// AddTimeout adds value to the "timeout" field.
func (_u *SysJobUpdate) AddTimeout(v int32) *SysJobUpdate {
	_u.mutation.AddTimeout(v)
	return _u
}

// SetMaxRetry sets the "max_retry" field.
func (_u *SysJobUpdate) SetMaxRetry(v int32) *SysJobUpdate {
	_u.mutation.ResetMaxRetry()
	_u.mutation.SetMaxRetry(v)
	return _u
}

// SetNillableMaxRetry sets the "max_retry" field if the given value is not nil.
func (_u *SysJobUpdate) SetNillableMaxRetry(v *int32) *SysJobUpdate {
	if v != nil {
		_u.SetMaxRetry(*v)
	}
	return _u
}

// AddMaxRetry adds value to the "max_retry" field.
func (_u *SysJobUpdate) AddMaxRetry(v int32) *SysJobUpdate {
	_u.mutation.AddMaxRetry(v)
	return _u
}

// SetRetryInterval sets the "retry_interval" field.
func (_u *SysJobUpdate) SetRetryInterval(v int32) *SysJobUpdate {
	_u.mutation.ResetRetryInterval()
	_u.mutation.SetRetryInterval(v)
	return _u
}

// SetNillableRetryInterval sets the "retry_interval" field if the given value is not nil.
func (_u *SysJobUpdate) SetNillableRetryInterval(v *int32) *SysJobUpdate {
	if v != nil {
		_u.SetRetryInterval(*v)
	}
	return _u
}

// AddRetryInterval adds value to the "retry_interval" field.
func (_u *SysJobUpdate) AddRetryInterval(v int32) *SysJobUpdate {
	_u.mutation.AddRetryInterval(v)
	return _u
}

// SetNextRunAt sets the "next_run_at" field.
func (_u *SysJobUpdate) SetNextRunAt(v time.Time) *SysJobUpdate {
	_u.mutation.SetNextRunAt(v)
	return _u
}

// SetNillableNextRunAt sets the "next_run_at" field if the given value is not nil.
func (_u *SysJobUpdate) SetNillableNextRunAt(v *time.Time) *SysJobUpdate {
	if v != nil {
		_u.SetNextRunAt(*v)
	}
	return _u
}

// ClearNextRunAt clears the value of the "next_run_at" field.
func (_u *SysJobUpdate) ClearNextRunAt() *SysJobUpdate {
	_u.mutation.ClearNextRunAt()
	return _u
}

// SetLastRunAt sets the "last_run_at" field.
func (_u *SysJobUpdate) SetLastRunAt(v time.Time) *SysJobUpdate {
	_u.mutation.SetLastRunAt(v)
	return _u
}

// SetNillableLastRunAt sets the "last_run_at" field if the given value is not nil.
func (_u *SysJobUpdate) SetNillableLastRunAt(v *time.Time) *SysJobUpdate {
	if v != nil {
		_u.SetLastRunAt(*v)
	}
	return _u
}

// ClearLastRunAt clears the value of the "last_run_at" field.
func (_u *SysJobUpdate) ClearLastRunAt() *SysJobUpdate {
	_u.mutation.ClearLastRunAt()
	return _u
}

// SetLastStatus sets the "last_status" field.
func (_u *SysJobUpdate) SetLastStatus(v string) *SysJobUpdate {
	_u.mutation.SetLastStatus(v)
	return _u
}

// SetNillableLastStatus sets the "last_status" field if the given value is not nil.
func (_u *SysJobUpdate) SetNillableLastStatus(v *string) *SysJobUpdate {
	if v != nil {
		_u.SetLastStatus(*v)
	}
	return _u
}

// ClearLastStatus clears the value of the "last_status" field.
func (_u *SysJobUpdate) ClearLastStatus() *SysJobUpdate {
	_u.mutation.ClearLastStatus()
	return _u
}

// SetLastDuration sets the "last_duration" field.
func (_u *SysJobUpdate) SetLastDuration(v int64) *SysJobUpdate {
	_u.mutation.ResetLastDuration()
	_u.mutation.SetLastDuration(v)
	return _u
}

// SetNillableLastDuration sets the "last_duration" field if the given value is not nil.
func (_u *SysJobUpdate) SetNillableLastDuration(v *int64) *SysJobUpdate {
	if v != nil {
		_u.SetLastDuration(*v)
	}
	return _u
}

// AddLastDuration adds value to the "last_duration" field.
func (_u *SysJobUpdate) AddLastDuration(v int64) *SysJobUpdate {
	_u.mutation.AddLastDuration(v)
	return _u
}

// ClearLastDuration clears the value of the "last_duration" field.
func (_u *SysJobUpdate) ClearLastDuration() *SysJobUpdate {
	_u.mutation.ClearLastDuration()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *SysJobUpdate) SetLastError(v string) *SysJobUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *SysJobUpdate) SetNillableLastError(v *string) *SysJobUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *SysJobUpdate) ClearLastError() *SysJobUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// Mutation returns the SysJobMutation object of the builder.
func (_u *SysJobUpdate) Mutation() *SysJobMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SysJobUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SysJobUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SysJobUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SysJobUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SysJobUpdate) check() error {
	if v, ok := _u.mutation.UpdatedID(); ok {
		if err := sysjob.UpdatedIDValidator(v); err != nil {
			return &ValidationError{Name: "updated_id", err: fmt.Errorf(`ent: validator failed for field "SysJob.updated_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpdatedBy(); ok {
		if err := sysjob.UpdatedByValidator(v); err != nil {
			return &ValidationError{Name: "updated_by", err: fmt.Errorf(`ent: validator failed for field "SysJob.updated_by": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeletedBy(); ok {
		if err := sysjob.DeletedByValidator(v); err != nil {
			return &ValidationError{Name: "deleted_by", err: fmt.Errorf(`ent: validator failed for field "SysJob.deleted_by": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := sysjob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SysJob.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Remark(); ok {
		if err := sysjob.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "SysJob.remark": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := sysjob.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SysJob.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Group(); ok {
		if err := sysjob.GroupValidator(v); err != nil {
			return &ValidationError{Name: "group", err: fmt.Errorf(`ent: validator failed for field "SysJob.group": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Handler(); ok {
		if err := sysjob.HandlerValidator(v); err != nil {
			return &ValidationError{Name: "handler", err: fmt.Errorf(`ent: validator failed for field "SysJob.handler": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CronExpression(); ok {
		if err := sysjob.CronExpressionValidator(v); err != nil {
			return &ValidationError{Name: "cron_expression", err: fmt.Errorf(`ent: validator failed for field "SysJob.cron_expression": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TimeZone(); ok {
		if err := sysjob.TimeZoneValidator(v); err != nil {
			return &ValidationError{Name: "time_zone", err: fmt.Errorf(`ent: validator failed for field "SysJob.time_zone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MisfirePolicy(); ok {
		if err := sysjob.MisfirePolicyValidator(v); err != nil {
			return &ValidationError{Name: "misfire_policy", err: fmt.Errorf(`ent: validator failed for field "SysJob.misfire_policy": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Timeout(); ok {
		if err := sysjob.TimeoutValidator(v); err != nil {
			return &ValidationError{Name: "timeout", err: fmt.Errorf(`ent: validator failed for field "SysJob.timeout": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxRetry(); ok {
		if err := sysjob.MaxRetryValidator(v); err != nil {
			return &ValidationError{Name: "max_retry", err: fmt.Errorf(`ent: validator failed for field "SysJob.max_retry": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RetryInterval(); ok {
		if err := sysjob.RetryIntervalValidator(v); err != nil {
			return &ValidationError{Name: "retry_interval", err: fmt.Errorf(`ent: validator failed for field "SysJob.retry_interval": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastStatus(); ok {
		if err := sysjob.LastStatusValidator(v); err != nil {
			return &ValidationError{Name: "last_status", err: fmt.Errorf(`ent: validator failed for field "SysJob.last_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastError(); ok {
		if err := sysjob.LastErrorValidator(v); err != nil {
			return &ValidationError{Name: "last_error", err: fmt.Errorf(`ent: validator failed for field "SysJob.last_error": %w`, err)}
		}
	}
	return nil
}

func (_u *SysJobUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sysjob.Table, sysjob.Columns, sqlgraph.NewFieldSpec(sysjob.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sysjob.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedID(); ok {
		_spec.SetField(sysjob.FieldUpdatedID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedID(); ok {
		_spec.AddField(sysjob.FieldUpdatedID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(sysjob.FieldUpdatedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(sysjob.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(sysjob.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedID(); ok {
		_spec.SetField(sysjob.FieldDeletedID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDeletedID(); ok {
		_spec.AddField(sysjob.FieldDeletedID, field.TypeInt64, value)
	}
	if _u.mutation.DeletedIDCleared() {
		_spec.ClearField(sysjob.FieldDeletedID, field.TypeInt64)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(sysjob.FieldDeletedBy, field.TypeString, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(sysjob.FieldDeletedBy, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(sysjob.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(sysjob.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(sysjob.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(sysjob.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Group(); ok {
		_spec.SetField(sysjob.FieldGroup, field.TypeString, value)
	}
	if value, ok := _u.mutation.Handler(); ok {
		_spec.SetField(sysjob.FieldHandler, field.TypeString, value)
	}
	if value, ok := _u.mutation.Params(); ok {
		_spec.SetField(sysjob.FieldParams, field.TypeString, value)
	}
	if value, ok := _u.mutation.CronExpression(); ok {
		_spec.SetField(sysjob.FieldCronExpression, field.TypeString, value)
	}
	if value, ok := _u.mutation.TimeZone(); ok {
		_spec.SetField(sysjob.FieldTimeZone, field.TypeString, value)
	}
	if value, ok := _u.mutation.MisfirePolicy(); ok {
		_spec.SetField(sysjob.FieldMisfirePolicy, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Concurrent(); ok {
		_spec.SetField(sysjob.FieldConcurrent, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Timeout(); ok {
		_spec.SetField(sysjob.FieldTimeout, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedTimeout(); ok {
		_spec.AddField(sysjob.FieldTimeout, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.MaxRetry(); ok {
		_spec.SetField(sysjob.FieldMaxRetry, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedMaxRetry(); ok {
		_spec.AddField(sysjob.FieldMaxRetry, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.RetryInterval(); ok {
		_spec.SetField(sysjob.FieldRetryInterval, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedRetryInterval(); ok {
		_spec.AddField(sysjob.FieldRetryInterval, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.NextRunAt(); ok {
		_spec.SetField(sysjob.FieldNextRunAt, field.TypeTime, value)
	}
	if _u.mutation.NextRunAtCleared() {
		_spec.ClearField(sysjob.FieldNextRunAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastRunAt(); ok {
		_spec.SetField(sysjob.FieldLastRunAt, field.TypeTime, value)
	}
	if _u.mutation.LastRunAtCleared() {
		_spec.ClearField(sysjob.FieldLastRunAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastStatus(); ok {
		_spec.SetField(sysjob.FieldLastStatus, field.TypeString, value)
	}
	if _u.mutation.LastStatusCleared() {
		_spec.ClearField(sysjob.FieldLastStatus, field.TypeString)
	}
	if value, ok := _u.mutation.LastDuration(); ok {
		_spec.SetField(sysjob.FieldLastDuration, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastDuration(); ok {
		_spec.AddField(sysjob.FieldLastDuration, field.TypeInt64, value)
	}
	if _u.mutation.LastDurationCleared() {
		_spec.ClearField(sysjob.FieldLastDuration, field.TypeInt64)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(sysjob.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(sysjob.FieldLastError, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sysjob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SysJobUpdateOne is the builder for updating a single SysJob entity.
type SysJobUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SysJobMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SysJobUpdateOne) SetUpdatedAt(v time.Time) *SysJobUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *SysJobUpdateOne) SetNillableUpdatedAt(v *time.Time) *SysJobUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// SetUpdatedID sets the "updated_id" field.
func (_u *SysJobUpdateOne) SetUpdatedID(v int64) *SysJobUpdateOne {
	_u.mutation.ResetUpdatedID()
	_u.mutation.SetUpdatedID(v)
	return _u
}

// SetNillableUpdatedID sets the "updated_id" field if the given value is not nil.
func (_u *SysJobUpdateOne) SetNillableUpdatedID(v *int64) *SysJobUpdateOne {
	if v != nil {
		_u.SetUpdatedID(*v)
	}
	return _u
}

// AddUpdatedID adds value to the "updated_id" field.
func (_u *SysJobUpdateOne) AddUpdatedID(v int64) *SysJobUpdateOne {
	_u.mutation.AddUpdatedID(v)
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *SysJobUpdateOne) SetUpdatedBy(v string) *SysJobUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *SysJobUpdateOne) SetNillableUpdatedBy(v *string) *SysJobUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SysJobUpdateOne) SetDeletedAt(v time.Time) *SysJobUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SysJobUpdateOne) SetNillableDeletedAt(v *time.Time) *SysJobUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SysJobUpdateOne) ClearDeletedAt() *SysJobUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetDeletedID sets the "deleted_id" field.
func (_u *SysJobUpdateOne) SetDeletedID(v int64) *SysJobUpdateOne {
	_u.mutation.ResetDeletedID()
	_u.mutation.SetDeletedID(v)
	return _u
}

// SetNillableDeletedID sets the "deleted_id" field if the given value is not nil.
func (_u *SysJobUpdateOne) SetNillableDeletedID(v *int64) *SysJobUpdateOne {
	if v != nil {
		_u.SetDeletedID(*v)
	}
	return _u
}

// AddDeletedID adds value to the "deleted_id" field.
func (_u *SysJobUpdateOne) AddDeletedID(v int64) *SysJobUpdateOne {
	_u.mutation.AddDeletedID(v)
	return _u
}

// ClearDeletedID clears the value of the "deleted_id" field.
func (_u *SysJobUpdateOne) ClearDeletedID() *SysJobUpdateOne {
	_u.mutation.ClearDeletedID()
	return _u
}

// SetDeletedBy sets the "deleted_by" field.
func (_u *SysJobUpdateOne) SetDeletedBy(v string) *SysJobUpdateOne {
	_u.mutation.SetDeletedBy(v)
	return _u
}

// SetNillableDeletedBy sets the "deleted_by" field if the given value is not nil.
func (_u *SysJobUpdateOne) SetNillableDeletedBy(v *string) *SysJobUpdateOne {
	if v != nil {
		_u.SetDeletedBy(*v)
	}
	return _u
}

// ClearDeletedBy clears the value of the "deleted_by" field.
func (_u *SysJobUpdateOne) ClearDeletedBy() *SysJobUpdateOne {
	_u.mutation.ClearDeletedBy()
	return _u
}

// SetStatus sets the "status" field.
func (_u *SysJobUpdateOne) SetStatus(v sysjob.Status) *SysJobUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SysJobUpdateOne) SetNillableStatus(v *sysjob.Status) *SysJobUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRemark sets the "remark" field.
func (_u *SysJobUpdateOne) SetRemark(v string) *SysJobUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *SysJobUpdateOne) SetNillableRemark(v *string) *SysJobUpdateOne {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *SysJobUpdateOne) ClearRemark() *SysJobUpdateOne {
	_u.mutation.ClearRemark()
	return _u
}

// SetName sets the "name" field.
func (_u *SysJobUpdateOne) SetName(v string) *SysJobUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SysJobUpdateOne) SetNillableName(v *string) *SysJobUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetGroup sets the "group" field.
func (_u *SysJobUpdateOne) SetGroup(v string) *SysJobUpdateOne {
	_u.mutation.SetGroup(v)
	return _u
}

// SetNillableGroup sets the "group" field if the given value is not nil.
func (_u *SysJobUpdateOne) SetNillableGroup(v *string) *SysJobUpdateOne {
	if v != nil {
		_u.SetGroup(*v)
	}
	return _u
}

// SetHandler sets the "handler" field.
func (_u *SysJobUpdateOne) SetHandler(v string) *SysJobUpdateOne {
	_u.mutation.SetHandler(v)
	return _u
}

// SetNillableHandler sets the "handler" field if the given value is not nil.
func (_u *SysJobUpdateOne) SetNillableHandler(v *string) *SysJobUpdateOne {
	if v != nil {
		_u.SetHandler(*v)
	}
	return _u
}

// SetParams sets the "params" field.
func (_u *SysJobUpdateOne) SetParams(v string) *SysJobUpdateOne {
	_u.mutation.SetParams(v)
	return _u
}

// SetNillableParams sets the "params" field if the given value is not nil.
func (_u *SysJobUpdateOne) SetNillableParams(v *string) *SysJobUpdateOne {
	if v != nil {
		_u.SetParams(*v)
	}
	return _u
}

// SetCronExpression sets the "cron_expression" field.
func (_u *SysJobUpdateOne) SetCronExpression(v string) *SysJobUpdateOne {
	_u.mutation.SetCronExpression(v)
	return _u
}

// SetNillableCronExpression sets the "cron_expression" field if the given value is not nil.
func (_u *SysJobUpdateOne) SetNillableCronExpression(v *string) *SysJobUpdateOne {
	if v != nil {
		_u.SetCronExpression(*v)
	}
	return _u
}

// SetTimeZone sets the "time_zone" field.
func (_u *SysJobUpdateOne) SetTimeZone(v string) *SysJobUpdateOne {
	_u.mutation.SetTimeZone(v)
	return _u
}

// SetNillableTimeZone sets the "time_zone" field if the given value is not nil.
func (_u *SysJobUpdateOne) SetNillableTimeZone(v *string) *SysJobUpdateOne {
	if v != nil {
		_u.SetTimeZone(*v)
	}
	return _u
}

// SetMisfirePolicy sets the "misfire_policy" field.
func (_u *SysJobUpdateOne) SetMisfirePolicy(v sysjob.MisfirePolicy) *SysJobUpdateOne {
	_u.mutation.SetMisfirePolicy(v)
	return _u
}

// SetNillableMisfirePolicy sets the "misfire_policy" field if the given value is not nil.
func (_u *SysJobUpdateOne) SetNillableMisfirePolicy(v *sysjob.MisfirePolicy) *SysJobUpdateOne {
	if v != nil {
		_u.SetMisfirePolicy(*v)
	}
	return _u
}

// SetConcurrent sets the "concurrent" field.
func (_u *SysJobUpdateOne) SetConcurrent(v bool) *SysJobUpdateOne {
	_u.mutation.SetConcurrent(v)
	return _u
}

// SetNillableConcurrent sets the "concurrent" field if the given value is not nil.
func (_u *SysJobUpdateOne) SetNillableConcurrent(v *bool) *SysJobUpdateOne {
	if v != nil {
		_u.SetConcurrent(*v)
	}
	return _u
}

// SetTimeout sets the "timeout" field.
func (_u *SysJobUpdateOne) SetTimeout(v int32) *SysJobUpdateOne {
	_u.mutation.ResetTimeout()
	_u.mutation.SetTimeout(v)
	return _u
}

// SetNillableTimeout sets the "timeout" field if the given value is not nil.
func (_u *SysJobUpdateOne) SetNillableTimeout(v *int32) *SysJobUpdateOne {
	if v != nil {
		_u.SetTimeout(*v)
	}
	return _u
}

// AddTimeout adds value to the "timeout" field.
func (_u *SysJobUpdateOne) AddTimeout(v int32) *SysJobUpdateOne {
	_u.mutation.AddTimeout(v)
	return _u
}

// SetMaxRetry sets the "max_retry" field.
func (_u *SysJobUpdateOne) SetMaxRetry(v int32) *SysJobUpdateOne {
	_u.mutation.ResetMaxRetry()
	_u.mutation.SetMaxRetry(v)
	return _u
}

// SetNillableMaxRetry sets the "max_retry" field if the given value is not nil.
func (_u *SysJobUpdateOne) SetNillableMaxRetry(v *int32) *SysJobUpdateOne {
	if v != nil {
		_u.SetMaxRetry(*v)
	}
	return _u
}

// AddMaxRetry adds value to the "max_retry" field.
func (_u *SysJobUpdateOne) AddMaxRetry(v int32) *SysJobUpdateOne {
	_u.mutation.AddMaxRetry(v)
	return _u
}

// SetRetryInterval sets the "retry_interval" field.
func (_u *SysJobUpdateOne) SetRetryInterval(v int32) *SysJobUpdateOne {
	_u.mutation.ResetRetryInterval()
	_u.mutation.SetRetryInterval(v)
	return _u
}

// SetNillableRetryInterval sets the "retry_interval" field if the given value is not nil.
func (_u *SysJobUpdateOne) SetNillableRetryInterval(v *int32) *SysJobUpdateOne {
	if v != nil {
		_u.SetRetryInterval(*v)
	}
	return _u
}

// AddRetryInterval adds value to the "retry_interval" field.
func (_u *SysJobUpdateOne) AddRetryInterval(v int32) *SysJobUpdateOne {
	_u.mutation.AddRetryInterval(v)
	return _u
}

// SetNextRunAt sets the "next_run_at" field.
func (_u *SysJobUpdateOne) SetNextRunAt(v time.Time) *SysJobUpdateOne {
	_u.mutation.SetNextRunAt(v)
	return _u
}

// SetNillableNextRunAt sets the "next_run_at" field if the given value is not nil.
func (_u *SysJobUpdateOne) SetNillableNextRunAt(v *time.Time) *SysJobUpdateOne {
	if v != nil {
		_u.SetNextRunAt(*v)
	}
	return _u
}

// ClearNextRunAt clears the value of the "next_run_at" field.
func (_u *SysJobUpdateOne) ClearNextRunAt() *SysJobUpdateOne {
	_u.mutation.ClearNextRunAt()
	return _u
}

// SetLastRunAt sets the "last_run_at" field.
func (_u *SysJobUpdateOne) SetLastRunAt(v time.Time) *SysJobUpdateOne {
	_u.mutation.SetLastRunAt(v)
	return _u
}

// SetNillableLastRunAt sets the "last_run_at" field if the given value is not nil.
func (_u *SysJobUpdateOne) SetNillableLastRunAt(v *time.Time) *SysJobUpdateOne {
	if v != nil {
		_u.SetLastRunAt(*v)
	}
	return _u
}

// ClearLastRunAt clears the value of the "last_run_at" field.
func (_u *SysJobUpdateOne) ClearLastRunAt() *SysJobUpdateOne {
	_u.mutation.ClearLastRunAt()
	return _u
}

// SetLastStatus sets the "last_status" field.
func (_u *SysJobUpdateOne) SetLastStatus(v string) *SysJobUpdateOne {
	_u.mutation.SetLastStatus(v)
	return _u
}

// SetNillableLastStatus sets the "last_status" field if the given value is not nil.
func (_u *SysJobUpdateOne) SetNillableLastStatus(v *string) *SysJobUpdateOne {
	if v != nil {
		_u.SetLastStatus(*v)
	}
	return _u
}

// ClearLastStatus clears the value of the "last_status" field.
func (_u *SysJobUpdateOne) ClearLastStatus() *SysJobUpdateOne {
	_u.mutation.ClearLastStatus()
	return _u
}

// SetLastDuration sets the "last_duration" field.
func (_u *SysJobUpdateOne) SetLastDuration(v int64) *SysJobUpdateOne {
	_u.mutation.ResetLastDuration()
	_u.mutation.SetLastDuration(v)
	return _u
}

// SetNillableLastDuration sets the "last_duration" field if the given value is not nil.
func (_u *SysJobUpdateOne) SetNillableLastDuration(v *int64) *SysJobUpdateOne {
	if v != nil {
		_u.SetLastDuration(*v)
	}
	return _u
}

// AddLastDuration adds value to the "last_duration" field.
func (_u *SysJobUpdateOne) AddLastDuration(v int64) *SysJobUpdateOne {
	_u.mutation.AddLastDuration(v)
	return _u
}

// ClearLastDuration clears the value of the "last_duration" field.
func (_u *SysJobUpdateOne) ClearLastDuration() *SysJobUpdateOne {
	_u.mutation.ClearLastDuration()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *SysJobUpdateOne) SetLastError(v string) *SysJobUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *SysJobUpdateOne) SetNillableLastError(v *string) *SysJobUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *SysJobUpdateOne) ClearLastError() *SysJobUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// Mutation returns the SysJobMutation object of the builder.
func (_u *SysJobUpdateOne) Mutation() *SysJobMutation {
	return _u.mutation
}

// Where appends a list predicates to the SysJobUpdate builder.
func (_u *SysJobUpdateOne) Where(ps ...predicate.SysJob) *SysJobUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SysJobUpdateOne) Select(field string, fields ...string) *SysJobUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SysJob entity.
func (_u *SysJobUpdateOne) Save(ctx context.Context) (*SysJob, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SysJobUpdateOne) SaveX(ctx context.Context) *SysJob {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SysJobUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SysJobUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SysJobUpdateOne) check() error {
	if v, ok := _u.mutation.UpdatedID(); ok {
		if err := sysjob.UpdatedIDValidator(v); err != nil {
			return &ValidationError{Name: "updated_id", err: fmt.Errorf(`ent: validator failed for field "SysJob.updated_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UpdatedBy(); ok {
		if err := sysjob.UpdatedByValidator(v); err != nil {
			return &ValidationError{Name: "updated_by", err: fmt.Errorf(`ent: validator failed for field "SysJob.updated_by": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DeletedBy(); ok {
		if err := sysjob.DeletedByValidator(v); err != nil {
			return &ValidationError{Name: "deleted_by", err: fmt.Errorf(`ent: validator failed for field "SysJob.deleted_by": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := sysjob.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SysJob.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Remark(); ok {
		if err := sysjob.RemarkValidator(v); err != nil {
			return &ValidationError{Name: "remark", err: fmt.Errorf(`ent: validator failed for field "SysJob.remark": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := sysjob.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SysJob.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Group(); ok {
		if err := sysjob.GroupValidator(v); err != nil {
			return &ValidationError{Name: "group", err: fmt.Errorf(`ent: validator failed for field "SysJob.group": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Handler(); ok {
		if err := sysjob.HandlerValidator(v); err != nil {
			return &ValidationError{Name: "handler", err: fmt.Errorf(`ent: validator failed for field "SysJob.handler": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CronExpression(); ok {
		if err := sysjob.CronExpressionValidator(v); err != nil {
			return &ValidationError{Name: "cron_expression", err: fmt.Errorf(`ent: validator failed for field "SysJob.cron_expression": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TimeZone(); ok {
		if err := sysjob.TimeZoneValidator(v); err != nil {
			return &ValidationError{Name: "time_zone", err: fmt.Errorf(`ent: validator failed for field "SysJob.time_zone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MisfirePolicy(); ok {
		if err := sysjob.MisfirePolicyValidator(v); err != nil {
			return &ValidationError{Name: "misfire_policy", err: fmt.Errorf(`ent: validator failed for field "SysJob.misfire_policy": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Timeout(); ok {
		if err := sysjob.TimeoutValidator(v); err != nil {
			return &ValidationError{Name: "timeout", err: fmt.Errorf(`ent: validator failed for field "SysJob.timeout": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxRetry(); ok {
		if err := sysjob.MaxRetryValidator(v); err != nil {
			return &ValidationError{Name: "max_retry", err: fmt.Errorf(`ent: validator failed for field "SysJob.max_retry": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RetryInterval(); ok {
		if err := sysjob.RetryIntervalValidator(v); err != nil {
			return &ValidationError{Name: "retry_interval", err: fmt.Errorf(`ent: validator failed for field "SysJob.retry_interval": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastStatus(); ok {
		if err := sysjob.LastStatusValidator(v); err != nil {
			return &ValidationError{Name: "last_status", err: fmt.Errorf(`ent: validator failed for field "SysJob.last_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastError(); ok {
		if err := sysjob.LastErrorValidator(v); err != nil {
			return &ValidationError{Name: "last_error", err: fmt.Errorf(`ent: validator failed for field "SysJob.last_error": %w`, err)}
		}
	}
	return nil
}

func (_u *SysJobUpdateOne) sqlSave(ctx context.Context) (_node *SysJob, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sysjob.Table, sysjob.Columns, sqlgraph.NewFieldSpec(sysjob.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SysJob.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sysjob.FieldID)
		for _, f := range fields {
			if !sysjob.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sysjob.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sysjob.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UpdatedID(); ok {
		_spec.SetField(sysjob.FieldUpdatedID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedID(); ok {
		_spec.AddField(sysjob.FieldUpdatedID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(sysjob.FieldUpdatedBy, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(sysjob.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(sysjob.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedID(); ok {
		_spec.SetField(sysjob.FieldDeletedID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDeletedID(); ok {
		_spec.AddField(sysjob.FieldDeletedID, field.TypeInt64, value)
	}
	if _u.mutation.DeletedIDCleared() {
		_spec.ClearField(sysjob.FieldDeletedID, field.TypeInt64)
	}
	if value, ok := _u.mutation.DeletedBy(); ok {
		_spec.SetField(sysjob.FieldDeletedBy, field.TypeString, value)
	}
	if _u.mutation.DeletedByCleared() {
		_spec.ClearField(sysjob.FieldDeletedBy, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(sysjob.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(sysjob.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(sysjob.FieldRemark, field.TypeString)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(sysjob.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Group(); ok {
		_spec.SetField(sysjob.FieldGroup, field.TypeString, value)
	}
	if value, ok := _u.mutation.Handler(); ok {
		_spec.SetField(sysjob.FieldHandler, field.TypeString, value)
	}
	if value, ok := _u.mutation.Params(); ok {
		_spec.SetField(sysjob.FieldParams, field.TypeString, value)
	}
	if value, ok := _u.mutation.CronExpression(); ok {
		_spec.SetField(sysjob.FieldCronExpression, field.TypeString, value)
	}
	if value, ok := _u.mutation.TimeZone(); ok {
		_spec.SetField(sysjob.FieldTimeZone, field.TypeString, value)
	}
	if value, ok := _u.mutation.MisfirePolicy(); ok {
		_spec.SetField(sysjob.FieldMisfirePolicy, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Concurrent(); ok {
		_spec.SetField(sysjob.FieldConcurrent, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Timeout(); ok {
		_spec.SetField(sysjob.FieldTimeout, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedTimeout(); ok {
		_spec.AddField(sysjob.FieldTimeout, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.MaxRetry(); ok {
		_spec.SetField(sysjob.FieldMaxRetry, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedMaxRetry(); ok {
		_spec.AddField(sysjob.FieldMaxRetry, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.RetryInterval(); ok {
		_spec.SetField(sysjob.FieldRetryInterval, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.AddedRetryInterval(); ok {
		_spec.AddField(sysjob.FieldRetryInterval, field.TypeInt32, value)
	}
	if value, ok := _u.mutation.NextRunAt(); ok {
		_spec.SetField(sysjob.FieldNextRunAt, field.TypeTime, value)
	}
	if _u.mutation.NextRunAtCleared() {
		_spec.ClearField(sysjob.FieldNextRunAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastRunAt(); ok {
		_spec.SetField(sysjob.FieldLastRunAt, field.TypeTime, value)
	}
	if _u.mutation.LastRunAtCleared() {
		_spec.ClearField(sysjob.FieldLastRunAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastStatus(); ok {
		_spec.SetField(sysjob.FieldLastStatus, field.TypeString, value)
	}
	if _u.mutation.LastStatusCleared() {
		_spec.ClearField(sysjob.FieldLastStatus, field.TypeString)
	}
	if value, ok := _u.mutation.LastDuration(); ok {
		_spec.SetField(sysjob.FieldLastDuration, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastDuration(); ok {
		_spec.AddField(sysjob.FieldLastDuration, field.TypeInt64, value)
	}
	if _u.mutation.LastDurationCleared() {
		_spec.ClearField(sysjob.FieldLastDuration, field.TypeInt64)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(sysjob.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(sysjob.FieldLastError, field.TypeString)
	}
	_node = &SysJob{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sysjob.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
