// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/saas-zero/saas-zero-job/ent/sysjob"
)

// job Table | 定时任务表
type SysJob struct {
	config `json:"-"`
	// ID of the ent.
	// Primary Key | 主键ID，可自定义雪花ID
	ID int64 `json:"id,omitempty"`
	// Create Time | 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Creator ID | 创建人ID
	CreatedID int64 `json:"created_id,omitempty"`
	// Creator Name | 创建人名称
	CreatedBy string `json:"created_by,omitempty"`
	// updated Time | 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// updated ID | 更新人ID
	UpdatedID int64 `json:"updated_id,omitempty"`
	// updated Name | 更新人名称
	UpdatedBy string `json:"updated_by,omitempty"`
	// deleted Time | 删除时间
	DeletedAt time.Time `json:"deleted_at,omitempty"`
	// deleted ID | 删除人ID，逻辑删除用
	DeletedID int64 `json:"deleted_id,omitempty"`
	// deleted Name | 删除人名称
	DeletedBy string `json:"deleted_by,omitempty"`
	// 状态：active-有效，inactive-无效，suspended-暂停
	Status sysjob.Status `json:"status,omitempty"`
	// Remark holds the value of the "remark" field.
	Remark string `json:"remark,omitempty"`
	// 任务名称 | Job Name
	Name string `json:"name,omitempty"`
	// 任务分组(字典 job_group) | Job Group
	Group string `json:"group,omitempty"`
	// 处理器注册码(代码注册表, 如 report.daily) | Handler Code
	Handler string `json:"handler,omitempty"`
	// 处理器参数(JSON) | Handler Params(JSON)
	Params string `json:"params,omitempty"`
	// cron表达式(兼容5/6位, 秒可选) | Cron Expression(5/6 fields, seconds optional)
	CronExpression string `json:"cron_expression,omitempty"`
	// 表达式时区 | Time Zone
	TimeZone string `json:"time_zone,omitempty"`
	// 错过执行策略: skip-放弃, fire_once-补跑一次, fire_all-全部补跑 | Misfire Policy
	MisfirePolicy sysjob.MisfirePolicy `json:"misfire_policy,omitempty"`
	// 是否允许并发执行(否-同一时刻只跑一次) | Allow Concurrent
	Concurrent bool `json:"concurrent,omitempty"`
	// 单次执行超时(秒) | Timeout(seconds)
	Timeout int32 `json:"timeout,omitempty"`
	// 失败重试次数 | Max Retry
	MaxRetry int32 `json:"max_retry,omitempty"`
	// 重试间隔(秒) | Retry Interval(seconds)
	RetryInterval int32 `json:"retry_interval,omitempty"`
	// 下次触发时间(调度器回写) | Next Run At
	NextRunAt time.Time `json:"next_run_at,omitempty"`
	// 上次触发时间 | Last Run At
	LastRunAt time.Time `json:"last_run_at,omitempty"`
	// 上次执行结果: success/fail/timeout/skipped/none | Last Status
	LastStatus string `json:"last_status,omitempty"`
	// 上次耗时(毫秒) | Last Duration(ms)
	LastDuration int64 `json:"last_duration,omitempty"`
	// 上次错误摘要 | Last Error
	LastError    string `json:"last_error,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SysJob) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case sysjob.FieldConcurrent:
			values[i] = new(sql.NullBool)
		case sysjob.FieldID, sysjob.FieldCreatedID, sysjob.FieldUpdatedID, sysjob.FieldDeletedID, sysjob.FieldTimeout, sysjob.FieldMaxRetry, sysjob.FieldRetryInterval, sysjob.FieldLastDuration:
			values[i] = new(sql.NullInt64)
		case sysjob.FieldCreatedBy, sysjob.FieldUpdatedBy, sysjob.FieldDeletedBy, sysjob.FieldStatus, sysjob.FieldRemark, sysjob.FieldName, sysjob.FieldGroup, sysjob.FieldHandler, sysjob.FieldParams, sysjob.FieldCronExpression, sysjob.FieldTimeZone, sysjob.FieldMisfirePolicy, sysjob.FieldLastStatus, sysjob.FieldLastError:
			values[i] = new(sql.NullString)
		case sysjob.FieldCreatedAt, sysjob.FieldUpdatedAt, sysjob.FieldDeletedAt, sysjob.FieldNextRunAt, sysjob.FieldLastRunAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SysJob fields.
func (_m *SysJob) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case sysjob.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case sysjob.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case sysjob.FieldCreatedID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_id", values[i])
			} else if value.Valid {
				_m.CreatedID = value.Int64
			}
		case sysjob.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				_m.CreatedBy = value.String
			}
		case sysjob.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case sysjob.FieldUpdatedID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_id", values[i])
			} else if value.Valid {
				_m.UpdatedID = value.Int64
			}
		case sysjob.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				_m.UpdatedBy = value.String
			}
		case sysjob.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = value.Time
			}
		case sysjob.FieldDeletedID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_id", values[i])
			} else if value.Valid {
				_m.DeletedID = value.Int64
			}
		case sysjob.FieldDeletedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_by", values[i])
			} else if value.Valid {
				_m.DeletedBy = value.String
			}
		case sysjob.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = sysjob.Status(value.String)
			}
		case sysjob.FieldRemark:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field remark", values[i])
			} else if value.Valid {
				_m.Remark = value.String
			}
		case sysjob.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case sysjob.FieldGroup:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field group", values[i])
			} else if value.Valid {
				_m.Group = value.String
			}
		case sysjob.FieldHandler:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field handler", values[i])
			} else if value.Valid {
				_m.Handler = value.String
			}
		case sysjob.FieldParams:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field params", values[i])
			} else if value.Valid {
				_m.Params = value.String
			}
		case sysjob.FieldCronExpression:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cron_expression", values[i])
			} else if value.Valid {
				_m.CronExpression = value.String
			}
		case sysjob.FieldTimeZone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field time_zone", values[i])
			} else if value.Valid {
				_m.TimeZone = value.String
			}
		case sysjob.FieldMisfirePolicy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field misfire_policy", values[i])
			} else if value.Valid {
				_m.MisfirePolicy = sysjob.MisfirePolicy(value.String)
			}
		case sysjob.FieldConcurrent:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field concurrent", values[i])
			} else if value.Valid {
				_m.Concurrent = value.Bool
			}
		case sysjob.FieldTimeout:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field timeout", values[i])
			} else if value.Valid {
				_m.Timeout = int32(value.Int64)
			}
		case sysjob.FieldMaxRetry:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_retry", values[i])
			} else if value.Valid {
				_m.MaxRetry = int32(value.Int64)
			}
		case sysjob.FieldRetryInterval:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field retry_interval", values[i])
			} else if value.Valid {
				_m.RetryInterval = int32(value.Int64)
			}
		case sysjob.FieldNextRunAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field next_run_at", values[i])
			} else if value.Valid {
				_m.NextRunAt = value.Time
			}
		case sysjob.FieldLastRunAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_run_at", values[i])
			} else if value.Valid {
				_m.LastRunAt = value.Time
			}
		case sysjob.FieldLastStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_status", values[i])
			} else if value.Valid {
				_m.LastStatus = value.String
			}
		case sysjob.FieldLastDuration:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field last_duration", values[i])
			} else if value.Valid {
				_m.LastDuration = value.Int64
			}
		case sysjob.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SysJob.
// This includes values selected through modifiers, order, etc.
func (_m *SysJob) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SysJob.
// Note that you need to call SysJob.Unwrap() before calling this method if this SysJob
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SysJob) Update() *SysJobUpdateOne {
	return NewSysJobClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SysJob entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SysJob) Unwrap() *SysJob {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SysJob is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SysJob) String() string {
	var builder strings.Builder
	builder.WriteString("SysJob(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("created_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedID))
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(_m.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpdatedID))
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(_m.UpdatedBy)
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(_m.DeletedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("deleted_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DeletedID))
	builder.WriteString(", ")
	builder.WriteString("deleted_by=")
	builder.WriteString(_m.DeletedBy)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("remark=")
	builder.WriteString(_m.Remark)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("group=")
	builder.WriteString(_m.Group)
	builder.WriteString(", ")
	builder.WriteString("handler=")
	builder.WriteString(_m.Handler)
	builder.WriteString(", ")
	builder.WriteString("params=")
	builder.WriteString(_m.Params)
	builder.WriteString(", ")
	builder.WriteString("cron_expression=")
	builder.WriteString(_m.CronExpression)
	builder.WriteString(", ")
	builder.WriteString("time_zone=")
	builder.WriteString(_m.TimeZone)
	builder.WriteString(", ")
	builder.WriteString("misfire_policy=")
	builder.WriteString(fmt.Sprintf("%v", _m.MisfirePolicy))
	builder.WriteString(", ")
	builder.WriteString("concurrent=")
	builder.WriteString(fmt.Sprintf("%v", _m.Concurrent))
	builder.WriteString(", ")
	builder.WriteString("timeout=")
	builder.WriteString(fmt.Sprintf("%v", _m.Timeout))
	builder.WriteString(", ")
	builder.WriteString("max_retry=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxRetry))
	builder.WriteString(", ")
	builder.WriteString("retry_interval=")
	builder.WriteString(fmt.Sprintf("%v", _m.RetryInterval))
	builder.WriteString(", ")
	builder.WriteString("next_run_at=")
	builder.WriteString(_m.NextRunAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last_run_at=")
	builder.WriteString(_m.LastRunAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last_status=")
	builder.WriteString(_m.LastStatus)
	builder.WriteString(", ")
	builder.WriteString("last_duration=")
	builder.WriteString(fmt.Sprintf("%v", _m.LastDuration))
	builder.WriteString(", ")
	builder.WriteString("last_error=")
	builder.WriteString(_m.LastError)
	builder.WriteByte(')')
	return builder.String()
}

// SysJobs is a parsable slice of SysJob.
type SysJobs []*SysJob
