// Code generated by ent, DO NOT EDIT.

package sysjoblog

import (
	"fmt"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the sysjoblog type in the database.
	Label = "sys_job_log"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldCreatedID holds the string denoting the created_id field in the database.
	FieldCreatedID = "created_id"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldJobID holds the string denoting the job_id field in the database.
	FieldJobID = "job_id"
	// FieldJobName holds the string denoting the job_name field in the database.
	FieldJobName = "job_name"
	// FieldJobGroup holds the string denoting the job_group field in the database.
	FieldJobGroup = "job_group"
	// FieldHandler holds the string denoting the handler field in the database.
	FieldHandler = "handler"
	// FieldTriggerType holds the string denoting the trigger_type field in the database.
	FieldTriggerType = "trigger_type"
	// FieldExecNode holds the string denoting the exec_node field in the database.
	FieldExecNode = "exec_node"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldAttempt holds the string denoting the attempt field in the database.
	FieldAttempt = "attempt"
	// FieldMessage holds the string denoting the message field in the database.
	FieldMessage = "message"
	// FieldExceptionInfo holds the string denoting the exception_info field in the database.
	FieldExceptionInfo = "exception_info"
	// FieldDuration holds the string denoting the duration field in the database.
	FieldDuration = "duration"
	// Table holds the table name of the sysjoblog in the database.
	Table = "sys_job_logs"
)

// Columns holds all SQL columns for sysjoblog fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldCreatedID,
	FieldCreatedBy,
	FieldJobID,
	FieldJobName,
	FieldJobGroup,
	FieldHandler,
	FieldTriggerType,
	FieldExecNode,
	FieldStatus,
	FieldAttempt,
	FieldMessage,
	FieldExceptionInfo,
	FieldDuration,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/saas-zero/saas-zero-job/ent/runtime"
var (
	Hooks [2]ent.Hook
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// CreatedIDValidator is a validator for the "created_id" field. It is called by the builders before save.
	CreatedIDValidator func(int64) error
	// CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	CreatedByValidator func(string) error
	// JobIDValidator is a validator for the "job_id" field. It is called by the builders before save.
	JobIDValidator func(int64) error
	// DefaultJobName holds the default value on creation for the "job_name" field.
	DefaultJobName string
	// JobNameValidator is a validator for the "job_name" field. It is called by the builders before save.
	JobNameValidator func(string) error
	// DefaultJobGroup holds the default value on creation for the "job_group" field.
	DefaultJobGroup string
	// JobGroupValidator is a validator for the "job_group" field. It is called by the builders before save.
	JobGroupValidator func(string) error
	// DefaultHandler holds the default value on creation for the "handler" field.
	DefaultHandler string
	// HandlerValidator is a validator for the "handler" field. It is called by the builders before save.
	HandlerValidator func(string) error
	// DefaultExecNode holds the default value on creation for the "exec_node" field.
	DefaultExecNode string
	// ExecNodeValidator is a validator for the "exec_node" field. It is called by the builders before save.
	ExecNodeValidator func(string) error
	// DefaultAttempt holds the default value on creation for the "attempt" field.
	DefaultAttempt int32
	// AttemptValidator is a validator for the "attempt" field. It is called by the builders before save.
	AttemptValidator func(int32) error
	// DefaultMessage holds the default value on creation for the "message" field.
	DefaultMessage string
	// MessageValidator is a validator for the "message" field. It is called by the builders before save.
	MessageValidator func(string) error
	// DefaultExceptionInfo holds the default value on creation for the "exception_info" field.
	DefaultExceptionInfo string
	// ExceptionInfoValidator is a validator for the "exception_info" field. It is called by the builders before save.
	ExceptionInfoValidator func(string) error
	// DefaultDuration holds the default value on creation for the "duration" field.
	DefaultDuration int64
	// DurationValidator is a validator for the "duration" field. It is called by the builders before save.
	DurationValidator func(int64) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int64) error
)

// TriggerType defines the type for the "trigger_type" enum field.
type TriggerType string

// TriggerTypeCron is the default value of the TriggerType enum.
const DefaultTriggerType = TriggerTypeCron

// TriggerType values.
const (
	TriggerTypeCron   TriggerType = "cron"
	TriggerTypeManual TriggerType = "manual"
	TriggerTypeRetry  TriggerType = "retry"
)

func (tt TriggerType) String() string {
	return string(tt)
}

// TriggerTypeValidator is a validator for the "trigger_type" field enum values. It is called by the builders before save.
func TriggerTypeValidator(tt TriggerType) error {
	switch tt {
	case TriggerTypeCron, TriggerTypeManual, TriggerTypeRetry:
		return nil
	default:
		return fmt.Errorf("sysjoblog: invalid enum value for trigger_type field: %q", tt)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusRunning is the default value of the Status enum.
const DefaultStatus = StatusRunning

// Status values.
const (
	StatusRunning Status = "running"
	StatusSuccess Status = "success"
	StatusFail    Status = "fail"
	StatusTimeout Status = "timeout"
	StatusSkipped Status = "skipped"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusRunning, StatusSuccess, StatusFail, StatusTimeout, StatusSkipped:
		return nil
	default:
		return fmt.Errorf("sysjoblog: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the SysJobLog queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByCreatedID orders the results by the created_id field.
func ByCreatedID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedID, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByJobID orders the results by the job_id field.
func ByJobID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJobID, opts...).ToFunc()
}

// ByJobName orders the results by the job_name field.
func ByJobName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJobName, opts...).ToFunc()
}

// ByJobGroup orders the results by the job_group field.
func ByJobGroup(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJobGroup, opts...).ToFunc()
}

// ByHandler orders the results by the handler field.
func ByHandler(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHandler, opts...).ToFunc()
}

// ByTriggerType orders the results by the trigger_type field.
func ByTriggerType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTriggerType, opts...).ToFunc()
}

// ByExecNode orders the results by the exec_node field.
func ByExecNode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExecNode, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByAttempt orders the results by the attempt field.
func ByAttempt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttempt, opts...).ToFunc()
}

// ByMessage orders the results by the message field.
func ByMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMessage, opts...).ToFunc()
}

// ByExceptionInfo orders the results by the exception_info field.
func ByExceptionInfo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExceptionInfo, opts...).ToFunc()
}

// ByDuration orders the results by the duration field.
func ByDuration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDuration, opts...).ToFunc()
}
