// Code generated by ent, DO NOT EDIT.

package sysjoblog

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/saas-zero/saas-zero-job/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedID applies equality check predicate on the "created_id" field. It's identical to CreatedIDEQ.
func CreatedID(v int64) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldEQ(FieldCreatedID, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldEQ(FieldCreatedBy, v))
}

// JobID applies equality check predicate on the "job_id" field. It's identical to JobIDEQ.
func JobID(v int64) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldEQ(FieldJobID, v))
}

// JobName applies equality check predicate on the "job_name" field. It's identical to JobNameEQ.
func JobName(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldEQ(FieldJobName, v))
}

// JobGroup applies equality check predicate on the "job_group" field. It's identical to JobGroupEQ.
func JobGroup(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldEQ(FieldJobGroup, v))
}

// Handler applies equality check predicate on the "handler" field. It's identical to HandlerEQ.
func Handler(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldEQ(FieldHandler, v))
}

// ExecNode applies equality check predicate on the "exec_node" field. It's identical to ExecNodeEQ.
func ExecNode(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldEQ(FieldExecNode, v))
}

// Attempt applies equality check predicate on the "attempt" field. It's identical to AttemptEQ.
func Attempt(v int32) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldEQ(FieldAttempt, v))
}

// Message applies equality check predicate on the "message" field. It's identical to MessageEQ.
func Message(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldEQ(FieldMessage, v))
}

// ExceptionInfo applies equality check predicate on the "exception_info" field. It's identical to ExceptionInfoEQ.
func ExceptionInfo(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldEQ(FieldExceptionInfo, v))
}

// Duration applies equality check predicate on the "duration" field. It's identical to DurationEQ.
func Duration(v int64) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldEQ(FieldDuration, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedIDEQ applies the EQ predicate on the "created_id" field.
func CreatedIDEQ(v int64) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldEQ(FieldCreatedID, v))
}

// CreatedIDNEQ applies the NEQ predicate on the "created_id" field.
func CreatedIDNEQ(v int64) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldNEQ(FieldCreatedID, v))
}

// CreatedIDIn applies the In predicate on the "created_id" field.
func CreatedIDIn(vs ...int64) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldIn(FieldCreatedID, vs...))
}

// CreatedIDNotIn applies the NotIn predicate on the "created_id" field.
func CreatedIDNotIn(vs ...int64) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldNotIn(FieldCreatedID, vs...))
}

// CreatedIDGT applies the GT predicate on the "created_id" field.
func CreatedIDGT(v int64) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldGT(FieldCreatedID, v))
}

// CreatedIDGTE applies the GTE predicate on the "created_id" field.
func CreatedIDGTE(v int64) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldGTE(FieldCreatedID, v))
}

// CreatedIDLT applies the LT predicate on the "created_id" field.
func CreatedIDLT(v int64) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldLT(FieldCreatedID, v))
}

// CreatedIDLTE applies the LTE predicate on the "created_id" field.
func CreatedIDLTE(v int64) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldLTE(FieldCreatedID, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldContainsFold(FieldCreatedBy, v))
}

// JobIDEQ applies the EQ predicate on the "job_id" field.
func JobIDEQ(v int64) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldEQ(FieldJobID, v))
}

// JobIDNEQ applies the NEQ predicate on the "job_id" field.
func JobIDNEQ(v int64) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldNEQ(FieldJobID, v))
}

// JobIDIn applies the In predicate on the "job_id" field.
func JobIDIn(vs ...int64) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldIn(FieldJobID, vs...))
}

// JobIDNotIn applies the NotIn predicate on the "job_id" field.
func JobIDNotIn(vs ...int64) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldNotIn(FieldJobID, vs...))
}

// JobIDGT applies the GT predicate on the "job_id" field.
func JobIDGT(v int64) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldGT(FieldJobID, v))
}

// JobIDGTE applies the GTE predicate on the "job_id" field.
func JobIDGTE(v int64) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldGTE(FieldJobID, v))
}

// JobIDLT applies the LT predicate on the "job_id" field.
func JobIDLT(v int64) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldLT(FieldJobID, v))
}

// JobIDLTE applies the LTE predicate on the "job_id" field.
func JobIDLTE(v int64) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldLTE(FieldJobID, v))
}

// JobNameEQ applies the EQ predicate on the "job_name" field.
func JobNameEQ(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldEQ(FieldJobName, v))
}

// JobNameNEQ applies the NEQ predicate on the "job_name" field.
func JobNameNEQ(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldNEQ(FieldJobName, v))
}

// JobNameIn applies the In predicate on the "job_name" field.
func JobNameIn(vs ...string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldIn(FieldJobName, vs...))
}

// JobNameNotIn applies the NotIn predicate on the "job_name" field.
func JobNameNotIn(vs ...string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldNotIn(FieldJobName, vs...))
}

// JobNameGT applies the GT predicate on the "job_name" field.
func JobNameGT(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldGT(FieldJobName, v))
}

// JobNameGTE applies the GTE predicate on the "job_name" field.
func JobNameGTE(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldGTE(FieldJobName, v))
}

// JobNameLT applies the LT predicate on the "job_name" field.
func JobNameLT(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldLT(FieldJobName, v))
}

// JobNameLTE applies the LTE predicate on the "job_name" field.
func JobNameLTE(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldLTE(FieldJobName, v))
}

// JobNameContains applies the Contains predicate on the "job_name" field.
func JobNameContains(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldContains(FieldJobName, v))
}

// JobNameHasPrefix applies the HasPrefix predicate on the "job_name" field.
func JobNameHasPrefix(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldHasPrefix(FieldJobName, v))
}

// JobNameHasSuffix applies the HasSuffix predicate on the "job_name" field.
func JobNameHasSuffix(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldHasSuffix(FieldJobName, v))
}

// JobNameEqualFold applies the EqualFold predicate on the "job_name" field.
func JobNameEqualFold(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldEqualFold(FieldJobName, v))
}

// JobNameContainsFold applies the ContainsFold predicate on the "job_name" field.
func JobNameContainsFold(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldContainsFold(FieldJobName, v))
}

// JobGroupEQ applies the EQ predicate on the "job_group" field.
func JobGroupEQ(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldEQ(FieldJobGroup, v))
}

// JobGroupNEQ applies the NEQ predicate on the "job_group" field.
func JobGroupNEQ(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldNEQ(FieldJobGroup, v))
}

// JobGroupIn applies the In predicate on the "job_group" field.
func JobGroupIn(vs ...string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldIn(FieldJobGroup, vs...))
}

// JobGroupNotIn applies the NotIn predicate on the "job_group" field.
func JobGroupNotIn(vs ...string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldNotIn(FieldJobGroup, vs...))
}

// JobGroupGT applies the GT predicate on the "job_group" field.
func JobGroupGT(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldGT(FieldJobGroup, v))
}

// JobGroupGTE applies the GTE predicate on the "job_group" field.
func JobGroupGTE(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldGTE(FieldJobGroup, v))
}

// JobGroupLT applies the LT predicate on the "job_group" field.
func JobGroupLT(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldLT(FieldJobGroup, v))
}

// JobGroupLTE applies the LTE predicate on the "job_group" field.
func JobGroupLTE(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldLTE(FieldJobGroup, v))
}

// JobGroupContains applies the Contains predicate on the "job_group" field.
func JobGroupContains(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldContains(FieldJobGroup, v))
}

// JobGroupHasPrefix applies the HasPrefix predicate on the "job_group" field.
func JobGroupHasPrefix(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldHasPrefix(FieldJobGroup, v))
}

// JobGroupHasSuffix applies the HasSuffix predicate on the "job_group" field.
func JobGroupHasSuffix(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldHasSuffix(FieldJobGroup, v))
}

// JobGroupEqualFold applies the EqualFold predicate on the "job_group" field.
func JobGroupEqualFold(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldEqualFold(FieldJobGroup, v))
}

// JobGroupContainsFold applies the ContainsFold predicate on the "job_group" field.
func JobGroupContainsFold(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldContainsFold(FieldJobGroup, v))
}

// HandlerEQ applies the EQ predicate on the "handler" field.
func HandlerEQ(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldEQ(FieldHandler, v))
}

// HandlerNEQ applies the NEQ predicate on the "handler" field.
func HandlerNEQ(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldNEQ(FieldHandler, v))
}

// HandlerIn applies the In predicate on the "handler" field.
func HandlerIn(vs ...string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldIn(FieldHandler, vs...))
}

// HandlerNotIn applies the NotIn predicate on the "handler" field.
func HandlerNotIn(vs ...string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldNotIn(FieldHandler, vs...))
}

// HandlerGT applies the GT predicate on the "handler" field.
func HandlerGT(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldGT(FieldHandler, v))
}

// HandlerGTE applies the GTE predicate on the "handler" field.
func HandlerGTE(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldGTE(FieldHandler, v))
}

// HandlerLT applies the LT predicate on the "handler" field.
func HandlerLT(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldLT(FieldHandler, v))
}

// HandlerLTE applies the LTE predicate on the "handler" field.
func HandlerLTE(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldLTE(FieldHandler, v))
}

// HandlerContains applies the Contains predicate on the "handler" field.
func HandlerContains(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldContains(FieldHandler, v))
}

// HandlerHasPrefix applies the HasPrefix predicate on the "handler" field.
func HandlerHasPrefix(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldHasPrefix(FieldHandler, v))
}

// HandlerHasSuffix applies the HasSuffix predicate on the "handler" field.
func HandlerHasSuffix(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldHasSuffix(FieldHandler, v))
}

// HandlerEqualFold applies the EqualFold predicate on the "handler" field.
func HandlerEqualFold(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldEqualFold(FieldHandler, v))
}

// HandlerContainsFold applies the ContainsFold predicate on the "handler" field.
func HandlerContainsFold(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldContainsFold(FieldHandler, v))
}

// TriggerTypeEQ applies the EQ predicate on the "trigger_type" field.
func TriggerTypeEQ(v TriggerType) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldEQ(FieldTriggerType, v))
}

// TriggerTypeNEQ applies the NEQ predicate on the "trigger_type" field.
func TriggerTypeNEQ(v TriggerType) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldNEQ(FieldTriggerType, v))
}

// TriggerTypeIn applies the In predicate on the "trigger_type" field.
func TriggerTypeIn(vs ...TriggerType) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldIn(FieldTriggerType, vs...))
}

// TriggerTypeNotIn applies the NotIn predicate on the "trigger_type" field.
func TriggerTypeNotIn(vs ...TriggerType) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldNotIn(FieldTriggerType, vs...))
}

// ExecNodeEQ applies the EQ predicate on the "exec_node" field.
func ExecNodeEQ(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldEQ(FieldExecNode, v))
}

// ExecNodeNEQ applies the NEQ predicate on the "exec_node" field.
func ExecNodeNEQ(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldNEQ(FieldExecNode, v))
}

// ExecNodeIn applies the In predicate on the "exec_node" field.
func ExecNodeIn(vs ...string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldIn(FieldExecNode, vs...))
}

// ExecNodeNotIn applies the NotIn predicate on the "exec_node" field.
func ExecNodeNotIn(vs ...string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldNotIn(FieldExecNode, vs...))
}

// ExecNodeGT applies the GT predicate on the "exec_node" field.
func ExecNodeGT(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldGT(FieldExecNode, v))
}

// ExecNodeGTE applies the GTE predicate on the "exec_node" field.
func ExecNodeGTE(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldGTE(FieldExecNode, v))
}

// ExecNodeLT applies the LT predicate on the "exec_node" field.
func ExecNodeLT(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldLT(FieldExecNode, v))
}

// ExecNodeLTE applies the LTE predicate on the "exec_node" field.
func ExecNodeLTE(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldLTE(FieldExecNode, v))
}

// ExecNodeContains applies the Contains predicate on the "exec_node" field.
func ExecNodeContains(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldContains(FieldExecNode, v))
}

// ExecNodeHasPrefix applies the HasPrefix predicate on the "exec_node" field.
func ExecNodeHasPrefix(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldHasPrefix(FieldExecNode, v))
}

// ExecNodeHasSuffix applies the HasSuffix predicate on the "exec_node" field.
func ExecNodeHasSuffix(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldHasSuffix(FieldExecNode, v))
}

// ExecNodeEqualFold applies the EqualFold predicate on the "exec_node" field.
func ExecNodeEqualFold(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldEqualFold(FieldExecNode, v))
}

// ExecNodeContainsFold applies the ContainsFold predicate on the "exec_node" field.
func ExecNodeContainsFold(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldContainsFold(FieldExecNode, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldNotIn(FieldStatus, vs...))
}

// AttemptEQ applies the EQ predicate on the "attempt" field.
func AttemptEQ(v int32) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldEQ(FieldAttempt, v))
}

// AttemptNEQ applies the NEQ predicate on the "attempt" field.
func AttemptNEQ(v int32) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldNEQ(FieldAttempt, v))
}

// AttemptIn applies the In predicate on the "attempt" field.
func AttemptIn(vs ...int32) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldIn(FieldAttempt, vs...))
}

// AttemptNotIn applies the NotIn predicate on the "attempt" field.
func AttemptNotIn(vs ...int32) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldNotIn(FieldAttempt, vs...))
}

// AttemptGT applies the GT predicate on the "attempt" field.
func AttemptGT(v int32) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldGT(FieldAttempt, v))
}

// AttemptGTE applies the GTE predicate on the "attempt" field.
func AttemptGTE(v int32) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldGTE(FieldAttempt, v))
}

// AttemptLT applies the LT predicate on the "attempt" field.
func AttemptLT(v int32) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldLT(FieldAttempt, v))
}

// AttemptLTE applies the LTE predicate on the "attempt" field.
func AttemptLTE(v int32) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldLTE(FieldAttempt, v))
}

// MessageEQ applies the EQ predicate on the "message" field.
func MessageEQ(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldEQ(FieldMessage, v))
}

// MessageNEQ applies the NEQ predicate on the "message" field.
func MessageNEQ(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldNEQ(FieldMessage, v))
}

// MessageIn applies the In predicate on the "message" field.
func MessageIn(vs ...string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldIn(FieldMessage, vs...))
}

// MessageNotIn applies the NotIn predicate on the "message" field.
func MessageNotIn(vs ...string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldNotIn(FieldMessage, vs...))
}

// MessageGT applies the GT predicate on the "message" field.
func MessageGT(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldGT(FieldMessage, v))
}

// MessageGTE applies the GTE predicate on the "message" field.
func MessageGTE(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldGTE(FieldMessage, v))
}

// MessageLT applies the LT predicate on the "message" field.
func MessageLT(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldLT(FieldMessage, v))
}

// MessageLTE applies the LTE predicate on the "message" field.
func MessageLTE(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldLTE(FieldMessage, v))
}

// MessageContains applies the Contains predicate on the "message" field.
func MessageContains(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldContains(FieldMessage, v))
}

// MessageHasPrefix applies the HasPrefix predicate on the "message" field.
func MessageHasPrefix(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldHasPrefix(FieldMessage, v))
}

// MessageHasSuffix applies the HasSuffix predicate on the "message" field.
func MessageHasSuffix(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldHasSuffix(FieldMessage, v))
}

// MessageEqualFold applies the EqualFold predicate on the "message" field.
func MessageEqualFold(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldEqualFold(FieldMessage, v))
}

// MessageContainsFold applies the ContainsFold predicate on the "message" field.
func MessageContainsFold(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldContainsFold(FieldMessage, v))
}

// ExceptionInfoEQ applies the EQ predicate on the "exception_info" field.
func ExceptionInfoEQ(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldEQ(FieldExceptionInfo, v))
}

// ExceptionInfoNEQ applies the NEQ predicate on the "exception_info" field.
func ExceptionInfoNEQ(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldNEQ(FieldExceptionInfo, v))
}

// ExceptionInfoIn applies the In predicate on the "exception_info" field.
func ExceptionInfoIn(vs ...string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldIn(FieldExceptionInfo, vs...))
}

// ExceptionInfoNotIn applies the NotIn predicate on the "exception_info" field.
func ExceptionInfoNotIn(vs ...string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldNotIn(FieldExceptionInfo, vs...))
}

// ExceptionInfoGT applies the GT predicate on the "exception_info" field.
func ExceptionInfoGT(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldGT(FieldExceptionInfo, v))
}

// ExceptionInfoGTE applies the GTE predicate on the "exception_info" field.
func ExceptionInfoGTE(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldGTE(FieldExceptionInfo, v))
}

// ExceptionInfoLT applies the LT predicate on the "exception_info" field.
func ExceptionInfoLT(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldLT(FieldExceptionInfo, v))
}

// ExceptionInfoLTE applies the LTE predicate on the "exception_info" field.
func ExceptionInfoLTE(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldLTE(FieldExceptionInfo, v))
}

// ExceptionInfoContains applies the Contains predicate on the "exception_info" field.
func ExceptionInfoContains(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldContains(FieldExceptionInfo, v))
}

// ExceptionInfoHasPrefix applies the HasPrefix predicate on the "exception_info" field.
func ExceptionInfoHasPrefix(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldHasPrefix(FieldExceptionInfo, v))
}

// ExceptionInfoHasSuffix applies the HasSuffix predicate on the "exception_info" field.
func ExceptionInfoHasSuffix(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldHasSuffix(FieldExceptionInfo, v))
}

// ExceptionInfoEqualFold applies the EqualFold predicate on the "exception_info" field.
func ExceptionInfoEqualFold(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldEqualFold(FieldExceptionInfo, v))
}

// ExceptionInfoContainsFold applies the ContainsFold predicate on the "exception_info" field.
func ExceptionInfoContainsFold(v string) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldContainsFold(FieldExceptionInfo, v))
}

// DurationEQ applies the EQ predicate on the "duration" field.
func DurationEQ(v int64) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldEQ(FieldDuration, v))
}

// DurationNEQ applies the NEQ predicate on the "duration" field.
func DurationNEQ(v int64) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldNEQ(FieldDuration, v))
}

// DurationIn applies the In predicate on the "duration" field.
func DurationIn(vs ...int64) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldIn(FieldDuration, vs...))
}

// DurationNotIn applies the NotIn predicate on the "duration" field.
func DurationNotIn(vs ...int64) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldNotIn(FieldDuration, vs...))
}

// DurationGT applies the GT predicate on the "duration" field.
func DurationGT(v int64) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldGT(FieldDuration, v))
}

// DurationGTE applies the GTE predicate on the "duration" field.
func DurationGTE(v int64) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldGTE(FieldDuration, v))
}

// DurationLT applies the LT predicate on the "duration" field.
func DurationLT(v int64) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldLT(FieldDuration, v))
}

// DurationLTE applies the LTE predicate on the "duration" field.
func DurationLTE(v int64) predicate.SysJobLog {
	return predicate.SysJobLog(sql.FieldLTE(FieldDuration, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SysJobLog) predicate.SysJobLog {
	return predicate.SysJobLog(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SysJobLog) predicate.SysJobLog {
	return predicate.SysJobLog(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SysJobLog) predicate.SysJobLog {
	return predicate.SysJobLog(sql.NotPredicates(p))
}
