// 声明 proto 语法版本，固定值

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: job_service.proto

// proto 包名

package apps

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SysJobs_GetJobById_FullMethodName            = "/job_service.SysJobs/GetJobById"
	SysJobs_GetJobList_FullMethodName            = "/job_service.SysJobs/GetJobList"
	SysJobs_CreateJob_FullMethodName             = "/job_service.SysJobs/CreateJob"
	SysJobs_UpdateJob_FullMethodName             = "/job_service.SysJobs/UpdateJob"
	SysJobs_DeleteJob_FullMethodName             = "/job_service.SysJobs/DeleteJob"
	SysJobs_StartJob_FullMethodName              = "/job_service.SysJobs/StartJob"
	SysJobs_PauseJob_FullMethodName              = "/job_service.SysJobs/PauseJob"
	SysJobs_RunJobOnce_FullMethodName            = "/job_service.SysJobs/RunJobOnce"
	SysJobs_CleanJobLog_FullMethodName           = "/job_service.SysJobs/CleanJobLog"
	SysJobs_GetJobLogList_FullMethodName         = "/job_service.SysJobs/GetJobLogList"
	SysJobs_GetRegisteredHandlers_FullMethodName = "/job_service.SysJobs/GetRegisteredHandlers"
)

// SysJobsClient is the client API for SysJobs service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SysJobsClient interface {
	// 根据ID获取任务
	GetJobById(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Job, error)
	// 获取任务列表
	GetJobList(ctx context.Context, in *JobListReq, opts ...grpc.CallOption) (*JobListResp, error)
	// 创建任务
	CreateJob(ctx context.Context, in *Job, opts ...grpc.CallOption) (*EmptyResp, error)
	// 更新任务 (更新后通知调度器重新加载)
	UpdateJob(ctx context.Context, in *Job, opts ...grpc.CallOption) (*EmptyResp, error)
	// 删除任务 (软删, 通知调度器移除)
	DeleteJob(ctx context.Context, in *IdsReq, opts ...grpc.CallOption) (*EmptyResp, error)
	// 启动任务
	StartJob(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*EmptyResp, error)
	// 暂停任务
	PauseJob(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*EmptyResp, error)
	// 立即执行任务 (不受 status 限制, 记 trigger=manual)
	// 异步执行：接口只表示"已提交"，执行结果见 sys_job_logs 与 last_*/next_run_at
	RunJobOnce(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*EmptyResp, error)
	// 清理任务日志 (按 job_id+保留天数, 禁止全表)
	CleanJobLog(ctx context.Context, in *CleanJobLogReq, opts ...grpc.CallOption) (*EmptyResp, error)
	// 获取任务日志列表
	GetJobLogList(ctx context.Context, in *JobLogListReq, opts ...grpc.CallOption) (*JobLogListResp, error)
	// 获取已注册的处理器列表（本实例代码注册表，唯一来源）
	GetRegisteredHandlers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HandlerListResp, error)
}

type sysJobsClient struct {
	cc grpc.ClientConnInterface
}

func NewSysJobsClient(cc grpc.ClientConnInterface) SysJobsClient {
	return &sysJobsClient{cc}
}

func (c *sysJobsClient) GetJobById(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*Job, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Job)
	err := c.cc.Invoke(ctx, SysJobs_GetJobById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysJobsClient) GetJobList(ctx context.Context, in *JobListReq, opts ...grpc.CallOption) (*JobListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobListResp)
	err := c.cc.Invoke(ctx, SysJobs_GetJobList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysJobsClient) CreateJob(ctx context.Context, in *Job, opts ...grpc.CallOption) (*EmptyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResp)
	err := c.cc.Invoke(ctx, SysJobs_CreateJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysJobsClient) UpdateJob(ctx context.Context, in *Job, opts ...grpc.CallOption) (*EmptyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResp)
	err := c.cc.Invoke(ctx, SysJobs_UpdateJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysJobsClient) DeleteJob(ctx context.Context, in *IdsReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResp)
	err := c.cc.Invoke(ctx, SysJobs_DeleteJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysJobsClient) StartJob(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResp)
	err := c.cc.Invoke(ctx, SysJobs_StartJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysJobsClient) PauseJob(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResp)
	err := c.cc.Invoke(ctx, SysJobs_PauseJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysJobsClient) RunJobOnce(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResp)
	err := c.cc.Invoke(ctx, SysJobs_RunJobOnce_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysJobsClient) CleanJobLog(ctx context.Context, in *CleanJobLogReq, opts ...grpc.CallOption) (*EmptyResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyResp)
	err := c.cc.Invoke(ctx, SysJobs_CleanJobLog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysJobsClient) GetJobLogList(ctx context.Context, in *JobLogListReq, opts ...grpc.CallOption) (*JobLogListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobLogListResp)
	err := c.cc.Invoke(ctx, SysJobs_GetJobLogList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sysJobsClient) GetRegisteredHandlers(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*HandlerListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandlerListResp)
	err := c.cc.Invoke(ctx, SysJobs_GetRegisteredHandlers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SysJobsServer is the server API for SysJobs service.
// All implementations must embed UnimplementedSysJobsServer
// for forward compatibility.
type SysJobsServer interface {
	// 根据ID获取任务
	GetJobById(context.Context, *IdReq) (*Job, error)
	// 获取任务列表
	GetJobList(context.Context, *JobListReq) (*JobListResp, error)
	// 创建任务
	CreateJob(context.Context, *Job) (*EmptyResp, error)
	// 更新任务 (更新后通知调度器重新加载)
	UpdateJob(context.Context, *Job) (*EmptyResp, error)
	// 删除任务 (软删, 通知调度器移除)
	DeleteJob(context.Context, *IdsReq) (*EmptyResp, error)
	// 启动任务
	StartJob(context.Context, *IdReq) (*EmptyResp, error)
	// 暂停任务
	PauseJob(context.Context, *IdReq) (*EmptyResp, error)
	// 立即执行任务 (不受 status 限制, 记 trigger=manual)
	// 异步执行：接口只表示"已提交"，执行结果见 sys_job_logs 与 last_*/next_run_at
	RunJobOnce(context.Context, *IdReq) (*EmptyResp, error)
	// 清理任务日志 (按 job_id+保留天数, 禁止全表)
	CleanJobLog(context.Context, *CleanJobLogReq) (*EmptyResp, error)
	// 获取任务日志列表
	GetJobLogList(context.Context, *JobLogListReq) (*JobLogListResp, error)
	// 获取已注册的处理器列表（本实例代码注册表，唯一来源）
	GetRegisteredHandlers(context.Context, *emptypb.Empty) (*HandlerListResp, error)
	mustEmbedUnimplementedSysJobsServer()
}

// UnimplementedSysJobsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSysJobsServer struct{}

func (UnimplementedSysJobsServer) GetJobById(context.Context, *IdReq) (*Job, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobById not implemented")
}
func (UnimplementedSysJobsServer) GetJobList(context.Context, *JobListReq) (*JobListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobList not implemented")
}
func (UnimplementedSysJobsServer) CreateJob(context.Context, *Job) (*EmptyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateJob not implemented")
}
func (UnimplementedSysJobsServer) UpdateJob(context.Context, *Job) (*EmptyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateJob not implemented")
}
func (UnimplementedSysJobsServer) DeleteJob(context.Context, *IdsReq) (*EmptyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteJob not implemented")
}
func (UnimplementedSysJobsServer) StartJob(context.Context, *IdReq) (*EmptyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartJob not implemented")
}
func (UnimplementedSysJobsServer) PauseJob(context.Context, *IdReq) (*EmptyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PauseJob not implemented")
}
func (UnimplementedSysJobsServer) RunJobOnce(context.Context, *IdReq) (*EmptyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunJobOnce not implemented")
}
func (UnimplementedSysJobsServer) CleanJobLog(context.Context, *CleanJobLogReq) (*EmptyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CleanJobLog not implemented")
}
func (UnimplementedSysJobsServer) GetJobLogList(context.Context, *JobLogListReq) (*JobLogListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJobLogList not implemented")
}
func (UnimplementedSysJobsServer) GetRegisteredHandlers(context.Context, *emptypb.Empty) (*HandlerListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRegisteredHandlers not implemented")
}
func (UnimplementedSysJobsServer) mustEmbedUnimplementedSysJobsServer() {}
func (UnimplementedSysJobsServer) testEmbeddedByValue()                 {}

// UnsafeSysJobsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SysJobsServer will
// result in compilation errors.
type UnsafeSysJobsServer interface {
	mustEmbedUnimplementedSysJobsServer()
}

func RegisterSysJobsServer(s grpc.ServiceRegistrar, srv SysJobsServer) {
	// If the following call pancis, it indicates UnimplementedSysJobsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SysJobs_ServiceDesc, srv)
}

func _SysJobs_GetJobById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysJobsServer).GetJobById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysJobs_GetJobById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysJobsServer).GetJobById(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysJobs_GetJobList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysJobsServer).GetJobList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysJobs_GetJobList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysJobsServer).GetJobList(ctx, req.(*JobListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysJobs_CreateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Job)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysJobsServer).CreateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysJobs_CreateJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysJobsServer).CreateJob(ctx, req.(*Job))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysJobs_UpdateJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Job)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysJobsServer).UpdateJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysJobs_UpdateJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysJobsServer).UpdateJob(ctx, req.(*Job))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysJobs_DeleteJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysJobsServer).DeleteJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysJobs_DeleteJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysJobsServer).DeleteJob(ctx, req.(*IdsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysJobs_StartJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysJobsServer).StartJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysJobs_StartJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysJobsServer).StartJob(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysJobs_PauseJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysJobsServer).PauseJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysJobs_PauseJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysJobsServer).PauseJob(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysJobs_RunJobOnce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysJobsServer).RunJobOnce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysJobs_RunJobOnce_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysJobsServer).RunJobOnce(ctx, req.(*IdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysJobs_CleanJobLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CleanJobLogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysJobsServer).CleanJobLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysJobs_CleanJobLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysJobsServer).CleanJobLog(ctx, req.(*CleanJobLogReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysJobs_GetJobLogList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JobLogListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysJobsServer).GetJobLogList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysJobs_GetJobLogList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysJobsServer).GetJobLogList(ctx, req.(*JobLogListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _SysJobs_GetRegisteredHandlers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SysJobsServer).GetRegisteredHandlers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SysJobs_GetRegisteredHandlers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SysJobsServer).GetRegisteredHandlers(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// SysJobs_ServiceDesc is the grpc.ServiceDesc for SysJobs service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SysJobs_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "job_service.SysJobs",
	HandlerType: (*SysJobsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetJobById",
			Handler:    _SysJobs_GetJobById_Handler,
		},
		{
			MethodName: "GetJobList",
			Handler:    _SysJobs_GetJobList_Handler,
		},
		{
			MethodName: "CreateJob",
			Handler:    _SysJobs_CreateJob_Handler,
		},
		{
			MethodName: "UpdateJob",
			Handler:    _SysJobs_UpdateJob_Handler,
		},
		{
			MethodName: "DeleteJob",
			Handler:    _SysJobs_DeleteJob_Handler,
		},
		{
			MethodName: "StartJob",
			Handler:    _SysJobs_StartJob_Handler,
		},
		{
			MethodName: "PauseJob",
			Handler:    _SysJobs_PauseJob_Handler,
		},
		{
			MethodName: "RunJobOnce",
			Handler:    _SysJobs_RunJobOnce_Handler,
		},
		{
			MethodName: "CleanJobLog",
			Handler:    _SysJobs_CleanJobLog_Handler,
		},
		{
			MethodName: "GetJobLogList",
			Handler:    _SysJobs_GetJobLogList_Handler,
		},
		{
			MethodName: "GetRegisteredHandlers",
			Handler:    _SysJobs_GetRegisteredHandlers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "job_service.proto",
}
