// 声明 proto 语法版本，固定值

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.4
// source: job_service.proto

// proto 包名

package apps

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Job struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                               // 雪花ID (string 避免前端精度丢失)
	CreatedAt      int64                  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`               // 创建时间(秒)
	UpdatedAt      int64                  `protobuf:"varint,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`               // 更新时间(秒)
	Name           string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`                                           // 任务名称
	Group          string                 `protobuf:"bytes,5,opt,name=group,proto3" json:"group,omitempty"`                                         // 分组 (字典 job_group)
	Handler        string                 `protobuf:"bytes,6,opt,name=handler,proto3" json:"handler,omitempty"`                                     // 处理器注册码
	Params         string                 `protobuf:"bytes,7,opt,name=params,proto3" json:"params,omitempty"`                                       // 处理器参数 (JSON)
	CronExpression string                 `protobuf:"bytes,8,opt,name=cron_expression,json=cronExpression,proto3" json:"cron_expression,omitempty"` // 兼容 5/6 位 (秒可选)
	TimeZone       string                 `protobuf:"bytes,9,opt,name=time_zone,json=timeZone,proto3" json:"time_zone,omitempty"`                   // 时区
	MisfirePolicy  string                 `protobuf:"bytes,10,opt,name=misfire_policy,json=misfirePolicy,proto3" json:"misfire_policy,omitempty"`   // skip/fire_once/fire_all
	Concurrent     bool                   `protobuf:"varint,11,opt,name=concurrent,proto3" json:"concurrent,omitempty"`                             // 是否允许并发
	Timeout        int32                  `protobuf:"varint,12,opt,name=timeout,proto3" json:"timeout,omitempty"`                                   // 超时(秒)
	MaxRetry       int32                  `protobuf:"varint,13,opt,name=max_retry,json=maxRetry,proto3" json:"max_retry,omitempty"`                 // 失败重试次数
	RetryInterval  int32                  `protobuf:"varint,14,opt,name=retry_interval,json=retryInterval,proto3" json:"retry_interval,omitempty"`  // 重试间隔(秒)
	Status         string                 `protobuf:"bytes,15,opt,name=status,proto3" json:"status,omitempty"`                                      // active/suspended (StatusMixin)
	Remark         string                 `protobuf:"bytes,16,opt,name=remark,proto3" json:"remark,omitempty"`                                      // 备注
	NextRunAt      int64                  `protobuf:"varint,17,opt,name=next_run_at,json=nextRunAt,proto3" json:"next_run_at,omitempty"`            // 下次触发时间(秒, 调度器回写)
	LastRunAt      int64                  `protobuf:"varint,18,opt,name=last_run_at,json=lastRunAt,proto3" json:"last_run_at,omitempty"`            // 上次触发时间(秒)
	LastStatus     string                 `protobuf:"bytes,19,opt,name=last_status,json=lastStatus,proto3" json:"last_status,omitempty"`            // 上次结果: success/fail/timeout/skipped/none
	LastDuration   int64                  `protobuf:"varint,20,opt,name=last_duration,json=lastDuration,proto3" json:"last_duration,omitempty"`     // 上次耗时(毫秒)
	LastError      string                 `protobuf:"bytes,21,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`               // 上次错误摘要
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Job) Reset() {
	*x = Job{}
	mi := &file_job_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Job) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Job) ProtoMessage() {}

func (x *Job) ProtoReflect() protoreflect.Message {
	mi := &file_job_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Job.ProtoReflect.Descriptor instead.
func (*Job) Descriptor() ([]byte, []int) {
	return file_job_service_proto_rawDescGZIP(), []int{0}
}

func (x *Job) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Job) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Job) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Job) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Job) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Job) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

func (x *Job) GetParams() string {
	if x != nil {
		return x.Params
	}
	return ""
}

func (x *Job) GetCronExpression() string {
	if x != nil {
		return x.CronExpression
	}
	return ""
}

func (x *Job) GetTimeZone() string {
	if x != nil {
		return x.TimeZone
	}
	return ""
}

func (x *Job) GetMisfirePolicy() string {
	if x != nil {
		return x.MisfirePolicy
	}
	return ""
}

func (x *Job) GetConcurrent() bool {
	if x != nil {
		return x.Concurrent
	}
	return false
}

func (x *Job) GetTimeout() int32 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

func (x *Job) GetMaxRetry() int32 {
	if x != nil {
		return x.MaxRetry
	}
	return 0
}

func (x *Job) GetRetryInterval() int32 {
	if x != nil {
		return x.RetryInterval
	}
	return 0
}

func (x *Job) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Job) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *Job) GetNextRunAt() int64 {
	if x != nil {
		return x.NextRunAt
	}
	return 0
}

func (x *Job) GetLastRunAt() int64 {
	if x != nil {
		return x.LastRunAt
	}
	return 0
}

func (x *Job) GetLastStatus() string {
	if x != nil {
		return x.LastStatus
	}
	return ""
}

func (x *Job) GetLastDuration() int64 {
	if x != nil {
		return x.LastDuration
	}
	return 0
}

func (x *Job) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type IdReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdReq) Reset() {
	*x = IdReq{}
	mi := &file_job_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdReq) ProtoMessage() {}

func (x *IdReq) ProtoReflect() protoreflect.Message {
	mi := &file_job_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdReq.ProtoReflect.Descriptor instead.
func (*IdReq) Descriptor() ([]byte, []int) {
	return file_job_service_proto_rawDescGZIP(), []int{1}
}

func (x *IdReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type IdsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IdsReq) Reset() {
	*x = IdsReq{}
	mi := &file_job_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdsReq) ProtoMessage() {}

func (x *IdsReq) ProtoReflect() protoreflect.Message {
	mi := &file_job_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdsReq.ProtoReflect.Descriptor instead.
func (*IdsReq) Descriptor() ([]byte, []int) {
	return file_job_service_proto_rawDescGZIP(), []int{2}
}

func (x *IdsReq) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type EmptyResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyResp) Reset() {
	*x = EmptyResp{}
	mi := &file_job_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyResp) ProtoMessage() {}

func (x *EmptyResp) ProtoReflect() protoreflect.Message {
	mi := &file_job_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyResp.ProtoReflect.Descriptor instead.
func (*EmptyResp) Descriptor() ([]byte, []int) {
	return file_job_service_proto_rawDescGZIP(), []int{3}
}

func (x *EmptyResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *EmptyResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type JobListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Handler       string                 `protobuf:"bytes,3,opt,name=handler,proto3" json:"handler,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Page          int32                  `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,6,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobListReq) Reset() {
	*x = JobListReq{}
	mi := &file_job_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobListReq) ProtoMessage() {}

func (x *JobListReq) ProtoReflect() protoreflect.Message {
	mi := &file_job_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobListReq.ProtoReflect.Descriptor instead.
func (*JobListReq) Descriptor() ([]byte, []int) {
	return file_job_service_proto_rawDescGZIP(), []int{4}
}

func (x *JobListReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *JobListReq) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *JobListReq) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

func (x *JobListReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobListReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *JobListReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type JobListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*Job                 `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobListResp) Reset() {
	*x = JobListResp{}
	mi := &file_job_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobListResp) ProtoMessage() {}

func (x *JobListResp) ProtoReflect() protoreflect.Message {
	mi := &file_job_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobListResp.ProtoReflect.Descriptor instead.
func (*JobListResp) Descriptor() ([]byte, []int) {
	return file_job_service_proto_rawDescGZIP(), []int{5}
}

func (x *JobListResp) GetList() []*Job {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *JobListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type JobLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`             // 执行时间(秒)
	JobId         string                 `protobuf:"bytes,3,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`                          // 任务ID (string)
	JobName       string                 `protobuf:"bytes,4,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`                    // 任务名称快照
	JobGroup      string                 `protobuf:"bytes,5,opt,name=job_group,json=jobGroup,proto3" json:"job_group,omitempty"`                 // 分组快照
	Handler       string                 `protobuf:"bytes,6,opt,name=handler,proto3" json:"handler,omitempty"`                                   // 处理器注册码快照
	TriggerType   string                 `protobuf:"bytes,7,opt,name=trigger_type,json=triggerType,proto3" json:"trigger_type,omitempty"`        // cron/manual/retry
	ExecNode      string                 `protobuf:"bytes,8,opt,name=exec_node,json=execNode,proto3" json:"exec_node,omitempty"`                 // 执行实例标识
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`                                     // running/success/fail/timeout/skipped
	Attempt       int32                  `protobuf:"varint,10,opt,name=attempt,proto3" json:"attempt,omitempty"`                                 // 尝试次数
	Message       string                 `protobuf:"bytes,11,opt,name=message,proto3" json:"message,omitempty"`                                  // 结果摘要
	ExceptionInfo string                 `protobuf:"bytes,12,opt,name=exception_info,json=exceptionInfo,proto3" json:"exception_info,omitempty"` // 异常信息(截断)
	Duration      int64                  `protobuf:"varint,13,opt,name=duration,proto3" json:"duration,omitempty"`                               // 执行时长(毫秒)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobLog) Reset() {
	*x = JobLog{}
	mi := &file_job_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobLog) ProtoMessage() {}

func (x *JobLog) ProtoReflect() protoreflect.Message {
	mi := &file_job_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobLog.ProtoReflect.Descriptor instead.
func (*JobLog) Descriptor() ([]byte, []int) {
	return file_job_service_proto_rawDescGZIP(), []int{6}
}

func (x *JobLog) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *JobLog) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *JobLog) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobLog) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *JobLog) GetJobGroup() string {
	if x != nil {
		return x.JobGroup
	}
	return ""
}

func (x *JobLog) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

func (x *JobLog) GetTriggerType() string {
	if x != nil {
		return x.TriggerType
	}
	return ""
}

func (x *JobLog) GetExecNode() string {
	if x != nil {
		return x.ExecNode
	}
	return ""
}

func (x *JobLog) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobLog) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *JobLog) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JobLog) GetExceptionInfo() string {
	if x != nil {
		return x.ExceptionInfo
	}
	return ""
}

func (x *JobLog) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type JobLogListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	JobName       string                 `protobuf:"bytes,2,opt,name=job_name,json=jobName,proto3" json:"job_name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	BeginTime     int64                  `protobuf:"varint,4,opt,name=begin_time,json=beginTime,proto3" json:"begin_time,omitempty"` // 开始时间(秒)
	EndTime       int64                  `protobuf:"varint,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // 结束时间(秒)
	Page          int32                  `protobuf:"varint,6,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,7,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobLogListReq) Reset() {
	*x = JobLogListReq{}
	mi := &file_job_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobLogListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobLogListReq) ProtoMessage() {}

func (x *JobLogListReq) ProtoReflect() protoreflect.Message {
	mi := &file_job_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobLogListReq.ProtoReflect.Descriptor instead.
func (*JobLogListReq) Descriptor() ([]byte, []int) {
	return file_job_service_proto_rawDescGZIP(), []int{7}
}

func (x *JobLogListReq) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobLogListReq) GetJobName() string {
	if x != nil {
		return x.JobName
	}
	return ""
}

func (x *JobLogListReq) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobLogListReq) GetBeginTime() int64 {
	if x != nil {
		return x.BeginTime
	}
	return 0
}

func (x *JobLogListReq) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *JobLogListReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *JobLogListReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type JobLogListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*JobLog              `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobLogListResp) Reset() {
	*x = JobLogListResp{}
	mi := &file_job_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobLogListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobLogListResp) ProtoMessage() {}

func (x *JobLogListResp) ProtoReflect() protoreflect.Message {
	mi := &file_job_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobLogListResp.ProtoReflect.Descriptor instead.
func (*JobLogListResp) Descriptor() ([]byte, []int) {
	return file_job_service_proto_rawDescGZIP(), []int{8}
}

func (x *JobLogListResp) GetList() []*JobLog {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *JobLogListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CleanJobLogReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`           // 为空 = 不清理；必须按 job_id 限定，禁止全表
	KeepDays      int32                  `protobuf:"varint,2,opt,name=keep_days,json=keepDays,proto3" json:"keep_days,omitempty"` // 保留天数, 默认 30
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CleanJobLogReq) Reset() {
	*x = CleanJobLogReq{}
	mi := &file_job_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CleanJobLogReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CleanJobLogReq) ProtoMessage() {}

func (x *CleanJobLogReq) ProtoReflect() protoreflect.Message {
	mi := &file_job_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CleanJobLogReq.ProtoReflect.Descriptor instead.
func (*CleanJobLogReq) Descriptor() ([]byte, []int) {
	return file_job_service_proto_rawDescGZIP(), []int{9}
}

func (x *CleanJobLogReq) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CleanJobLogReq) GetKeepDays() int32 {
	if x != nil {
		return x.KeepDays
	}
	return 0
}

type HandlerItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"` // 注册码，如 "report.daily"
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"` // 展示名（代码注册表内置）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandlerItem) Reset() {
	*x = HandlerItem{}
	mi := &file_job_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandlerItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlerItem) ProtoMessage() {}

func (x *HandlerItem) ProtoReflect() protoreflect.Message {
	mi := &file_job_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlerItem.ProtoReflect.Descriptor instead.
func (*HandlerItem) Descriptor() ([]byte, []int) {
	return file_job_service_proto_rawDescGZIP(), []int{10}
}

func (x *HandlerItem) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *HandlerItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HandlerListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*HandlerItem         `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandlerListResp) Reset() {
	*x = HandlerListResp{}
	mi := &file_job_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandlerListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandlerListResp) ProtoMessage() {}

func (x *HandlerListResp) ProtoReflect() protoreflect.Message {
	mi := &file_job_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandlerListResp.ProtoReflect.Descriptor instead.
func (*HandlerListResp) Descriptor() ([]byte, []int) {
	return file_job_service_proto_rawDescGZIP(), []int{11}
}

func (x *HandlerListResp) GetList() []*HandlerItem {
	if x != nil {
		return x.List
	}
	return nil
}

var File_job_service_proto protoreflect.FileDescriptor

const file_job_service_proto_rawDesc = "" +
	"\n" +
	"\x11job_service.proto\x12\vjob_service\x1a\x1bgoogle/protobuf/empty.proto\"\xef\x04\n" +
	"\x03Job\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\x03R\tupdatedAt\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x14\n" +
	"\x05group\x18\x05 \x01(\tR\x05group\x12\x18\n" +
	"\ahandler\x18\x06 \x01(\tR\ahandler\x12\x16\n" +
	"\x06params\x18\a \x01(\tR\x06params\x12'\n" +
	"\x0fcron_expression\x18\b \x01(\tR\x0ecronExpression\x12\x1b\n" +
	"\ttime_zone\x18\t \x01(\tR\btimeZone\x12%\n" +
	"\x0emisfire_policy\x18\n" +
	" \x01(\tR\rmisfirePolicy\x12\x1e\n" +
	"\n" +
	"concurrent\x18\v \x01(\bR\n" +
	"concurrent\x12\x18\n" +
	"\atimeout\x18\f \x01(\x05R\atimeout\x12\x1b\n" +
	"\tmax_retry\x18\r \x01(\x05R\bmaxRetry\x12%\n" +
	"\x0eretry_interval\x18\x0e \x01(\x05R\rretryInterval\x12\x16\n" +
	"\x06status\x18\x0f \x01(\tR\x06status\x12\x16\n" +
	"\x06remark\x18\x10 \x01(\tR\x06remark\x12\x1e\n" +
	"\vnext_run_at\x18\x11 \x01(\x03R\tnextRunAt\x12\x1e\n" +
	"\vlast_run_at\x18\x12 \x01(\x03R\tlastRunAt\x12\x1f\n" +
	"\vlast_status\x18\x13 \x01(\tR\n" +
	"lastStatus\x12#\n" +
	"\rlast_duration\x18\x14 \x01(\x03R\flastDuration\x12\x1d\n" +
	"\n" +
	"last_error\x18\x15 \x01(\tR\tlastError\"\x17\n" +
	"\x05IdReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1a\n" +
	"\x06IdsReq\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"1\n" +
	"\tEmptyResp\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\x99\x01\n" +
	"\n" +
	"JobListReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x18\n" +
	"\ahandler\x18\x03 \x01(\tR\ahandler\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x12\n" +
	"\x04page\x18\x05 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x06 \x01(\x05R\bpageSize\"I\n" +
	"\vJobListResp\x12$\n" +
	"\x04list\x18\x01 \x03(\v2\x10.job_service.JobR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\xef\x02\n" +
	"\x06JobLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03R\tcreatedAt\x12\x15\n" +
	"\x06job_id\x18\x03 \x01(\tR\x05jobId\x12\x19\n" +
	"\bjob_name\x18\x04 \x01(\tR\ajobName\x12\x1b\n" +
	"\tjob_group\x18\x05 \x01(\tR\bjobGroup\x12\x18\n" +
	"\ahandler\x18\x06 \x01(\tR\ahandler\x12!\n" +
	"\ftrigger_type\x18\a \x01(\tR\vtriggerType\x12\x1b\n" +
	"\texec_node\x18\b \x01(\tR\bexecNode\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12\x18\n" +
	"\aattempt\x18\n" +
	" \x01(\x05R\aattempt\x12\x18\n" +
	"\amessage\x18\v \x01(\tR\amessage\x12%\n" +
	"\x0eexception_info\x18\f \x01(\tR\rexceptionInfo\x12\x1a\n" +
	"\bduration\x18\r \x01(\x03R\bduration\"\xc4\x01\n" +
	"\rJobLogListReq\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x19\n" +
	"\bjob_name\x18\x02 \x01(\tR\ajobName\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"begin_time\x18\x04 \x01(\x03R\tbeginTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\x03R\aendTime\x12\x12\n" +
	"\x04page\x18\x06 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\a \x01(\x05R\bpageSize\"O\n" +
	"\x0eJobLogListResp\x12'\n" +
	"\x04list\x18\x01 \x03(\v2\x13.job_service.JobLogR\x04list\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"D\n" +
	"\x0eCleanJobLogReq\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x1b\n" +
	"\tkeep_days\x18\x02 \x01(\x05R\bkeepDays\"5\n" +
	"\vHandlerItem\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"?\n" +
	"\x0fHandlerListResp\x12,\n" +
	"\x04list\x18\x01 \x03(\v2\x18.job_service.HandlerItemR\x04list2\xad\x05\n" +
	"\aSysJobs\x122\n" +
	"\n" +
	"GetJobById\x12\x12.job_service.IdReq\x1a\x10.job_service.Job\x12?\n" +
	"\n" +
	"GetJobList\x12\x17.job_service.JobListReq\x1a\x18.job_service.JobListResp\x125\n" +
	"\tCreateJob\x12\x10.job_service.Job\x1a\x16.job_service.EmptyResp\x125\n" +
	"\tUpdateJob\x12\x10.job_service.Job\x1a\x16.job_service.EmptyResp\x128\n" +
	"\tDeleteJob\x12\x13.job_service.IdsReq\x1a\x16.job_service.EmptyResp\x126\n" +
	"\bStartJob\x12\x12.job_service.IdReq\x1a\x16.job_service.EmptyResp\x126\n" +
	"\bPauseJob\x12\x12.job_service.IdReq\x1a\x16.job_service.EmptyResp\x128\n" +
	"\n" +
	"RunJobOnce\x12\x12.job_service.IdReq\x1a\x16.job_service.EmptyResp\x12B\n" +
	"\vCleanJobLog\x12\x1b.job_service.CleanJobLogReq\x1a\x16.job_service.EmptyResp\x12H\n" +
	"\rGetJobLogList\x12\x1a.job_service.JobLogListReq\x1a\x1b.job_service.JobLogListResp\x12M\n" +
	"\x15GetRegisteredHandlers\x12\x16.google.protobuf.Empty\x1a\x1c.job_service.HandlerListRespB\bZ\x06./appsb\x06proto3"

var (
	file_job_service_proto_rawDescOnce sync.Once
	file_job_service_proto_rawDescData []byte
)

func file_job_service_proto_rawDescGZIP() []byte {
	file_job_service_proto_rawDescOnce.Do(func() {
		file_job_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_job_service_proto_rawDesc), len(file_job_service_proto_rawDesc)))
	})
	return file_job_service_proto_rawDescData
}

var file_job_service_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_job_service_proto_goTypes = []any{
	(*Job)(nil),             // 0: job_service.Job
	(*IdReq)(nil),           // 1: job_service.IdReq
	(*IdsReq)(nil),          // 2: job_service.IdsReq
	(*EmptyResp)(nil),       // 3: job_service.EmptyResp
	(*JobListReq)(nil),      // 4: job_service.JobListReq
	(*JobListResp)(nil),     // 5: job_service.JobListResp
	(*JobLog)(nil),          // 6: job_service.JobLog
	(*JobLogListReq)(nil),   // 7: job_service.JobLogListReq
	(*JobLogListResp)(nil),  // 8: job_service.JobLogListResp
	(*CleanJobLogReq)(nil),  // 9: job_service.CleanJobLogReq
	(*HandlerItem)(nil),     // 10: job_service.HandlerItem
	(*HandlerListResp)(nil), // 11: job_service.HandlerListResp
	(*emptypb.Empty)(nil),   // 12: google.protobuf.Empty
}
var file_job_service_proto_depIdxs = []int32{
	0,  // 0: job_service.JobListResp.list:type_name -> job_service.Job
	6,  // 1: job_service.JobLogListResp.list:type_name -> job_service.JobLog
	10, // 2: job_service.HandlerListResp.list:type_name -> job_service.HandlerItem
	1,  // 3: job_service.SysJobs.GetJobById:input_type -> job_service.IdReq
	4,  // 4: job_service.SysJobs.GetJobList:input_type -> job_service.JobListReq
	0,  // 5: job_service.SysJobs.CreateJob:input_type -> job_service.Job
	0,  // 6: job_service.SysJobs.UpdateJob:input_type -> job_service.Job
	2,  // 7: job_service.SysJobs.DeleteJob:input_type -> job_service.IdsReq
	1,  // 8: job_service.SysJobs.StartJob:input_type -> job_service.IdReq
	1,  // 9: job_service.SysJobs.PauseJob:input_type -> job_service.IdReq
	1,  // 10: job_service.SysJobs.RunJobOnce:input_type -> job_service.IdReq
	9,  // 11: job_service.SysJobs.CleanJobLog:input_type -> job_service.CleanJobLogReq
	7,  // 12: job_service.SysJobs.GetJobLogList:input_type -> job_service.JobLogListReq
	12, // 13: job_service.SysJobs.GetRegisteredHandlers:input_type -> google.protobuf.Empty
	0,  // 14: job_service.SysJobs.GetJobById:output_type -> job_service.Job
	5,  // 15: job_service.SysJobs.GetJobList:output_type -> job_service.JobListResp
	3,  // 16: job_service.SysJobs.CreateJob:output_type -> job_service.EmptyResp
	3,  // 17: job_service.SysJobs.UpdateJob:output_type -> job_service.EmptyResp
	3,  // 18: job_service.SysJobs.DeleteJob:output_type -> job_service.EmptyResp
	3,  // 19: job_service.SysJobs.StartJob:output_type -> job_service.EmptyResp
	3,  // 20: job_service.SysJobs.PauseJob:output_type -> job_service.EmptyResp
	3,  // 21: job_service.SysJobs.RunJobOnce:output_type -> job_service.EmptyResp
	3,  // 22: job_service.SysJobs.CleanJobLog:output_type -> job_service.EmptyResp
	8,  // 23: job_service.SysJobs.GetJobLogList:output_type -> job_service.JobLogListResp
	11, // 24: job_service.SysJobs.GetRegisteredHandlers:output_type -> job_service.HandlerListResp
	14, // [14:25] is the sub-list for method output_type
	3,  // [3:14] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_job_service_proto_init() }
func file_job_service_proto_init() {
	if File_job_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_job_service_proto_rawDesc), len(file_job_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_job_service_proto_goTypes,
		DependencyIndexes: file_job_service_proto_depIdxs,
		MessageInfos:      file_job_service_proto_msgTypes,
	}.Build()
	File_job_service_proto = out.File
	file_job_service_proto_goTypes = nil
	file_job_service_proto_depIdxs = nil
}
