// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"time"

	"github.com/saas-zero/saas-zero-job/ent/schema"
	"github.com/saas-zero/saas-zero-job/ent/sysjob"
	"github.com/saas-zero/saas-zero-job/ent/sysjoblog"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	sysjobMixin := schema.SysJob{}.Mixin()
	sysjobMixinHooks0 := sysjobMixin[0].Hooks()
	sysjobMixinHooks1 := sysjobMixin[1].Hooks()
	sysjobMixinHooks2 := sysjobMixin[2].Hooks()
	sysjobMixinHooks3 := sysjobMixin[3].Hooks()
	sysjob.Hooks[0] = sysjobMixinHooks0[0]
	sysjob.Hooks[1] = sysjobMixinHooks1[0]
	sysjob.Hooks[2] = sysjobMixinHooks2[0]
	sysjob.Hooks[3] = sysjobMixinHooks3[0]
	sysjobMixinFields0 := sysjobMixin[0].Fields()
	_ = sysjobMixinFields0
	sysjobMixinFields1 := sysjobMixin[1].Fields()
	_ = sysjobMixinFields1
	sysjobMixinFields2 := sysjobMixin[2].Fields()
	_ = sysjobMixinFields2
	sysjobMixinFields3 := sysjobMixin[3].Fields()
	_ = sysjobMixinFields3
	sysjobMixinFields4 := sysjobMixin[4].Fields()
	_ = sysjobMixinFields4
	sysjobMixinFields5 := sysjobMixin[5].Fields()
	_ = sysjobMixinFields5
	sysjobFields := schema.SysJob{}.Fields()
	_ = sysjobFields
	// sysjobDescCreatedAt is the schema descriptor for created_at field.
	sysjobDescCreatedAt := sysjobMixinFields1[0].Descriptor()
	// sysjob.DefaultCreatedAt holds the default value on creation for the created_at field.
	sysjob.DefaultCreatedAt = sysjobDescCreatedAt.Default.(func() time.Time)
	// sysjobDescCreatedID is the schema descriptor for created_id field.
	sysjobDescCreatedID := sysjobMixinFields1[1].Descriptor()
	// sysjob.CreatedIDValidator is a validator for the "created_id" field. It is called by the builders before save.
	sysjob.CreatedIDValidator = sysjobDescCreatedID.Validators[0].(func(int64) error)
	// sysjobDescCreatedBy is the schema descriptor for created_by field.
	sysjobDescCreatedBy := sysjobMixinFields1[2].Descriptor()
	// sysjob.CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	sysjob.CreatedByValidator = func() func(string) error {
		validators := sysjobDescCreatedBy.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(created_by string) error {
			for _, fn := range fns {
				if err := fn(created_by); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sysjobDescUpdatedAt is the schema descriptor for updated_at field.
	sysjobDescUpdatedAt := sysjobMixinFields2[0].Descriptor()
	// sysjob.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	sysjob.DefaultUpdatedAt = sysjobDescUpdatedAt.Default.(func() time.Time)
	// sysjobDescUpdatedID is the schema descriptor for updated_id field.
	sysjobDescUpdatedID := sysjobMixinFields2[1].Descriptor()
	// sysjob.UpdatedIDValidator is a validator for the "updated_id" field. It is called by the builders before save.
	sysjob.UpdatedIDValidator = sysjobDescUpdatedID.Validators[0].(func(int64) error)
	// sysjobDescUpdatedBy is the schema descriptor for updated_by field.
	sysjobDescUpdatedBy := sysjobMixinFields2[2].Descriptor()
	// sysjob.UpdatedByValidator is a validator for the "updated_by" field. It is called by the builders before save.
	sysjob.UpdatedByValidator = func() func(string) error {
		validators := sysjobDescUpdatedBy.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(updated_by string) error {
			for _, fn := range fns {
				if err := fn(updated_by); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sysjobDescDeletedBy is the schema descriptor for deleted_by field.
	sysjobDescDeletedBy := sysjobMixinFields3[2].Descriptor()
	// sysjob.DeletedByValidator is a validator for the "deleted_by" field. It is called by the builders before save.
	sysjob.DeletedByValidator = sysjobDescDeletedBy.Validators[0].(func(string) error)
	// sysjobDescRemark is the schema descriptor for remark field.
	sysjobDescRemark := sysjobMixinFields5[0].Descriptor()
	// sysjob.RemarkValidator is a validator for the "remark" field. It is called by the builders before save.
	sysjob.RemarkValidator = sysjobDescRemark.Validators[0].(func(string) error)
	// sysjobDescName is the schema descriptor for name field.
	sysjobDescName := sysjobFields[0].Descriptor()
	// sysjob.NameValidator is a validator for the "name" field. It is called by the builders before save.
	sysjob.NameValidator = func() func(string) error {
		validators := sysjobDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sysjobDescGroup is the schema descriptor for group field.
	sysjobDescGroup := sysjobFields[1].Descriptor()
	// sysjob.DefaultGroup holds the default value on creation for the group field.
	sysjob.DefaultGroup = sysjobDescGroup.Default.(string)
	// sysjob.GroupValidator is a validator for the "group" field. It is called by the builders before save.
	sysjob.GroupValidator = sysjobDescGroup.Validators[0].(func(string) error)
	// sysjobDescHandler is the schema descriptor for handler field.
	sysjobDescHandler := sysjobFields[2].Descriptor()
	// sysjob.HandlerValidator is a validator for the "handler" field. It is called by the builders before save.
	sysjob.HandlerValidator = func() func(string) error {
		validators := sysjobDescHandler.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(handler string) error {
			for _, fn := range fns {
				if err := fn(handler); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sysjobDescParams is the schema descriptor for params field.
	sysjobDescParams := sysjobFields[3].Descriptor()
	// sysjob.DefaultParams holds the default value on creation for the params field.
	sysjob.DefaultParams = sysjobDescParams.Default.(string)
	// sysjobDescCronExpression is the schema descriptor for cron_expression field.
	sysjobDescCronExpression := sysjobFields[4].Descriptor()
	// sysjob.CronExpressionValidator is a validator for the "cron_expression" field. It is called by the builders before save.
	sysjob.CronExpressionValidator = func() func(string) error {
		validators := sysjobDescCronExpression.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(cron_expression string) error {
			for _, fn := range fns {
				if err := fn(cron_expression); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sysjobDescTimeZone is the schema descriptor for time_zone field.
	sysjobDescTimeZone := sysjobFields[5].Descriptor()
	// sysjob.DefaultTimeZone holds the default value on creation for the time_zone field.
	sysjob.DefaultTimeZone = sysjobDescTimeZone.Default.(string)
	// sysjob.TimeZoneValidator is a validator for the "time_zone" field. It is called by the builders before save.
	sysjob.TimeZoneValidator = sysjobDescTimeZone.Validators[0].(func(string) error)
	// sysjobDescConcurrent is the schema descriptor for concurrent field.
	sysjobDescConcurrent := sysjobFields[7].Descriptor()
	// sysjob.DefaultConcurrent holds the default value on creation for the concurrent field.
	sysjob.DefaultConcurrent = sysjobDescConcurrent.Default.(bool)
	// sysjobDescTimeout is the schema descriptor for timeout field.
	sysjobDescTimeout := sysjobFields[8].Descriptor()
	// sysjob.DefaultTimeout holds the default value on creation for the timeout field.
	sysjob.DefaultTimeout = sysjobDescTimeout.Default.(int32)
	// sysjob.TimeoutValidator is a validator for the "timeout" field. It is called by the builders before save.
	sysjob.TimeoutValidator = sysjobDescTimeout.Validators[0].(func(int32) error)
	// sysjobDescMaxRetry is the schema descriptor for max_retry field.
	sysjobDescMaxRetry := sysjobFields[9].Descriptor()
	// sysjob.DefaultMaxRetry holds the default value on creation for the max_retry field.
	sysjob.DefaultMaxRetry = sysjobDescMaxRetry.Default.(int32)
	// sysjob.MaxRetryValidator is a validator for the "max_retry" field. It is called by the builders before save.
	sysjob.MaxRetryValidator = sysjobDescMaxRetry.Validators[0].(func(int32) error)
	// sysjobDescRetryInterval is the schema descriptor for retry_interval field.
	sysjobDescRetryInterval := sysjobFields[10].Descriptor()
	// sysjob.DefaultRetryInterval holds the default value on creation for the retry_interval field.
	sysjob.DefaultRetryInterval = sysjobDescRetryInterval.Default.(int32)
	// sysjob.RetryIntervalValidator is a validator for the "retry_interval" field. It is called by the builders before save.
	sysjob.RetryIntervalValidator = sysjobDescRetryInterval.Validators[0].(func(int32) error)
	// sysjobDescLastStatus is the schema descriptor for last_status field.
	sysjobDescLastStatus := sysjobFields[13].Descriptor()
	// sysjob.LastStatusValidator is a validator for the "last_status" field. It is called by the builders before save.
	sysjob.LastStatusValidator = sysjobDescLastStatus.Validators[0].(func(string) error)
	// sysjobDescLastError is the schema descriptor for last_error field.
	sysjobDescLastError := sysjobFields[15].Descriptor()
	// sysjob.LastErrorValidator is a validator for the "last_error" field. It is called by the builders before save.
	sysjob.LastErrorValidator = sysjobDescLastError.Validators[0].(func(string) error)
	// sysjobDescID is the schema descriptor for id field.
	sysjobDescID := sysjobMixinFields0[0].Descriptor()
	// sysjob.IDValidator is a validator for the "id" field. It is called by the builders before save.
	sysjob.IDValidator = sysjobDescID.Validators[0].(func(int64) error)
	sysjoblogMixin := schema.SysJobLog{}.Mixin()
	sysjoblogMixinHooks0 := sysjoblogMixin[0].Hooks()
	sysjoblogMixinHooks1 := sysjoblogMixin[1].Hooks()
	sysjoblog.Hooks[0] = sysjoblogMixinHooks0[0]
	sysjoblog.Hooks[1] = sysjoblogMixinHooks1[0]
	sysjoblogMixinFields0 := sysjoblogMixin[0].Fields()
	_ = sysjoblogMixinFields0
	sysjoblogMixinFields1 := sysjoblogMixin[1].Fields()
	_ = sysjoblogMixinFields1
	sysjoblogFields := schema.SysJobLog{}.Fields()
	_ = sysjoblogFields
	// sysjoblogDescCreatedAt is the schema descriptor for created_at field.
	sysjoblogDescCreatedAt := sysjoblogMixinFields1[0].Descriptor()
	// sysjoblog.DefaultCreatedAt holds the default value on creation for the created_at field.
	sysjoblog.DefaultCreatedAt = sysjoblogDescCreatedAt.Default.(func() time.Time)
	// sysjoblogDescCreatedID is the schema descriptor for created_id field.
	sysjoblogDescCreatedID := sysjoblogMixinFields1[1].Descriptor()
	// sysjoblog.CreatedIDValidator is a validator for the "created_id" field. It is called by the builders before save.
	sysjoblog.CreatedIDValidator = sysjoblogDescCreatedID.Validators[0].(func(int64) error)
	// sysjoblogDescCreatedBy is the schema descriptor for created_by field.
	sysjoblogDescCreatedBy := sysjoblogMixinFields1[2].Descriptor()
	// sysjoblog.CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	sysjoblog.CreatedByValidator = func() func(string) error {
		validators := sysjoblogDescCreatedBy.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(created_by string) error {
			for _, fn := range fns {
				if err := fn(created_by); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// sysjoblogDescJobID is the schema descriptor for job_id field.
	sysjoblogDescJobID := sysjoblogFields[0].Descriptor()
	// sysjoblog.JobIDValidator is a validator for the "job_id" field. It is called by the builders before save.
	sysjoblog.JobIDValidator = sysjoblogDescJobID.Validators[0].(func(int64) error)
	// sysjoblogDescJobName is the schema descriptor for job_name field.
	sysjoblogDescJobName := sysjoblogFields[1].Descriptor()
	// sysjoblog.DefaultJobName holds the default value on creation for the job_name field.
	sysjoblog.DefaultJobName = sysjoblogDescJobName.Default.(string)
	// sysjoblog.JobNameValidator is a validator for the "job_name" field. It is called by the builders before save.
	sysjoblog.JobNameValidator = sysjoblogDescJobName.Validators[0].(func(string) error)
	// sysjoblogDescJobGroup is the schema descriptor for job_group field.
	sysjoblogDescJobGroup := sysjoblogFields[2].Descriptor()
	// sysjoblog.DefaultJobGroup holds the default value on creation for the job_group field.
	sysjoblog.DefaultJobGroup = sysjoblogDescJobGroup.Default.(string)
	// sysjoblog.JobGroupValidator is a validator for the "job_group" field. It is called by the builders before save.
	sysjoblog.JobGroupValidator = sysjoblogDescJobGroup.Validators[0].(func(string) error)
	// sysjoblogDescHandler is the schema descriptor for handler field.
	sysjoblogDescHandler := sysjoblogFields[3].Descriptor()
	// sysjoblog.DefaultHandler holds the default value on creation for the handler field.
	sysjoblog.DefaultHandler = sysjoblogDescHandler.Default.(string)
	// sysjoblog.HandlerValidator is a validator for the "handler" field. It is called by the builders before save.
	sysjoblog.HandlerValidator = sysjoblogDescHandler.Validators[0].(func(string) error)
	// sysjoblogDescExecNode is the schema descriptor for exec_node field.
	sysjoblogDescExecNode := sysjoblogFields[5].Descriptor()
	// sysjoblog.DefaultExecNode holds the default value on creation for the exec_node field.
	sysjoblog.DefaultExecNode = sysjoblogDescExecNode.Default.(string)
	// sysjoblog.ExecNodeValidator is a validator for the "exec_node" field. It is called by the builders before save.
	sysjoblog.ExecNodeValidator = sysjoblogDescExecNode.Validators[0].(func(string) error)
	// sysjoblogDescAttempt is the schema descriptor for attempt field.
	sysjoblogDescAttempt := sysjoblogFields[7].Descriptor()
	// sysjoblog.DefaultAttempt holds the default value on creation for the attempt field.
	sysjoblog.DefaultAttempt = sysjoblogDescAttempt.Default.(int32)
	// sysjoblog.AttemptValidator is a validator for the "attempt" field. It is called by the builders before save.
	sysjoblog.AttemptValidator = sysjoblogDescAttempt.Validators[0].(func(int32) error)
	// sysjoblogDescMessage is the schema descriptor for message field.
	sysjoblogDescMessage := sysjoblogFields[8].Descriptor()
	// sysjoblog.DefaultMessage holds the default value on creation for the message field.
	sysjoblog.DefaultMessage = sysjoblogDescMessage.Default.(string)
	// sysjoblog.MessageValidator is a validator for the "message" field. It is called by the builders before save.
	sysjoblog.MessageValidator = sysjoblogDescMessage.Validators[0].(func(string) error)
	// sysjoblogDescExceptionInfo is the schema descriptor for exception_info field.
	sysjoblogDescExceptionInfo := sysjoblogFields[9].Descriptor()
	// sysjoblog.DefaultExceptionInfo holds the default value on creation for the exception_info field.
	sysjoblog.DefaultExceptionInfo = sysjoblogDescExceptionInfo.Default.(string)
	// sysjoblog.ExceptionInfoValidator is a validator for the "exception_info" field. It is called by the builders before save.
	sysjoblog.ExceptionInfoValidator = sysjoblogDescExceptionInfo.Validators[0].(func(string) error)
	// sysjoblogDescDuration is the schema descriptor for duration field.
	sysjoblogDescDuration := sysjoblogFields[10].Descriptor()
	// sysjoblog.DefaultDuration holds the default value on creation for the duration field.
	sysjoblog.DefaultDuration = sysjoblogDescDuration.Default.(int64)
	// sysjoblog.DurationValidator is a validator for the "duration" field. It is called by the builders before save.
	sysjoblog.DurationValidator = sysjoblogDescDuration.Validators[0].(func(int64) error)
	// sysjoblogDescID is the schema descriptor for id field.
	sysjoblogDescID := sysjoblogMixinFields0[0].Descriptor()
	// sysjoblog.IDValidator is a validator for the "id" field. It is called by the builders before save.
	sysjoblog.IDValidator = sysjoblogDescID.Validators[0].(func(int64) error)
}

const (
	Version = "v0.14.5"                                         // Version of ent codegen.
	Sum     = "h1:Rj2WOYJtCkWyFo6a+5wB3EfBRP0rnx1fMk6gGA0UUe4=" // Sum of ent codegen.
)
