// Code generated by ent, DO NOT EDIT.

package sysjob

import (
	"fmt"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the sysjob type in the database.
	Label = "sys_job"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldCreatedID holds the string denoting the created_id field in the database.
	FieldCreatedID = "created_id"
	// FieldCreatedBy holds the string denoting the created_by field in the database.
	FieldCreatedBy = "created_by"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUpdatedID holds the string denoting the updated_id field in the database.
	FieldUpdatedID = "updated_id"
	// FieldUpdatedBy holds the string denoting the updated_by field in the database.
	FieldUpdatedBy = "updated_by"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldDeletedID holds the string denoting the deleted_id field in the database.
	FieldDeletedID = "deleted_id"
	// FieldDeletedBy holds the string denoting the deleted_by field in the database.
	FieldDeletedBy = "deleted_by"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldRemark holds the string denoting the remark field in the database.
	FieldRemark = "remark"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldGroup holds the string denoting the group field in the database.
	FieldGroup = "group"
	// FieldHandler holds the string denoting the handler field in the database.
	FieldHandler = "handler"
	// FieldParams holds the string denoting the params field in the database.
	FieldParams = "params"
	// FieldCronExpression holds the string denoting the cron_expression field in the database.
	FieldCronExpression = "cron_expression"
	// FieldTimeZone holds the string denoting the time_zone field in the database.
	FieldTimeZone = "time_zone"
	// FieldMisfirePolicy holds the string denoting the misfire_policy field in the database.
	FieldMisfirePolicy = "misfire_policy"
	// FieldConcurrent holds the string denoting the concurrent field in the database.
	FieldConcurrent = "concurrent"
	// FieldTimeout holds the string denoting the timeout field in the database.
	FieldTimeout = "timeout"
	// FieldMaxRetry holds the string denoting the max_retry field in the database.
	FieldMaxRetry = "max_retry"
	// FieldRetryInterval holds the string denoting the retry_interval field in the database.
	FieldRetryInterval = "retry_interval"
	// FieldNextRunAt holds the string denoting the next_run_at field in the database.
	FieldNextRunAt = "next_run_at"
	// FieldLastRunAt holds the string denoting the last_run_at field in the database.
	FieldLastRunAt = "last_run_at"
	// FieldLastStatus holds the string denoting the last_status field in the database.
	FieldLastStatus = "last_status"
	// FieldLastDuration holds the string denoting the last_duration field in the database.
	FieldLastDuration = "last_duration"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// Table holds the table name of the sysjob in the database.
	Table = "sys_jobs"
)

// Columns holds all SQL columns for sysjob fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldCreatedID,
	FieldCreatedBy,
	FieldUpdatedAt,
	FieldUpdatedID,
	FieldUpdatedBy,
	FieldDeletedAt,
	FieldDeletedID,
	FieldDeletedBy,
	FieldStatus,
	FieldRemark,
	FieldName,
	FieldGroup,
	FieldHandler,
	FieldParams,
	FieldCronExpression,
	FieldTimeZone,
	FieldMisfirePolicy,
	FieldConcurrent,
	FieldTimeout,
	FieldMaxRetry,
	FieldRetryInterval,
	FieldNextRunAt,
	FieldLastRunAt,
	FieldLastStatus,
	FieldLastDuration,
	FieldLastError,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/saas-zero/saas-zero-job/ent/runtime"
var (
	Hooks [4]ent.Hook
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// CreatedIDValidator is a validator for the "created_id" field. It is called by the builders before save.
	CreatedIDValidator func(int64) error
	// CreatedByValidator is a validator for the "created_by" field. It is called by the builders before save.
	CreatedByValidator func(string) error
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdatedIDValidator is a validator for the "updated_id" field. It is called by the builders before save.
	UpdatedIDValidator func(int64) error
	// UpdatedByValidator is a validator for the "updated_by" field. It is called by the builders before save.
	UpdatedByValidator func(string) error
	// DeletedByValidator is a validator for the "deleted_by" field. It is called by the builders before save.
	DeletedByValidator func(string) error
	// RemarkValidator is a validator for the "remark" field. It is called by the builders before save.
	RemarkValidator func(string) error
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultGroup holds the default value on creation for the "group" field.
	DefaultGroup string
	// GroupValidator is a validator for the "group" field. It is called by the builders before save.
	GroupValidator func(string) error
	// HandlerValidator is a validator for the "handler" field. It is called by the builders before save.
	HandlerValidator func(string) error
	// DefaultParams holds the default value on creation for the "params" field.
	DefaultParams string
	// CronExpressionValidator is a validator for the "cron_expression" field. It is called by the builders before save.
	CronExpressionValidator func(string) error
	// DefaultTimeZone holds the default value on creation for the "time_zone" field.
	DefaultTimeZone string
	// TimeZoneValidator is a validator for the "time_zone" field. It is called by the builders before save.
	TimeZoneValidator func(string) error
	// DefaultConcurrent holds the default value on creation for the "concurrent" field.
	DefaultConcurrent bool
	// DefaultTimeout holds the default value on creation for the "timeout" field.
	DefaultTimeout int32
	// TimeoutValidator is a validator for the "timeout" field. It is called by the builders before save.
	TimeoutValidator func(int32) error
	// DefaultMaxRetry holds the default value on creation for the "max_retry" field.
	DefaultMaxRetry int32
	// MaxRetryValidator is a validator for the "max_retry" field. It is called by the builders before save.
	MaxRetryValidator func(int32) error
	// DefaultRetryInterval holds the default value on creation for the "retry_interval" field.
	DefaultRetryInterval int32
	// RetryIntervalValidator is a validator for the "retry_interval" field. It is called by the builders before save.
	RetryIntervalValidator func(int32) error
	// LastStatusValidator is a validator for the "last_status" field. It is called by the builders before save.
	LastStatusValidator func(string) error
	// LastErrorValidator is a validator for the "last_error" field. It is called by the builders before save.
	LastErrorValidator func(string) error
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int64) error
)

// Status defines the type for the "status" enum field.
type Status string

// StatusActive is the default value of the Status enum.
const DefaultStatus = StatusActive

// Status values.
const (
	StatusActive    Status = "active"
	StatusInactive  Status = "inactive"
	StatusSuspended Status = "suspended"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusActive, StatusInactive, StatusSuspended:
		return nil
	default:
		return fmt.Errorf("sysjob: invalid enum value for status field: %q", s)
	}
}

// MisfirePolicy defines the type for the "misfire_policy" enum field.
type MisfirePolicy string

// MisfirePolicyFireOnce is the default value of the MisfirePolicy enum.
const DefaultMisfirePolicy = MisfirePolicyFireOnce

// MisfirePolicy values.
const (
	MisfirePolicySkip     MisfirePolicy = "skip"
	MisfirePolicyFireOnce MisfirePolicy = "fire_once"
	MisfirePolicyFireAll  MisfirePolicy = "fire_all"
)

func (mp MisfirePolicy) String() string {
	return string(mp)
}

// MisfirePolicyValidator is a validator for the "misfire_policy" field enum values. It is called by the builders before save.
func MisfirePolicyValidator(mp MisfirePolicy) error {
	switch mp {
	case MisfirePolicySkip, MisfirePolicyFireOnce, MisfirePolicyFireAll:
		return nil
	default:
		return fmt.Errorf("sysjob: invalid enum value for misfire_policy field: %q", mp)
	}
}

// OrderOption defines the ordering options for the SysJob queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByCreatedID orders the results by the created_id field.
func ByCreatedID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedID, opts...).ToFunc()
}

// ByCreatedBy orders the results by the created_by field.
func ByCreatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedBy, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUpdatedID orders the results by the updated_id field.
func ByUpdatedID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedID, opts...).ToFunc()
}

// ByUpdatedBy orders the results by the updated_by field.
func ByUpdatedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedBy, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByDeletedID orders the results by the deleted_id field.
func ByDeletedID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedID, opts...).ToFunc()
}

// ByDeletedBy orders the results by the deleted_by field.
func ByDeletedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedBy, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByRemark orders the results by the remark field.
func ByRemark(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRemark, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByGroup orders the results by the group field.
func ByGroup(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroup, opts...).ToFunc()
}

// ByHandler orders the results by the handler field.
func ByHandler(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHandler, opts...).ToFunc()
}

// ByParams orders the results by the params field.
func ByParams(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldParams, opts...).ToFunc()
}

// ByCronExpression orders the results by the cron_expression field.
func ByCronExpression(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCronExpression, opts...).ToFunc()
}

// ByTimeZone orders the results by the time_zone field.
func ByTimeZone(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimeZone, opts...).ToFunc()
}

// ByMisfirePolicy orders the results by the misfire_policy field.
func ByMisfirePolicy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMisfirePolicy, opts...).ToFunc()
}

// ByConcurrent orders the results by the concurrent field.
func ByConcurrent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConcurrent, opts...).ToFunc()
}

// ByTimeout orders the results by the timeout field.
func ByTimeout(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimeout, opts...).ToFunc()
}

// ByMaxRetry orders the results by the max_retry field.
func ByMaxRetry(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxRetry, opts...).ToFunc()
}

// ByRetryInterval orders the results by the retry_interval field.
func ByRetryInterval(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRetryInterval, opts...).ToFunc()
}

// ByNextRunAt orders the results by the next_run_at field.
func ByNextRunAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextRunAt, opts...).ToFunc()
}

// ByLastRunAt orders the results by the last_run_at field.
func ByLastRunAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastRunAt, opts...).ToFunc()
}

// ByLastStatus orders the results by the last_status field.
func ByLastStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastStatus, opts...).ToFunc()
}

// ByLastDuration orders the results by the last_duration field.
func ByLastDuration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastDuration, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}
