// Code generated by ent, DO NOT EDIT.

package sysjob

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/saas-zero/saas-zero-job/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedID applies equality check predicate on the "created_id" field. It's identical to CreatedIDEQ.
func CreatedID(v int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldCreatedID, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedID applies equality check predicate on the "updated_id" field. It's identical to UpdatedIDEQ.
func UpdatedID(v int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldUpdatedID, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldUpdatedBy, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedID applies equality check predicate on the "deleted_id" field. It's identical to DeletedIDEQ.
func DeletedID(v int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldDeletedID, v))
}

// DeletedBy applies equality check predicate on the "deleted_by" field. It's identical to DeletedByEQ.
func DeletedBy(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldDeletedBy, v))
}

// Remark applies equality check predicate on the "remark" field. It's identical to RemarkEQ.
func Remark(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldRemark, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldName, v))
}

// Group applies equality check predicate on the "group" field. It's identical to GroupEQ.
func Group(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldGroup, v))
}

// Handler applies equality check predicate on the "handler" field. It's identical to HandlerEQ.
func Handler(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldHandler, v))
}

// Params applies equality check predicate on the "params" field. It's identical to ParamsEQ.
func Params(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldParams, v))
}

// CronExpression applies equality check predicate on the "cron_expression" field. It's identical to CronExpressionEQ.
func CronExpression(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldCronExpression, v))
}

// TimeZone applies equality check predicate on the "time_zone" field. It's identical to TimeZoneEQ.
func TimeZone(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldTimeZone, v))
}

// Concurrent applies equality check predicate on the "concurrent" field. It's identical to ConcurrentEQ.
func Concurrent(v bool) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldConcurrent, v))
}

// Timeout applies equality check predicate on the "timeout" field. It's identical to TimeoutEQ.
func Timeout(v int32) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldTimeout, v))
}

// MaxRetry applies equality check predicate on the "max_retry" field. It's identical to MaxRetryEQ.
func MaxRetry(v int32) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldMaxRetry, v))
}

// RetryInterval applies equality check predicate on the "retry_interval" field. It's identical to RetryIntervalEQ.
func RetryInterval(v int32) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldRetryInterval, v))
}

// NextRunAt applies equality check predicate on the "next_run_at" field. It's identical to NextRunAtEQ.
func NextRunAt(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldNextRunAt, v))
}

// LastRunAt applies equality check predicate on the "last_run_at" field. It's identical to LastRunAtEQ.
func LastRunAt(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldLastRunAt, v))
}

// LastStatus applies equality check predicate on the "last_status" field. It's identical to LastStatusEQ.
func LastStatus(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldLastStatus, v))
}

// LastDuration applies equality check predicate on the "last_duration" field. It's identical to LastDurationEQ.
func LastDuration(v int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldLastDuration, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldLastError, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedIDEQ applies the EQ predicate on the "created_id" field.
func CreatedIDEQ(v int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldCreatedID, v))
}

// CreatedIDNEQ applies the NEQ predicate on the "created_id" field.
func CreatedIDNEQ(v int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldNEQ(FieldCreatedID, v))
}

// CreatedIDIn applies the In predicate on the "created_id" field.
func CreatedIDIn(vs ...int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldIn(FieldCreatedID, vs...))
}

// CreatedIDNotIn applies the NotIn predicate on the "created_id" field.
func CreatedIDNotIn(vs ...int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldNotIn(FieldCreatedID, vs...))
}

// CreatedIDGT applies the GT predicate on the "created_id" field.
func CreatedIDGT(v int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldGT(FieldCreatedID, v))
}

// CreatedIDGTE applies the GTE predicate on the "created_id" field.
func CreatedIDGTE(v int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldGTE(FieldCreatedID, v))
}

// CreatedIDLT applies the LT predicate on the "created_id" field.
func CreatedIDLT(v int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldLT(FieldCreatedID, v))
}

// CreatedIDLTE applies the LTE predicate on the "created_id" field.
func CreatedIDLTE(v int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldLTE(FieldCreatedID, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.SysJob {
	return predicate.SysJob(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.SysJob {
	return predicate.SysJob(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldContainsFold(FieldCreatedBy, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedIDEQ applies the EQ predicate on the "updated_id" field.
func UpdatedIDEQ(v int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldUpdatedID, v))
}

// UpdatedIDNEQ applies the NEQ predicate on the "updated_id" field.
func UpdatedIDNEQ(v int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldNEQ(FieldUpdatedID, v))
}

// UpdatedIDIn applies the In predicate on the "updated_id" field.
func UpdatedIDIn(vs ...int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldIn(FieldUpdatedID, vs...))
}

// UpdatedIDNotIn applies the NotIn predicate on the "updated_id" field.
func UpdatedIDNotIn(vs ...int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldNotIn(FieldUpdatedID, vs...))
}

// UpdatedIDGT applies the GT predicate on the "updated_id" field.
func UpdatedIDGT(v int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldGT(FieldUpdatedID, v))
}

// UpdatedIDGTE applies the GTE predicate on the "updated_id" field.
func UpdatedIDGTE(v int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldGTE(FieldUpdatedID, v))
}

// UpdatedIDLT applies the LT predicate on the "updated_id" field.
func UpdatedIDLT(v int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldLT(FieldUpdatedID, v))
}

// UpdatedIDLTE applies the LTE predicate on the "updated_id" field.
func UpdatedIDLTE(v int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldLTE(FieldUpdatedID, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...string) predicate.SysJob {
	return predicate.SysJob(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...string) predicate.SysJob {
	return predicate.SysJob(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByContains applies the Contains predicate on the "updated_by" field.
func UpdatedByContains(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldContains(FieldUpdatedBy, v))
}

// UpdatedByHasPrefix applies the HasPrefix predicate on the "updated_by" field.
func UpdatedByHasPrefix(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldHasPrefix(FieldUpdatedBy, v))
}

// UpdatedByHasSuffix applies the HasSuffix predicate on the "updated_by" field.
func UpdatedByHasSuffix(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldHasSuffix(FieldUpdatedBy, v))
}

// UpdatedByEqualFold applies the EqualFold predicate on the "updated_by" field.
func UpdatedByEqualFold(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEqualFold(FieldUpdatedBy, v))
}

// UpdatedByContainsFold applies the ContainsFold predicate on the "updated_by" field.
func UpdatedByContainsFold(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldContainsFold(FieldUpdatedBy, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.SysJob {
	return predicate.SysJob(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.SysJob {
	return predicate.SysJob(sql.FieldNotNull(FieldDeletedAt))
}

// DeletedIDEQ applies the EQ predicate on the "deleted_id" field.
func DeletedIDEQ(v int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldDeletedID, v))
}

// DeletedIDNEQ applies the NEQ predicate on the "deleted_id" field.
func DeletedIDNEQ(v int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldNEQ(FieldDeletedID, v))
}

// DeletedIDIn applies the In predicate on the "deleted_id" field.
func DeletedIDIn(vs ...int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldIn(FieldDeletedID, vs...))
}

// DeletedIDNotIn applies the NotIn predicate on the "deleted_id" field.
func DeletedIDNotIn(vs ...int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldNotIn(FieldDeletedID, vs...))
}

// DeletedIDGT applies the GT predicate on the "deleted_id" field.
func DeletedIDGT(v int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldGT(FieldDeletedID, v))
}

// DeletedIDGTE applies the GTE predicate on the "deleted_id" field.
func DeletedIDGTE(v int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldGTE(FieldDeletedID, v))
}

// DeletedIDLT applies the LT predicate on the "deleted_id" field.
func DeletedIDLT(v int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldLT(FieldDeletedID, v))
}

// DeletedIDLTE applies the LTE predicate on the "deleted_id" field.
func DeletedIDLTE(v int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldLTE(FieldDeletedID, v))
}

// DeletedIDIsNil applies the IsNil predicate on the "deleted_id" field.
func DeletedIDIsNil() predicate.SysJob {
	return predicate.SysJob(sql.FieldIsNull(FieldDeletedID))
}

// DeletedIDNotNil applies the NotNil predicate on the "deleted_id" field.
func DeletedIDNotNil() predicate.SysJob {
	return predicate.SysJob(sql.FieldNotNull(FieldDeletedID))
}

// DeletedByEQ applies the EQ predicate on the "deleted_by" field.
func DeletedByEQ(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldDeletedBy, v))
}

// DeletedByNEQ applies the NEQ predicate on the "deleted_by" field.
func DeletedByNEQ(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldNEQ(FieldDeletedBy, v))
}

// DeletedByIn applies the In predicate on the "deleted_by" field.
func DeletedByIn(vs ...string) predicate.SysJob {
	return predicate.SysJob(sql.FieldIn(FieldDeletedBy, vs...))
}

// DeletedByNotIn applies the NotIn predicate on the "deleted_by" field.
func DeletedByNotIn(vs ...string) predicate.SysJob {
	return predicate.SysJob(sql.FieldNotIn(FieldDeletedBy, vs...))
}

// DeletedByGT applies the GT predicate on the "deleted_by" field.
func DeletedByGT(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldGT(FieldDeletedBy, v))
}

// DeletedByGTE applies the GTE predicate on the "deleted_by" field.
func DeletedByGTE(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldGTE(FieldDeletedBy, v))
}

// DeletedByLT applies the LT predicate on the "deleted_by" field.
func DeletedByLT(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldLT(FieldDeletedBy, v))
}

// DeletedByLTE applies the LTE predicate on the "deleted_by" field.
func DeletedByLTE(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldLTE(FieldDeletedBy, v))
}

// DeletedByContains applies the Contains predicate on the "deleted_by" field.
func DeletedByContains(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldContains(FieldDeletedBy, v))
}

// DeletedByHasPrefix applies the HasPrefix predicate on the "deleted_by" field.
func DeletedByHasPrefix(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldHasPrefix(FieldDeletedBy, v))
}

// DeletedByHasSuffix applies the HasSuffix predicate on the "deleted_by" field.
func DeletedByHasSuffix(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldHasSuffix(FieldDeletedBy, v))
}

// DeletedByIsNil applies the IsNil predicate on the "deleted_by" field.
func DeletedByIsNil() predicate.SysJob {
	return predicate.SysJob(sql.FieldIsNull(FieldDeletedBy))
}

// DeletedByNotNil applies the NotNil predicate on the "deleted_by" field.
func DeletedByNotNil() predicate.SysJob {
	return predicate.SysJob(sql.FieldNotNull(FieldDeletedBy))
}

// DeletedByEqualFold applies the EqualFold predicate on the "deleted_by" field.
func DeletedByEqualFold(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEqualFold(FieldDeletedBy, v))
}

// DeletedByContainsFold applies the ContainsFold predicate on the "deleted_by" field.
func DeletedByContainsFold(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldContainsFold(FieldDeletedBy, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.SysJob {
	return predicate.SysJob(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.SysJob {
	return predicate.SysJob(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.SysJob {
	return predicate.SysJob(sql.FieldNotIn(FieldStatus, vs...))
}

// RemarkEQ applies the EQ predicate on the "remark" field.
func RemarkEQ(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldRemark, v))
}

// RemarkNEQ applies the NEQ predicate on the "remark" field.
func RemarkNEQ(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldNEQ(FieldRemark, v))
}

// RemarkIn applies the In predicate on the "remark" field.
func RemarkIn(vs ...string) predicate.SysJob {
	return predicate.SysJob(sql.FieldIn(FieldRemark, vs...))
}

// RemarkNotIn applies the NotIn predicate on the "remark" field.
func RemarkNotIn(vs ...string) predicate.SysJob {
	return predicate.SysJob(sql.FieldNotIn(FieldRemark, vs...))
}

// RemarkGT applies the GT predicate on the "remark" field.
func RemarkGT(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldGT(FieldRemark, v))
}

// RemarkGTE applies the GTE predicate on the "remark" field.
func RemarkGTE(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldGTE(FieldRemark, v))
}

// RemarkLT applies the LT predicate on the "remark" field.
func RemarkLT(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldLT(FieldRemark, v))
}

// RemarkLTE applies the LTE predicate on the "remark" field.
func RemarkLTE(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldLTE(FieldRemark, v))
}

// RemarkContains applies the Contains predicate on the "remark" field.
func RemarkContains(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldContains(FieldRemark, v))
}

// RemarkHasPrefix applies the HasPrefix predicate on the "remark" field.
func RemarkHasPrefix(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldHasPrefix(FieldRemark, v))
}

// RemarkHasSuffix applies the HasSuffix predicate on the "remark" field.
func RemarkHasSuffix(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldHasSuffix(FieldRemark, v))
}

// RemarkIsNil applies the IsNil predicate on the "remark" field.
func RemarkIsNil() predicate.SysJob {
	return predicate.SysJob(sql.FieldIsNull(FieldRemark))
}

// RemarkNotNil applies the NotNil predicate on the "remark" field.
func RemarkNotNil() predicate.SysJob {
	return predicate.SysJob(sql.FieldNotNull(FieldRemark))
}

// RemarkEqualFold applies the EqualFold predicate on the "remark" field.
func RemarkEqualFold(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEqualFold(FieldRemark, v))
}

// RemarkContainsFold applies the ContainsFold predicate on the "remark" field.
func RemarkContainsFold(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldContainsFold(FieldRemark, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.SysJob {
	return predicate.SysJob(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.SysJob {
	return predicate.SysJob(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldContainsFold(FieldName, v))
}

// GroupEQ applies the EQ predicate on the "group" field.
func GroupEQ(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldGroup, v))
}

// GroupNEQ applies the NEQ predicate on the "group" field.
func GroupNEQ(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldNEQ(FieldGroup, v))
}

// GroupIn applies the In predicate on the "group" field.
func GroupIn(vs ...string) predicate.SysJob {
	return predicate.SysJob(sql.FieldIn(FieldGroup, vs...))
}

// GroupNotIn applies the NotIn predicate on the "group" field.
func GroupNotIn(vs ...string) predicate.SysJob {
	return predicate.SysJob(sql.FieldNotIn(FieldGroup, vs...))
}

// GroupGT applies the GT predicate on the "group" field.
func GroupGT(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldGT(FieldGroup, v))
}

// GroupGTE applies the GTE predicate on the "group" field.
func GroupGTE(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldGTE(FieldGroup, v))
}

// GroupLT applies the LT predicate on the "group" field.
func GroupLT(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldLT(FieldGroup, v))
}

// GroupLTE applies the LTE predicate on the "group" field.
func GroupLTE(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldLTE(FieldGroup, v))
}

// GroupContains applies the Contains predicate on the "group" field.
func GroupContains(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldContains(FieldGroup, v))
}

// GroupHasPrefix applies the HasPrefix predicate on the "group" field.
func GroupHasPrefix(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldHasPrefix(FieldGroup, v))
}

// GroupHasSuffix applies the HasSuffix predicate on the "group" field.
func GroupHasSuffix(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldHasSuffix(FieldGroup, v))
}

// GroupEqualFold applies the EqualFold predicate on the "group" field.
func GroupEqualFold(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEqualFold(FieldGroup, v))
}

// GroupContainsFold applies the ContainsFold predicate on the "group" field.
func GroupContainsFold(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldContainsFold(FieldGroup, v))
}

// HandlerEQ applies the EQ predicate on the "handler" field.
func HandlerEQ(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldHandler, v))
}

// HandlerNEQ applies the NEQ predicate on the "handler" field.
func HandlerNEQ(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldNEQ(FieldHandler, v))
}

// HandlerIn applies the In predicate on the "handler" field.
func HandlerIn(vs ...string) predicate.SysJob {
	return predicate.SysJob(sql.FieldIn(FieldHandler, vs...))
}

// HandlerNotIn applies the NotIn predicate on the "handler" field.
func HandlerNotIn(vs ...string) predicate.SysJob {
	return predicate.SysJob(sql.FieldNotIn(FieldHandler, vs...))
}

// HandlerGT applies the GT predicate on the "handler" field.
func HandlerGT(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldGT(FieldHandler, v))
}

// HandlerGTE applies the GTE predicate on the "handler" field.
func HandlerGTE(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldGTE(FieldHandler, v))
}

// HandlerLT applies the LT predicate on the "handler" field.
func HandlerLT(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldLT(FieldHandler, v))
}

// HandlerLTE applies the LTE predicate on the "handler" field.
func HandlerLTE(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldLTE(FieldHandler, v))
}

// HandlerContains applies the Contains predicate on the "handler" field.
func HandlerContains(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldContains(FieldHandler, v))
}

// HandlerHasPrefix applies the HasPrefix predicate on the "handler" field.
func HandlerHasPrefix(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldHasPrefix(FieldHandler, v))
}

// HandlerHasSuffix applies the HasSuffix predicate on the "handler" field.
func HandlerHasSuffix(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldHasSuffix(FieldHandler, v))
}

// HandlerEqualFold applies the EqualFold predicate on the "handler" field.
func HandlerEqualFold(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEqualFold(FieldHandler, v))
}

// HandlerContainsFold applies the ContainsFold predicate on the "handler" field.
func HandlerContainsFold(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldContainsFold(FieldHandler, v))
}

// ParamsEQ applies the EQ predicate on the "params" field.
func ParamsEQ(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldParams, v))
}

// ParamsNEQ applies the NEQ predicate on the "params" field.
func ParamsNEQ(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldNEQ(FieldParams, v))
}

// ParamsIn applies the In predicate on the "params" field.
func ParamsIn(vs ...string) predicate.SysJob {
	return predicate.SysJob(sql.FieldIn(FieldParams, vs...))
}

// ParamsNotIn applies the NotIn predicate on the "params" field.
func ParamsNotIn(vs ...string) predicate.SysJob {
	return predicate.SysJob(sql.FieldNotIn(FieldParams, vs...))
}

// ParamsGT applies the GT predicate on the "params" field.
func ParamsGT(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldGT(FieldParams, v))
}

// ParamsGTE applies the GTE predicate on the "params" field.
func ParamsGTE(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldGTE(FieldParams, v))
}

// ParamsLT applies the LT predicate on the "params" field.
func ParamsLT(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldLT(FieldParams, v))
}

// ParamsLTE applies the LTE predicate on the "params" field.
func ParamsLTE(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldLTE(FieldParams, v))
}

// ParamsContains applies the Contains predicate on the "params" field.
func ParamsContains(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldContains(FieldParams, v))
}

// ParamsHasPrefix applies the HasPrefix predicate on the "params" field.
func ParamsHasPrefix(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldHasPrefix(FieldParams, v))
}

// ParamsHasSuffix applies the HasSuffix predicate on the "params" field.
func ParamsHasSuffix(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldHasSuffix(FieldParams, v))
}

// ParamsEqualFold applies the EqualFold predicate on the "params" field.
func ParamsEqualFold(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEqualFold(FieldParams, v))
}

// ParamsContainsFold applies the ContainsFold predicate on the "params" field.
func ParamsContainsFold(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldContainsFold(FieldParams, v))
}

// CronExpressionEQ applies the EQ predicate on the "cron_expression" field.
func CronExpressionEQ(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldCronExpression, v))
}

// CronExpressionNEQ applies the NEQ predicate on the "cron_expression" field.
func CronExpressionNEQ(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldNEQ(FieldCronExpression, v))
}

// CronExpressionIn applies the In predicate on the "cron_expression" field.
func CronExpressionIn(vs ...string) predicate.SysJob {
	return predicate.SysJob(sql.FieldIn(FieldCronExpression, vs...))
}

// CronExpressionNotIn applies the NotIn predicate on the "cron_expression" field.
func CronExpressionNotIn(vs ...string) predicate.SysJob {
	return predicate.SysJob(sql.FieldNotIn(FieldCronExpression, vs...))
}

// CronExpressionGT applies the GT predicate on the "cron_expression" field.
func CronExpressionGT(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldGT(FieldCronExpression, v))
}

// CronExpressionGTE applies the GTE predicate on the "cron_expression" field.
func CronExpressionGTE(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldGTE(FieldCronExpression, v))
}

// CronExpressionLT applies the LT predicate on the "cron_expression" field.
func CronExpressionLT(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldLT(FieldCronExpression, v))
}

// CronExpressionLTE applies the LTE predicate on the "cron_expression" field.
func CronExpressionLTE(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldLTE(FieldCronExpression, v))
}

// CronExpressionContains applies the Contains predicate on the "cron_expression" field.
func CronExpressionContains(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldContains(FieldCronExpression, v))
}

// CronExpressionHasPrefix applies the HasPrefix predicate on the "cron_expression" field.
func CronExpressionHasPrefix(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldHasPrefix(FieldCronExpression, v))
}

// CronExpressionHasSuffix applies the HasSuffix predicate on the "cron_expression" field.
func CronExpressionHasSuffix(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldHasSuffix(FieldCronExpression, v))
}

// CronExpressionEqualFold applies the EqualFold predicate on the "cron_expression" field.
func CronExpressionEqualFold(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEqualFold(FieldCronExpression, v))
}

// CronExpressionContainsFold applies the ContainsFold predicate on the "cron_expression" field.
func CronExpressionContainsFold(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldContainsFold(FieldCronExpression, v))
}

// TimeZoneEQ applies the EQ predicate on the "time_zone" field.
func TimeZoneEQ(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldTimeZone, v))
}

// TimeZoneNEQ applies the NEQ predicate on the "time_zone" field.
func TimeZoneNEQ(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldNEQ(FieldTimeZone, v))
}

// TimeZoneIn applies the In predicate on the "time_zone" field.
func TimeZoneIn(vs ...string) predicate.SysJob {
	return predicate.SysJob(sql.FieldIn(FieldTimeZone, vs...))
}

// TimeZoneNotIn applies the NotIn predicate on the "time_zone" field.
func TimeZoneNotIn(vs ...string) predicate.SysJob {
	return predicate.SysJob(sql.FieldNotIn(FieldTimeZone, vs...))
}

// TimeZoneGT applies the GT predicate on the "time_zone" field.
func TimeZoneGT(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldGT(FieldTimeZone, v))
}

// TimeZoneGTE applies the GTE predicate on the "time_zone" field.
func TimeZoneGTE(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldGTE(FieldTimeZone, v))
}

// TimeZoneLT applies the LT predicate on the "time_zone" field.
func TimeZoneLT(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldLT(FieldTimeZone, v))
}

// TimeZoneLTE applies the LTE predicate on the "time_zone" field.
func TimeZoneLTE(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldLTE(FieldTimeZone, v))
}

// TimeZoneContains applies the Contains predicate on the "time_zone" field.
func TimeZoneContains(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldContains(FieldTimeZone, v))
}

// TimeZoneHasPrefix applies the HasPrefix predicate on the "time_zone" field.
func TimeZoneHasPrefix(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldHasPrefix(FieldTimeZone, v))
}

// TimeZoneHasSuffix applies the HasSuffix predicate on the "time_zone" field.
func TimeZoneHasSuffix(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldHasSuffix(FieldTimeZone, v))
}

// TimeZoneEqualFold applies the EqualFold predicate on the "time_zone" field.
func TimeZoneEqualFold(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEqualFold(FieldTimeZone, v))
}

// TimeZoneContainsFold applies the ContainsFold predicate on the "time_zone" field.
func TimeZoneContainsFold(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldContainsFold(FieldTimeZone, v))
}

// MisfirePolicyEQ applies the EQ predicate on the "misfire_policy" field.
func MisfirePolicyEQ(v MisfirePolicy) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldMisfirePolicy, v))
}

// MisfirePolicyNEQ applies the NEQ predicate on the "misfire_policy" field.
func MisfirePolicyNEQ(v MisfirePolicy) predicate.SysJob {
	return predicate.SysJob(sql.FieldNEQ(FieldMisfirePolicy, v))
}

// MisfirePolicyIn applies the In predicate on the "misfire_policy" field.
func MisfirePolicyIn(vs ...MisfirePolicy) predicate.SysJob {
	return predicate.SysJob(sql.FieldIn(FieldMisfirePolicy, vs...))
}

// MisfirePolicyNotIn applies the NotIn predicate on the "misfire_policy" field.
func MisfirePolicyNotIn(vs ...MisfirePolicy) predicate.SysJob {
	return predicate.SysJob(sql.FieldNotIn(FieldMisfirePolicy, vs...))
}

// ConcurrentEQ applies the EQ predicate on the "concurrent" field.
func ConcurrentEQ(v bool) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldConcurrent, v))
}

// ConcurrentNEQ applies the NEQ predicate on the "concurrent" field.
func ConcurrentNEQ(v bool) predicate.SysJob {
	return predicate.SysJob(sql.FieldNEQ(FieldConcurrent, v))
}

// TimeoutEQ applies the EQ predicate on the "timeout" field.
func TimeoutEQ(v int32) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldTimeout, v))
}

// TimeoutNEQ applies the NEQ predicate on the "timeout" field.
func TimeoutNEQ(v int32) predicate.SysJob {
	return predicate.SysJob(sql.FieldNEQ(FieldTimeout, v))
}

// TimeoutIn applies the In predicate on the "timeout" field.
func TimeoutIn(vs ...int32) predicate.SysJob {
	return predicate.SysJob(sql.FieldIn(FieldTimeout, vs...))
}

// TimeoutNotIn applies the NotIn predicate on the "timeout" field.
func TimeoutNotIn(vs ...int32) predicate.SysJob {
	return predicate.SysJob(sql.FieldNotIn(FieldTimeout, vs...))
}

// TimeoutGT applies the GT predicate on the "timeout" field.
func TimeoutGT(v int32) predicate.SysJob {
	return predicate.SysJob(sql.FieldGT(FieldTimeout, v))
}

// TimeoutGTE applies the GTE predicate on the "timeout" field.
func TimeoutGTE(v int32) predicate.SysJob {
	return predicate.SysJob(sql.FieldGTE(FieldTimeout, v))
}

// TimeoutLT applies the LT predicate on the "timeout" field.
func TimeoutLT(v int32) predicate.SysJob {
	return predicate.SysJob(sql.FieldLT(FieldTimeout, v))
}

// TimeoutLTE applies the LTE predicate on the "timeout" field.
func TimeoutLTE(v int32) predicate.SysJob {
	return predicate.SysJob(sql.FieldLTE(FieldTimeout, v))
}

// MaxRetryEQ applies the EQ predicate on the "max_retry" field.
func MaxRetryEQ(v int32) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldMaxRetry, v))
}

// MaxRetryNEQ applies the NEQ predicate on the "max_retry" field.
func MaxRetryNEQ(v int32) predicate.SysJob {
	return predicate.SysJob(sql.FieldNEQ(FieldMaxRetry, v))
}

// MaxRetryIn applies the In predicate on the "max_retry" field.
func MaxRetryIn(vs ...int32) predicate.SysJob {
	return predicate.SysJob(sql.FieldIn(FieldMaxRetry, vs...))
}

// MaxRetryNotIn applies the NotIn predicate on the "max_retry" field.
func MaxRetryNotIn(vs ...int32) predicate.SysJob {
	return predicate.SysJob(sql.FieldNotIn(FieldMaxRetry, vs...))
}

// MaxRetryGT applies the GT predicate on the "max_retry" field.
func MaxRetryGT(v int32) predicate.SysJob {
	return predicate.SysJob(sql.FieldGT(FieldMaxRetry, v))
}

// MaxRetryGTE applies the GTE predicate on the "max_retry" field.
func MaxRetryGTE(v int32) predicate.SysJob {
	return predicate.SysJob(sql.FieldGTE(FieldMaxRetry, v))
}

// MaxRetryLT applies the LT predicate on the "max_retry" field.
func MaxRetryLT(v int32) predicate.SysJob {
	return predicate.SysJob(sql.FieldLT(FieldMaxRetry, v))
}

// MaxRetryLTE applies the LTE predicate on the "max_retry" field.
func MaxRetryLTE(v int32) predicate.SysJob {
	return predicate.SysJob(sql.FieldLTE(FieldMaxRetry, v))
}

// RetryIntervalEQ applies the EQ predicate on the "retry_interval" field.
func RetryIntervalEQ(v int32) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldRetryInterval, v))
}

// RetryIntervalNEQ applies the NEQ predicate on the "retry_interval" field.
func RetryIntervalNEQ(v int32) predicate.SysJob {
	return predicate.SysJob(sql.FieldNEQ(FieldRetryInterval, v))
}

// RetryIntervalIn applies the In predicate on the "retry_interval" field.
func RetryIntervalIn(vs ...int32) predicate.SysJob {
	return predicate.SysJob(sql.FieldIn(FieldRetryInterval, vs...))
}

// RetryIntervalNotIn applies the NotIn predicate on the "retry_interval" field.
func RetryIntervalNotIn(vs ...int32) predicate.SysJob {
	return predicate.SysJob(sql.FieldNotIn(FieldRetryInterval, vs...))
}

// RetryIntervalGT applies the GT predicate on the "retry_interval" field.
func RetryIntervalGT(v int32) predicate.SysJob {
	return predicate.SysJob(sql.FieldGT(FieldRetryInterval, v))
}

// RetryIntervalGTE applies the GTE predicate on the "retry_interval" field.
func RetryIntervalGTE(v int32) predicate.SysJob {
	return predicate.SysJob(sql.FieldGTE(FieldRetryInterval, v))
}

// RetryIntervalLT applies the LT predicate on the "retry_interval" field.
func RetryIntervalLT(v int32) predicate.SysJob {
	return predicate.SysJob(sql.FieldLT(FieldRetryInterval, v))
}

// RetryIntervalLTE applies the LTE predicate on the "retry_interval" field.
func RetryIntervalLTE(v int32) predicate.SysJob {
	return predicate.SysJob(sql.FieldLTE(FieldRetryInterval, v))
}

// NextRunAtEQ applies the EQ predicate on the "next_run_at" field.
func NextRunAtEQ(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldNextRunAt, v))
}

// NextRunAtNEQ applies the NEQ predicate on the "next_run_at" field.
func NextRunAtNEQ(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldNEQ(FieldNextRunAt, v))
}

// NextRunAtIn applies the In predicate on the "next_run_at" field.
func NextRunAtIn(vs ...time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldIn(FieldNextRunAt, vs...))
}

// NextRunAtNotIn applies the NotIn predicate on the "next_run_at" field.
func NextRunAtNotIn(vs ...time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldNotIn(FieldNextRunAt, vs...))
}

// NextRunAtGT applies the GT predicate on the "next_run_at" field.
func NextRunAtGT(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldGT(FieldNextRunAt, v))
}

// NextRunAtGTE applies the GTE predicate on the "next_run_at" field.
func NextRunAtGTE(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldGTE(FieldNextRunAt, v))
}

// NextRunAtLT applies the LT predicate on the "next_run_at" field.
func NextRunAtLT(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldLT(FieldNextRunAt, v))
}

// NextRunAtLTE applies the LTE predicate on the "next_run_at" field.
func NextRunAtLTE(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldLTE(FieldNextRunAt, v))
}

// NextRunAtIsNil applies the IsNil predicate on the "next_run_at" field.
func NextRunAtIsNil() predicate.SysJob {
	return predicate.SysJob(sql.FieldIsNull(FieldNextRunAt))
}

// NextRunAtNotNil applies the NotNil predicate on the "next_run_at" field.
func NextRunAtNotNil() predicate.SysJob {
	return predicate.SysJob(sql.FieldNotNull(FieldNextRunAt))
}

// LastRunAtEQ applies the EQ predicate on the "last_run_at" field.
func LastRunAtEQ(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldLastRunAt, v))
}

// LastRunAtNEQ applies the NEQ predicate on the "last_run_at" field.
func LastRunAtNEQ(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldNEQ(FieldLastRunAt, v))
}

// LastRunAtIn applies the In predicate on the "last_run_at" field.
func LastRunAtIn(vs ...time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldIn(FieldLastRunAt, vs...))
}

// LastRunAtNotIn applies the NotIn predicate on the "last_run_at" field.
func LastRunAtNotIn(vs ...time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldNotIn(FieldLastRunAt, vs...))
}

// LastRunAtGT applies the GT predicate on the "last_run_at" field.
func LastRunAtGT(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldGT(FieldLastRunAt, v))
}

// LastRunAtGTE applies the GTE predicate on the "last_run_at" field.
func LastRunAtGTE(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldGTE(FieldLastRunAt, v))
}

// LastRunAtLT applies the LT predicate on the "last_run_at" field.
func LastRunAtLT(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldLT(FieldLastRunAt, v))
}

// LastRunAtLTE applies the LTE predicate on the "last_run_at" field.
func LastRunAtLTE(v time.Time) predicate.SysJob {
	return predicate.SysJob(sql.FieldLTE(FieldLastRunAt, v))
}

// LastRunAtIsNil applies the IsNil predicate on the "last_run_at" field.
func LastRunAtIsNil() predicate.SysJob {
	return predicate.SysJob(sql.FieldIsNull(FieldLastRunAt))
}

// LastRunAtNotNil applies the NotNil predicate on the "last_run_at" field.
func LastRunAtNotNil() predicate.SysJob {
	return predicate.SysJob(sql.FieldNotNull(FieldLastRunAt))
}

// LastStatusEQ applies the EQ predicate on the "last_status" field.
func LastStatusEQ(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldLastStatus, v))
}

// LastStatusNEQ applies the NEQ predicate on the "last_status" field.
func LastStatusNEQ(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldNEQ(FieldLastStatus, v))
}

// LastStatusIn applies the In predicate on the "last_status" field.
func LastStatusIn(vs ...string) predicate.SysJob {
	return predicate.SysJob(sql.FieldIn(FieldLastStatus, vs...))
}

// LastStatusNotIn applies the NotIn predicate on the "last_status" field.
func LastStatusNotIn(vs ...string) predicate.SysJob {
	return predicate.SysJob(sql.FieldNotIn(FieldLastStatus, vs...))
}

// LastStatusGT applies the GT predicate on the "last_status" field.
func LastStatusGT(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldGT(FieldLastStatus, v))
}

// LastStatusGTE applies the GTE predicate on the "last_status" field.
func LastStatusGTE(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldGTE(FieldLastStatus, v))
}

// LastStatusLT applies the LT predicate on the "last_status" field.
func LastStatusLT(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldLT(FieldLastStatus, v))
}

// LastStatusLTE applies the LTE predicate on the "last_status" field.
func LastStatusLTE(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldLTE(FieldLastStatus, v))
}

// LastStatusContains applies the Contains predicate on the "last_status" field.
func LastStatusContains(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldContains(FieldLastStatus, v))
}

// LastStatusHasPrefix applies the HasPrefix predicate on the "last_status" field.
func LastStatusHasPrefix(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldHasPrefix(FieldLastStatus, v))
}

// LastStatusHasSuffix applies the HasSuffix predicate on the "last_status" field.
func LastStatusHasSuffix(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldHasSuffix(FieldLastStatus, v))
}

// LastStatusIsNil applies the IsNil predicate on the "last_status" field.
func LastStatusIsNil() predicate.SysJob {
	return predicate.SysJob(sql.FieldIsNull(FieldLastStatus))
}

// LastStatusNotNil applies the NotNil predicate on the "last_status" field.
func LastStatusNotNil() predicate.SysJob {
	return predicate.SysJob(sql.FieldNotNull(FieldLastStatus))
}

// LastStatusEqualFold applies the EqualFold predicate on the "last_status" field.
func LastStatusEqualFold(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEqualFold(FieldLastStatus, v))
}

// LastStatusContainsFold applies the ContainsFold predicate on the "last_status" field.
func LastStatusContainsFold(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldContainsFold(FieldLastStatus, v))
}

// LastDurationEQ applies the EQ predicate on the "last_duration" field.
func LastDurationEQ(v int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldLastDuration, v))
}

// LastDurationNEQ applies the NEQ predicate on the "last_duration" field.
func LastDurationNEQ(v int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldNEQ(FieldLastDuration, v))
}

// LastDurationIn applies the In predicate on the "last_duration" field.
func LastDurationIn(vs ...int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldIn(FieldLastDuration, vs...))
}

// LastDurationNotIn applies the NotIn predicate on the "last_duration" field.
func LastDurationNotIn(vs ...int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldNotIn(FieldLastDuration, vs...))
}

// LastDurationGT applies the GT predicate on the "last_duration" field.
func LastDurationGT(v int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldGT(FieldLastDuration, v))
}

// LastDurationGTE applies the GTE predicate on the "last_duration" field.
func LastDurationGTE(v int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldGTE(FieldLastDuration, v))
}

// LastDurationLT applies the LT predicate on the "last_duration" field.
func LastDurationLT(v int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldLT(FieldLastDuration, v))
}

// LastDurationLTE applies the LTE predicate on the "last_duration" field.
func LastDurationLTE(v int64) predicate.SysJob {
	return predicate.SysJob(sql.FieldLTE(FieldLastDuration, v))
}

// LastDurationIsNil applies the IsNil predicate on the "last_duration" field.
func LastDurationIsNil() predicate.SysJob {
	return predicate.SysJob(sql.FieldIsNull(FieldLastDuration))
}

// LastDurationNotNil applies the NotNil predicate on the "last_duration" field.
func LastDurationNotNil() predicate.SysJob {
	return predicate.SysJob(sql.FieldNotNull(FieldLastDuration))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.SysJob {
	return predicate.SysJob(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.SysJob {
	return predicate.SysJob(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorIsNil applies the IsNil predicate on the "last_error" field.
func LastErrorIsNil() predicate.SysJob {
	return predicate.SysJob(sql.FieldIsNull(FieldLastError))
}

// LastErrorNotNil applies the NotNil predicate on the "last_error" field.
func LastErrorNotNil() predicate.SysJob {
	return predicate.SysJob(sql.FieldNotNull(FieldLastError))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.SysJob {
	return predicate.SysJob(sql.FieldContainsFold(FieldLastError, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SysJob) predicate.SysJob {
	return predicate.SysJob(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SysJob) predicate.SysJob {
	return predicate.SysJob(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SysJob) predicate.SysJob {
	return predicate.SysJob(sql.NotPredicates(p))
}
